import typing
from typing import Protocol

import java.lang
import java.lang.annotation
import java.net
import java.nio
import java.nio.channels
import java.nio.charset
import java.nio.file
import java.security
import java.util
import java.util.function
import java.util.stream
import jpype
import jpype.protocol

class Closeable(java.lang.AutoCloseable):
    def close(self) -> None: ...

class DataInput:
    def readBoolean(self) -> bool: ...
    def readByte(self) -> int: ...
    def readChar(self) -> str: ...
    def readDouble(self) -> float: ...
    def readFloat(self) -> float: ...
    @typing.overload
    def readFully(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def readFully(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    def readInt(self) -> int: ...
    def readLine(self) -> java.lang.String: ...
    def readLong(self) -> int: ...
    def readShort(self) -> int: ...
    def readUTF(self) -> java.lang.String: ...
    def readUnsignedByte(self) -> int: ...
    def readUnsignedShort(self) -> int: ...
    def skipBytes(self, int: int) -> int: ...

class DataOutput:
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    def writeBoolean(self, boolean: bool) -> None: ...
    def writeByte(self, int: int) -> None: ...
    def writeBytes(self, string: java.lang.String | str) -> None: ...
    def writeChar(self, int: int) -> None: ...
    def writeChars(self, string: java.lang.String | str) -> None: ...
    def writeDouble(self, double: float) -> None: ...
    def writeFloat(self, float: float) -> None: ...
    def writeInt(self, int: int) -> None: ...
    def writeLong(self, long: int) -> None: ...
    def writeShort(self, int: int) -> None: ...
    def writeUTF(self, string: java.lang.String | str) -> None: ...

class FileDescriptor:
    in_: typing.ClassVar[FileDescriptor] = ...
    out: typing.ClassVar[FileDescriptor] = ...
    err: typing.ClassVar[FileDescriptor] = ...
    def __init__(self): ...
    def sync(self) -> None: ...
    def valid(self) -> bool: ...

class FileFilter:
    def accept(self, file: File | jpype.protocol.SupportsPath) -> bool: ...

class FilenameFilter:
    def accept(
        self, file: File | jpype.protocol.SupportsPath, string: java.lang.String | str
    ) -> bool: ...

class Flushable:
    def flush(self) -> None: ...

class IOError(java.lang.Error):
    def __init__(self, throwable: java.lang.Throwable): ...

class IOException(java.lang.Exception):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, throwable: java.lang.Throwable
    ): ...
    @typing.overload
    def __init__(self, throwable: java.lang.Throwable): ...

class ObjectInputFilter:
    @staticmethod
    def allowFilter(
        predicate: java.util.function.Predicate[type[typing.Any]]
        | typing.Callable[[type[typing.Any]], bool],
        status: ObjectInputFilter.Status,
    ) -> ObjectInputFilter: ...
    def checkInput(
        self, filterInfo: ObjectInputFilter.FilterInfo
    ) -> ObjectInputFilter.Status: ...
    @staticmethod
    def merge(
        objectInputFilter: ObjectInputFilter | typing.Callable,
        objectInputFilter2: ObjectInputFilter | typing.Callable,
    ) -> ObjectInputFilter: ...
    @staticmethod
    def rejectFilter(
        predicate: java.util.function.Predicate[type[typing.Any]]
        | typing.Callable[[type[typing.Any]], bool],
        status: ObjectInputFilter.Status,
    ) -> ObjectInputFilter: ...
    @staticmethod
    def rejectUndecidedClass(
        objectInputFilter: ObjectInputFilter | typing.Callable,
    ) -> ObjectInputFilter: ...
    class Config:
        @staticmethod
        def createFilter(string: java.lang.String | str) -> ObjectInputFilter: ...
        @staticmethod
        def getSerialFilter() -> ObjectInputFilter: ...
        @staticmethod
        def getSerialFilterFactory() -> java.util.function.BinaryOperator[
            ObjectInputFilter
        ]: ...
        @staticmethod
        def setSerialFilter(
            objectInputFilter: ObjectInputFilter | typing.Callable,
        ) -> None: ...
        @staticmethod
        def setSerialFilterFactory(
            binaryOperator: java.util.function.BinaryOperator[
                ObjectInputFilter | typing.Callable
            ]
            | typing.Callable,
        ) -> None: ...

    class FilterInfo:
        def arrayLength(self) -> int: ...
        def depth(self) -> int: ...
        def references(self) -> int: ...
        def serialClass(self) -> type[typing.Any]: ...
        def streamBytes(self) -> int: ...

    class Status(java.lang.Enum["ObjectInputFilter.Status"]):
        UNDECIDED: typing.ClassVar[ObjectInputFilter.Status] = ...
        ALLOWED: typing.ClassVar[ObjectInputFilter.Status] = ...
        REJECTED: typing.ClassVar[ObjectInputFilter.Status] = ...
        _valueOf_1__T = typing.TypeVar("_valueOf_1__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: java.lang.String | str) -> ObjectInputFilter.Status: ...
        @typing.overload
        @staticmethod
        def valueOf(
            class_: type[_valueOf_1__T], string: java.lang.String | str
        ) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence[ObjectInputFilter.Status]: ...

class ObjectInputValidation:
    def validateObject(self) -> None: ...

class ObjectStreamConstants:
    STREAM_MAGIC: typing.ClassVar[int] = ...
    STREAM_VERSION: typing.ClassVar[int] = ...
    TC_BASE: typing.ClassVar[int] = ...
    TC_NULL: typing.ClassVar[int] = ...
    TC_REFERENCE: typing.ClassVar[int] = ...
    TC_CLASSDESC: typing.ClassVar[int] = ...
    TC_OBJECT: typing.ClassVar[int] = ...
    TC_STRING: typing.ClassVar[int] = ...
    TC_ARRAY: typing.ClassVar[int] = ...
    TC_CLASS: typing.ClassVar[int] = ...
    TC_BLOCKDATA: typing.ClassVar[int] = ...
    TC_ENDBLOCKDATA: typing.ClassVar[int] = ...
    TC_RESET: typing.ClassVar[int] = ...
    TC_BLOCKDATALONG: typing.ClassVar[int] = ...
    TC_EXCEPTION: typing.ClassVar[int] = ...
    TC_LONGSTRING: typing.ClassVar[int] = ...
    TC_PROXYCLASSDESC: typing.ClassVar[int] = ...
    TC_ENUM: typing.ClassVar[int] = ...
    TC_MAX: typing.ClassVar[int] = ...
    baseWireHandle: typing.ClassVar[int] = ...
    SC_WRITE_METHOD: typing.ClassVar[int] = ...
    SC_BLOCK_DATA: typing.ClassVar[int] = ...
    SC_SERIALIZABLE: typing.ClassVar[int] = ...
    SC_EXTERNALIZABLE: typing.ClassVar[int] = ...
    SC_ENUM: typing.ClassVar[int] = ...
    SUBSTITUTION_PERMISSION: typing.ClassVar[SerializablePermission] = ...
    SUBCLASS_IMPLEMENTATION_PERMISSION: typing.ClassVar[SerializablePermission] = ...
    SERIAL_FILTER_PERMISSION: typing.ClassVar[SerializablePermission] = ...
    PROTOCOL_VERSION_1: typing.ClassVar[int] = ...
    PROTOCOL_VERSION_2: typing.ClassVar[int] = ...

class ObjectStreamField(java.lang.Comparable[typing.Any]):
    @typing.overload
    def __init__(self, string: java.lang.String | str, class_: type[typing.Any]): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, class_: type[typing.Any], boolean: bool
    ): ...
    def compareTo(self, object: typing.Any) -> int: ...
    def getName(self) -> java.lang.String: ...
    def getOffset(self) -> int: ...
    def getType(self) -> type[typing.Any]: ...
    def getTypeCode(self) -> str: ...
    def getTypeString(self) -> java.lang.String: ...
    def isPrimitive(self) -> bool: ...
    def isUnshared(self) -> bool: ...
    def toString(self) -> java.lang.String: ...

class Serial(java.lang.annotation.Annotation):
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> java.lang.String: ...

class Serializable: ...

class SerializablePermission(java.security.BasicPermission):
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ): ...

class StreamTokenizer:
    ttype: int = ...
    TT_EOF: typing.ClassVar[int] = ...
    TT_EOL: typing.ClassVar[int] = ...
    TT_NUMBER: typing.ClassVar[int] = ...
    TT_WORD: typing.ClassVar[int] = ...
    sval: java.lang.String = ...
    nval: float = ...
    @typing.overload
    def __init__(self, inputStream: InputStream): ...
    @typing.overload
    def __init__(self, reader: Reader): ...
    def commentChar(self, int: int) -> None: ...
    def eolIsSignificant(self, boolean: bool) -> None: ...
    def lineno(self) -> int: ...
    def lowerCaseMode(self, boolean: bool) -> None: ...
    def nextToken(self) -> int: ...
    def ordinaryChar(self, int: int) -> None: ...
    def ordinaryChars(self, int: int, int2: int) -> None: ...
    def parseNumbers(self) -> None: ...
    def pushBack(self) -> None: ...
    def quoteChar(self, int: int) -> None: ...
    def resetSyntax(self) -> None: ...
    def slashSlashComments(self, boolean: bool) -> None: ...
    def slashStarComments(self, boolean: bool) -> None: ...
    def toString(self) -> java.lang.String: ...
    def whitespaceChars(self, int: int, int2: int) -> None: ...
    def wordChars(self, int: int, int2: int) -> None: ...

class UncheckedIOException(java.lang.RuntimeException):
    @typing.overload
    def __init__(self, iOException: IOException): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str, iOException: IOException): ...
    def getCause(self) -> IOException: ...

class CharConversionException(IOException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...

class Console(Flushable):
    def charset(self) -> java.nio.charset.Charset: ...
    def flush(self) -> None: ...
    @typing.overload
    def format(
        self, string: java.lang.String | str, *object: typing.Any
    ) -> Console: ...
    @typing.overload
    def format(
        self,
        locale: java.util.Locale,
        string: java.lang.String | str,
        *object: typing.Any,
    ) -> Console: ...
    def isTerminal(self) -> bool: ...
    @typing.overload
    def printf(
        self, string: java.lang.String | str, *object: typing.Any
    ) -> Console: ...
    @typing.overload
    def printf(
        self,
        locale: java.util.Locale,
        string: java.lang.String | str,
        *object: typing.Any,
    ) -> Console: ...
    @typing.overload
    def readLine(self) -> java.lang.String: ...
    @typing.overload
    def readLine(
        self, string: java.lang.String | str, *object: typing.Any
    ) -> java.lang.String: ...
    @typing.overload
    def readLine(
        self,
        locale: java.util.Locale,
        string: java.lang.String | str,
        *object: typing.Any,
    ) -> java.lang.String: ...
    @typing.overload
    def readPassword(self) -> typing.MutableSequence[str]: ...
    @typing.overload
    def readPassword(
        self, string: java.lang.String | str, *object: typing.Any
    ) -> typing.MutableSequence[str]: ...
    @typing.overload
    def readPassword(
        self,
        locale: java.util.Locale,
        string: java.lang.String | str,
        *object: typing.Any,
    ) -> typing.MutableSequence[str]: ...
    def reader(self) -> Reader: ...
    def writer(self) -> PrintWriter: ...

class EOFException(IOException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...

class Externalizable(Serializable):
    def readExternal(self, objectInput: ObjectInput) -> None: ...
    def writeExternal(self, objectOutput: ObjectOutput) -> None: ...

class File(Serializable, java.lang.Comparable["File"]):
    separatorChar: typing.ClassVar[str] = ...
    separator: typing.ClassVar[java.lang.String] = ...
    pathSeparatorChar: typing.ClassVar[str] = ...
    pathSeparator: typing.ClassVar[java.lang.String] = ...
    @typing.overload
    def __init__(
        self, file: File | jpype.protocol.SupportsPath, string: java.lang.String | str
    ): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ): ...
    @typing.overload
    def __init__(self, uRI: java.net.URI): ...
    def canExecute(self) -> bool: ...
    def canRead(self) -> bool: ...
    def canWrite(self) -> bool: ...
    def compareTo(self, file: File | jpype.protocol.SupportsPath) -> int: ...
    def createNewFile(self) -> bool: ...
    @typing.overload
    @staticmethod
    def createTempFile(
        string: java.lang.String | str, string2: java.lang.String | str
    ) -> File: ...
    @typing.overload
    @staticmethod
    def createTempFile(
        string: java.lang.String | str,
        string2: java.lang.String | str,
        file: File | jpype.protocol.SupportsPath,
    ) -> File: ...
    def delete(self) -> bool: ...
    def deleteOnExit(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def exists(self) -> bool: ...
    def getAbsoluteFile(self) -> File: ...
    def getAbsolutePath(self) -> java.lang.String: ...
    def getCanonicalFile(self) -> File: ...
    def getCanonicalPath(self) -> java.lang.String: ...
    def getFreeSpace(self) -> int: ...
    def getName(self) -> java.lang.String: ...
    def getParent(self) -> java.lang.String: ...
    def getParentFile(self) -> File: ...
    def getPath(self) -> java.lang.String: ...
    def getTotalSpace(self) -> int: ...
    def getUsableSpace(self) -> int: ...
    def hashCode(self) -> int: ...
    def isAbsolute(self) -> bool: ...
    def isDirectory(self) -> bool: ...
    def isFile(self) -> bool: ...
    def isHidden(self) -> bool: ...
    def lastModified(self) -> int: ...
    def length(self) -> int: ...
    @typing.overload
    def list(self) -> typing.MutableSequence[java.lang.String]: ...
    @typing.overload
    def list(
        self, filenameFilter: FilenameFilter | typing.Callable
    ) -> typing.MutableSequence[java.lang.String]: ...
    @typing.overload
    def listFiles(self) -> typing.MutableSequence[File]: ...
    @typing.overload
    def listFiles(
        self, fileFilter: FileFilter | typing.Callable
    ) -> typing.MutableSequence[File]: ...
    @typing.overload
    def listFiles(
        self, filenameFilter: FilenameFilter | typing.Callable
    ) -> typing.MutableSequence[File]: ...
    @staticmethod
    def listRoots() -> typing.MutableSequence[File]: ...
    def mkdir(self) -> bool: ...
    def mkdirs(self) -> bool: ...
    def renameTo(self, file: File | jpype.protocol.SupportsPath) -> bool: ...
    @typing.overload
    def setExecutable(self, boolean: bool) -> bool: ...
    @typing.overload
    def setExecutable(self, boolean: bool, boolean2: bool) -> bool: ...
    def setLastModified(self, long: int) -> bool: ...
    def setReadOnly(self) -> bool: ...
    @typing.overload
    def setReadable(self, boolean: bool) -> bool: ...
    @typing.overload
    def setReadable(self, boolean: bool, boolean2: bool) -> bool: ...
    @typing.overload
    def setWritable(self, boolean: bool) -> bool: ...
    @typing.overload
    def setWritable(self, boolean: bool, boolean2: bool) -> bool: ...
    def toPath(self) -> java.nio.file.Path: ...
    def toString(self) -> java.lang.String: ...
    def toURI(self) -> java.net.URI: ...
    def toURL(self) -> java.net.URL: ...

class FileNotFoundException(IOException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...

class FilePermission(java.security.Permission, Serializable):
    def __init__(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getActions(self) -> java.lang.String: ...
    def hashCode(self) -> int: ...
    def implies(self, permission: java.security.Permission) -> bool: ...
    def newPermissionCollection(self) -> java.security.PermissionCollection: ...

class InputStream(Closeable):
    def __init__(self): ...
    def available(self) -> int: ...
    def close(self) -> None: ...
    def mark(self, int: int) -> None: ...
    def markSupported(self) -> bool: ...
    @staticmethod
    def nullInputStream() -> InputStream: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def readAllBytes(self) -> typing.MutableSequence[int]: ...
    @typing.overload
    def readNBytes(self, int: int) -> typing.MutableSequence[int]: ...
    @typing.overload
    def readNBytes(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...
    def skipNBytes(self, long: int) -> None: ...
    def transferTo(self, outputStream: OutputStream) -> int: ...

class InterruptedIOException(IOException):
    bytesTransferred: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...

class ObjectInput(DataInput, java.lang.AutoCloseable):
    def available(self) -> int: ...
    def close(self) -> None: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def readObject(self) -> typing.Any: ...
    def skip(self, long: int) -> int: ...

class ObjectOutput(DataOutput, java.lang.AutoCloseable):
    def close(self) -> None: ...
    def flush(self) -> None: ...
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    def writeObject(self, object: typing.Any) -> None: ...

class ObjectStreamClass(Serializable):
    NO_FIELDS: typing.ClassVar[typing.MutableSequence[ObjectStreamField]] = ...
    def forClass(self) -> type[typing.Any]: ...
    def getField(self, string: java.lang.String | str) -> ObjectStreamField: ...
    def getFields(self) -> typing.MutableSequence[ObjectStreamField]: ...
    def getName(self) -> java.lang.String: ...
    def getSerialVersionUID(self) -> int: ...
    @staticmethod
    def lookup(class_: type[typing.Any]) -> ObjectStreamClass: ...
    @staticmethod
    def lookupAny(class_: type[typing.Any]) -> ObjectStreamClass: ...
    def toString(self) -> java.lang.String: ...

class ObjectStreamException(IOException): ...

class OutputStream(Closeable, Flushable):
    def __init__(self): ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    @staticmethod
    def nullOutputStream() -> OutputStream: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...

class RandomAccessFile(DataOutput, DataInput, Closeable):
    @typing.overload
    def __init__(
        self, file: File | jpype.protocol.SupportsPath, string: java.lang.String | str
    ): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ): ...
    def close(self) -> None: ...
    def getChannel(self) -> java.nio.channels.FileChannel: ...
    def getFD(self) -> FileDescriptor: ...
    def getFilePointer(self) -> int: ...
    def length(self) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def readBoolean(self) -> bool: ...
    def readByte(self) -> int: ...
    def readChar(self) -> str: ...
    def readDouble(self) -> float: ...
    def readFloat(self) -> float: ...
    @typing.overload
    def readFully(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def readFully(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    def readInt(self) -> int: ...
    def readLine(self) -> java.lang.String: ...
    def readLong(self) -> int: ...
    def readShort(self) -> int: ...
    def readUTF(self) -> java.lang.String: ...
    def readUnsignedByte(self) -> int: ...
    def readUnsignedShort(self) -> int: ...
    def seek(self, long: int) -> None: ...
    def setLength(self, long: int) -> None: ...
    def skipBytes(self, int: int) -> int: ...
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    def writeBoolean(self, boolean: bool) -> None: ...
    def writeByte(self, int: int) -> None: ...
    def writeBytes(self, string: java.lang.String | str) -> None: ...
    def writeChar(self, int: int) -> None: ...
    def writeChars(self, string: java.lang.String | str) -> None: ...
    def writeDouble(self, double: float) -> None: ...
    def writeFloat(self, float: float) -> None: ...
    def writeInt(self, int: int) -> None: ...
    def writeLong(self, long: int) -> None: ...
    def writeShort(self, int: int) -> None: ...
    def writeUTF(self, string: java.lang.String | str) -> None: ...

class Reader(java.lang.Readable, Closeable):
    def close(self) -> None: ...
    def mark(self, int: int) -> None: ...
    def markSupported(self) -> bool: ...
    @staticmethod
    def nullReader() -> Reader: ...
    @staticmethod
    def of(charSequence: java.lang.CharSequence | str) -> Reader: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray, int: int, int2: int) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray) -> int: ...
    @typing.overload
    def read(self, charBuffer: java.nio.CharBuffer) -> int: ...
    def readAllAsString(self) -> java.lang.String: ...
    def readAllLines(self) -> java.util.List[java.lang.String]: ...
    def ready(self) -> bool: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...
    def transferTo(self, writer: Writer) -> int: ...

class SyncFailedException(IOException):
    def __init__(self, string: java.lang.String | str): ...

class UTFDataFormatException(IOException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...

class UnsupportedEncodingException(IOException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...

class Writer(java.lang.Appendable, Closeable, Flushable):
    @typing.overload
    def append(self, char: str) -> Writer: ...
    @typing.overload
    def append(self, charSequence: java.lang.CharSequence | str) -> Writer: ...
    @typing.overload
    def append(
        self, charSequence: java.lang.CharSequence | str, int: int, int2: int
    ) -> Writer: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    @staticmethod
    def nullWriter() -> Writer: ...
    @typing.overload
    def write(
        self, charArray: list[str] | jpype.JArray, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, charArray: list[str] | jpype.JArray) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str, int: int, int2: int) -> None: ...

class BufferedReader(Reader):
    @typing.overload
    def __init__(self, reader: Reader): ...
    @typing.overload
    def __init__(self, reader: Reader, int: int): ...
    def close(self) -> None: ...
    def lines(self) -> java.util.stream.Stream[java.lang.String]: ...
    def mark(self, int: int) -> None: ...
    def markSupported(self) -> bool: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray, int: int, int2: int) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray) -> int: ...
    @typing.overload
    def read(self, charBuffer: java.nio.CharBuffer) -> int: ...
    def readLine(self) -> java.lang.String: ...
    def ready(self) -> bool: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...

class BufferedWriter(Writer):
    @typing.overload
    def __init__(self, writer: Writer): ...
    @typing.overload
    def __init__(self, writer: Writer, int: int): ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def newLine(self) -> None: ...
    @typing.overload
    def write(
        self, charArray: list[str] | jpype.JArray, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str, int: int, int2: int) -> None: ...
    @typing.overload
    def write(self, charArray: list[str] | jpype.JArray) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str) -> None: ...

class ByteArrayInputStream(InputStream):
    @typing.overload
    def __init__(self, byteArray: list[int] | jpype.JArray | bytes): ...
    @typing.overload
    def __init__(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ): ...
    def available(self) -> int: ...
    def close(self) -> None: ...
    def mark(self, int: int) -> None: ...
    def markSupported(self) -> bool: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def readAllBytes(self) -> typing.MutableSequence[int]: ...
    @typing.overload
    def readNBytes(self, int: int) -> typing.MutableSequence[int]: ...
    @typing.overload
    def readNBytes(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...
    def transferTo(self, outputStream: OutputStream) -> int: ...

class ByteArrayOutputStream(OutputStream):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    def close(self) -> None: ...
    def reset(self) -> None: ...
    def size(self) -> int: ...
    def toByteArray(self) -> typing.MutableSequence[int]: ...
    @typing.overload
    def toString(self) -> java.lang.String: ...
    @typing.overload
    def toString(self, int: int) -> java.lang.String: ...
    @typing.overload
    def toString(self, string: java.lang.String | str) -> java.lang.String: ...
    @typing.overload
    def toString(self, charset: java.nio.charset.Charset) -> java.lang.String: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    def writeBytes(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    def writeTo(self, outputStream: OutputStream) -> None: ...

class CharArrayReader(Reader):
    @typing.overload
    def __init__(self, charArray: list[str] | jpype.JArray): ...
    @typing.overload
    def __init__(self, charArray: list[str] | jpype.JArray, int: int, int2: int): ...
    def close(self) -> None: ...
    def mark(self, int: int) -> None: ...
    def markSupported(self) -> bool: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray, int: int, int2: int) -> int: ...
    @typing.overload
    def read(self, charBuffer: java.nio.CharBuffer) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray) -> int: ...
    def ready(self) -> bool: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...

class CharArrayWriter(Writer):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def append(self, char: str) -> CharArrayWriter: ...
    @typing.overload
    def append(self, charSequence: java.lang.CharSequence | str) -> CharArrayWriter: ...
    @typing.overload
    def append(
        self, charSequence: java.lang.CharSequence | str, int: int, int2: int
    ) -> CharArrayWriter: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def reset(self) -> None: ...
    def size(self) -> int: ...
    def toCharArray(self) -> typing.MutableSequence[str]: ...
    def toString(self) -> java.lang.String: ...
    @typing.overload
    def write(
        self, charArray: list[str] | jpype.JArray, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str, int: int, int2: int) -> None: ...
    @typing.overload
    def write(self, charArray: list[str] | jpype.JArray) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str) -> None: ...
    def writeTo(self, writer: Writer) -> None: ...

class FileInputStream(InputStream):
    @typing.overload
    def __init__(self, file: File | jpype.protocol.SupportsPath): ...
    @typing.overload
    def __init__(self, fileDescriptor: FileDescriptor): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    def available(self) -> int: ...
    def close(self) -> None: ...
    def getChannel(self) -> java.nio.channels.FileChannel: ...
    def getFD(self) -> FileDescriptor: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def readAllBytes(self) -> typing.MutableSequence[int]: ...
    @typing.overload
    def readNBytes(self, int: int) -> typing.MutableSequence[int]: ...
    @typing.overload
    def readNBytes(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def skip(self, long: int) -> int: ...
    def transferTo(self, outputStream: OutputStream) -> int: ...

class FileOutputStream(OutputStream):
    @typing.overload
    def __init__(self, file: File | jpype.protocol.SupportsPath): ...
    @typing.overload
    def __init__(self, file: File | jpype.protocol.SupportsPath, boolean: bool): ...
    @typing.overload
    def __init__(self, fileDescriptor: FileDescriptor): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str, boolean: bool): ...
    def close(self) -> None: ...
    def getChannel(self) -> java.nio.channels.FileChannel: ...
    def getFD(self) -> FileDescriptor: ...
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...

class FilterInputStream(InputStream):
    def available(self) -> int: ...
    def close(self) -> None: ...
    def mark(self, int: int) -> None: ...
    def markSupported(self) -> bool: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...

class FilterOutputStream(OutputStream):
    def __init__(self, outputStream: OutputStream): ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...

class FilterReader(Reader):
    def close(self) -> None: ...
    def mark(self, int: int) -> None: ...
    def markSupported(self) -> bool: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray, int: int, int2: int) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray) -> int: ...
    @typing.overload
    def read(self, charBuffer: java.nio.CharBuffer) -> int: ...
    def ready(self) -> bool: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...

class FilterWriter(Writer):
    def close(self) -> None: ...
    def flush(self) -> None: ...
    @typing.overload
    def write(
        self, charArray: list[str] | jpype.JArray, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str, int: int, int2: int) -> None: ...
    @typing.overload
    def write(self, charArray: list[str] | jpype.JArray) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str) -> None: ...

class InputStreamReader(Reader):
    @typing.overload
    def __init__(self, inputStream: InputStream): ...
    @typing.overload
    def __init__(self, inputStream: InputStream, string: java.lang.String | str): ...
    @typing.overload
    def __init__(self, inputStream: InputStream, charset: java.nio.charset.Charset): ...
    @typing.overload
    def __init__(
        self, inputStream: InputStream, charsetDecoder: java.nio.charset.CharsetDecoder
    ): ...
    def close(self) -> None: ...
    def getEncoding(self) -> java.lang.String: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray, int: int, int2: int) -> int: ...
    @typing.overload
    def read(self, charBuffer: java.nio.CharBuffer) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray) -> int: ...
    def ready(self) -> bool: ...

class InvalidClassException(ObjectStreamException):
    classname: java.lang.String = ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ): ...
    @typing.overload
    def __init__(
        self,
        string: java.lang.String | str,
        string2: java.lang.String | str,
        throwable: java.lang.Throwable,
    ): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, throwable: java.lang.Throwable
    ): ...
    def getMessage(self) -> java.lang.String: ...

class InvalidObjectException(ObjectStreamException):
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, throwable: java.lang.Throwable
    ): ...

class NotActiveException(ObjectStreamException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...

class NotSerializableException(ObjectStreamException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...

class ObjectInputStream(InputStream, ObjectInput, ObjectStreamConstants):
    def __init__(self, inputStream: InputStream): ...
    def available(self) -> int: ...
    def close(self) -> None: ...
    def defaultReadObject(self) -> None: ...
    def getObjectInputFilter(self) -> ObjectInputFilter: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def readBoolean(self) -> bool: ...
    def readByte(self) -> int: ...
    def readChar(self) -> str: ...
    def readDouble(self) -> float: ...
    def readFields(self) -> ObjectInputStream.GetField: ...
    def readFloat(self) -> float: ...
    @typing.overload
    def readFully(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def readFully(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    def readInt(self) -> int: ...
    def readLine(self) -> java.lang.String: ...
    def readLong(self) -> int: ...
    def readObject(self) -> typing.Any: ...
    def readShort(self) -> int: ...
    def readUTF(self) -> java.lang.String: ...
    def readUnshared(self) -> typing.Any: ...
    def readUnsignedByte(self) -> int: ...
    def readUnsignedShort(self) -> int: ...
    def registerValidation(
        self, objectInputValidation: ObjectInputValidation | typing.Callable, int: int
    ) -> None: ...
    def setObjectInputFilter(
        self, objectInputFilter: ObjectInputFilter | typing.Callable
    ) -> None: ...
    def skipBytes(self, int: int) -> int: ...
    class GetField:
        def __init__(self): ...
        def defaulted(self, string: java.lang.String | str) -> bool: ...
        @typing.overload
        def get(self, string: java.lang.String | str, boolean: bool) -> bool: ...
        @typing.overload
        def get(self, string: java.lang.String | str, byte: int) -> int: ...
        @typing.overload
        def get(self, string: java.lang.String | str, char: str) -> str: ...
        @typing.overload
        def get(self, string: java.lang.String | str, double: float) -> float: ...
        @typing.overload
        def get(self, string: java.lang.String | str, float: float) -> float: ...
        @typing.overload
        def get(self, string: java.lang.String | str, int: int) -> int: ...
        @typing.overload
        def get(
            self, string: java.lang.String | str, object: typing.Any
        ) -> typing.Any: ...
        @typing.overload
        def get(self, string: java.lang.String | str, long: int) -> int: ...
        @typing.overload
        def get(self, string: java.lang.String | str, short: int) -> int: ...
        def getObjectStreamClass(self) -> ObjectStreamClass: ...

class ObjectOutputStream(OutputStream, ObjectOutput, ObjectStreamConstants):
    def __init__(self, outputStream: OutputStream): ...
    def close(self) -> None: ...
    def defaultWriteObject(self) -> None: ...
    def flush(self) -> None: ...
    def putFields(self) -> ObjectOutputStream.PutField: ...
    def reset(self) -> None: ...
    def useProtocolVersion(self, int: int) -> None: ...
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    def writeBoolean(self, boolean: bool) -> None: ...
    def writeByte(self, int: int) -> None: ...
    def writeBytes(self, string: java.lang.String | str) -> None: ...
    def writeChar(self, int: int) -> None: ...
    def writeChars(self, string: java.lang.String | str) -> None: ...
    def writeDouble(self, double: float) -> None: ...
    def writeFields(self) -> None: ...
    def writeFloat(self, float: float) -> None: ...
    def writeInt(self, int: int) -> None: ...
    def writeLong(self, long: int) -> None: ...
    def writeObject(self, object: typing.Any) -> None: ...
    def writeShort(self, int: int) -> None: ...
    def writeUTF(self, string: java.lang.String | str) -> None: ...
    def writeUnshared(self, object: typing.Any) -> None: ...
    class PutField:
        def __init__(self): ...
        @typing.overload
        def put(self, string: java.lang.String | str, boolean: bool) -> None: ...
        @typing.overload
        def put(self, string: java.lang.String | str, byte: int) -> None: ...
        @typing.overload
        def put(self, string: java.lang.String | str, char: str) -> None: ...
        @typing.overload
        def put(self, string: java.lang.String | str, double: float) -> None: ...
        @typing.overload
        def put(self, string: java.lang.String | str, float: float) -> None: ...
        @typing.overload
        def put(self, string: java.lang.String | str, int: int) -> None: ...
        @typing.overload
        def put(self, string: java.lang.String | str, object: typing.Any) -> None: ...
        @typing.overload
        def put(self, string: java.lang.String | str, long: int) -> None: ...
        @typing.overload
        def put(self, string: java.lang.String | str, short: int) -> None: ...
        def write(self, objectOutput: ObjectOutput) -> None: ...

class OptionalDataException(ObjectStreamException):
    length: int = ...
    eof: bool = ...

class OutputStreamWriter(Writer):
    @typing.overload
    def __init__(self, outputStream: OutputStream): ...
    @typing.overload
    def __init__(self, outputStream: OutputStream, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, outputStream: OutputStream, charset: java.nio.charset.Charset
    ): ...
    @typing.overload
    def __init__(
        self,
        outputStream: OutputStream,
        charsetEncoder: java.nio.charset.CharsetEncoder,
    ): ...
    @typing.overload
    def append(self, charSequence: java.lang.CharSequence | str) -> Writer: ...
    @typing.overload
    def append(
        self, charSequence: java.lang.CharSequence | str, int: int, int2: int
    ) -> Writer: ...
    @typing.overload
    def append(self, char: str) -> Writer: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def getEncoding(self) -> java.lang.String: ...
    @typing.overload
    def write(
        self, charArray: list[str] | jpype.JArray, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str, int: int, int2: int) -> None: ...
    @typing.overload
    def write(self, charArray: list[str] | jpype.JArray) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str) -> None: ...

class PipedInputStream(InputStream):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, pipedOutputStream: PipedOutputStream): ...
    @typing.overload
    def __init__(self, pipedOutputStream: PipedOutputStream, int: int): ...
    def available(self) -> int: ...
    def close(self) -> None: ...
    def connect(self, pipedOutputStream: PipedOutputStream) -> None: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...

class PipedOutputStream(OutputStream):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, pipedInputStream: PipedInputStream): ...
    def close(self) -> None: ...
    def connect(self, pipedInputStream: PipedInputStream) -> None: ...
    def flush(self) -> None: ...
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...

class PipedReader(Reader):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, pipedWriter: PipedWriter): ...
    @typing.overload
    def __init__(self, pipedWriter: PipedWriter, int: int): ...
    def close(self) -> None: ...
    def connect(self, pipedWriter: PipedWriter) -> None: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray) -> int: ...
    @typing.overload
    def read(self, charBuffer: java.nio.CharBuffer) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray, int: int, int2: int) -> int: ...
    def ready(self) -> bool: ...

class PipedWriter(Writer):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, pipedReader: PipedReader): ...
    def close(self) -> None: ...
    def connect(self, pipedReader: PipedReader) -> None: ...
    def flush(self) -> None: ...
    @typing.overload
    def write(
        self, charArray: list[str] | jpype.JArray, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    @typing.overload
    def write(self, charArray: list[str] | jpype.JArray) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str, int: int, int2: int) -> None: ...

class PrintWriter(Writer):
    @typing.overload
    def __init__(self, file: File | jpype.protocol.SupportsPath): ...
    @typing.overload
    def __init__(
        self, file: File | jpype.protocol.SupportsPath, string: java.lang.String | str
    ): ...
    @typing.overload
    def __init__(
        self,
        file: File | jpype.protocol.SupportsPath,
        charset: java.nio.charset.Charset,
    ): ...
    @typing.overload
    def __init__(self, outputStream: OutputStream): ...
    @typing.overload
    def __init__(self, outputStream: OutputStream, boolean: bool): ...
    @typing.overload
    def __init__(
        self,
        outputStream: OutputStream,
        boolean: bool,
        charset: java.nio.charset.Charset,
    ): ...
    @typing.overload
    def __init__(self, writer: Writer): ...
    @typing.overload
    def __init__(self, writer: Writer, boolean: bool): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, charset: java.nio.charset.Charset
    ): ...
    @typing.overload
    def append(self, char: str) -> PrintWriter: ...
    @typing.overload
    def append(self, charSequence: java.lang.CharSequence | str) -> PrintWriter: ...
    @typing.overload
    def append(
        self, charSequence: java.lang.CharSequence | str, int: int, int2: int
    ) -> PrintWriter: ...
    def checkError(self) -> bool: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    @typing.overload
    def format(
        self, string: java.lang.String | str, *object: typing.Any
    ) -> PrintWriter: ...
    @typing.overload
    def format(
        self,
        locale: java.util.Locale,
        string: java.lang.String | str,
        *object: typing.Any,
    ) -> PrintWriter: ...
    @typing.overload
    def print_(self, boolean: bool) -> None: ...
    @typing.overload
    def print_(self, char: str) -> None: ...
    @typing.overload
    def print_(self, charArray: list[str] | jpype.JArray) -> None: ...
    @typing.overload
    def print_(self, double: float) -> None: ...
    @typing.overload
    def print_(self, float: float) -> None: ...
    @typing.overload
    def print_(self, int: int) -> None: ...
    @typing.overload
    def print_(self, object: typing.Any) -> None: ...
    @typing.overload
    def print_(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def print_(self, long: int) -> None: ...
    @typing.overload
    def printf(
        self, string: java.lang.String | str, *object: typing.Any
    ) -> PrintWriter: ...
    @typing.overload
    def printf(
        self,
        locale: java.util.Locale,
        string: java.lang.String | str,
        *object: typing.Any,
    ) -> PrintWriter: ...
    @typing.overload
    def println(self) -> None: ...
    @typing.overload
    def println(self, boolean: bool) -> None: ...
    @typing.overload
    def println(self, char: str) -> None: ...
    @typing.overload
    def println(self, charArray: list[str] | jpype.JArray) -> None: ...
    @typing.overload
    def println(self, double: float) -> None: ...
    @typing.overload
    def println(self, float: float) -> None: ...
    @typing.overload
    def println(self, int: int) -> None: ...
    @typing.overload
    def println(self, object: typing.Any) -> None: ...
    @typing.overload
    def println(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def println(self, long: int) -> None: ...
    @typing.overload
    def write(self, charArray: list[str] | jpype.JArray) -> None: ...
    @typing.overload
    def write(
        self, charArray: list[str] | jpype.JArray, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str, int: int, int2: int) -> None: ...

class SequenceInputStream(InputStream):
    @typing.overload
    def __init__(self, inputStream: InputStream, inputStream2: InputStream): ...
    @typing.overload
    def __init__(self, enumeration: java.util.Enumeration[InputStream]): ...
    def available(self) -> int: ...
    def close(self) -> None: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def transferTo(self, outputStream: OutputStream) -> int: ...

class StreamCorruptedException(ObjectStreamException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...

class StringBufferInputStream(InputStream):
    def __init__(self, string: java.lang.String | str): ...
    def available(self) -> int: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...

class StringReader(Reader):
    def __init__(self, string: java.lang.String | str): ...
    def close(self) -> None: ...
    def mark(self, int: int) -> None: ...
    def markSupported(self) -> bool: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray) -> int: ...
    @typing.overload
    def read(self, charBuffer: java.nio.CharBuffer) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray, int: int, int2: int) -> int: ...
    def ready(self) -> bool: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...

class StringWriter(Writer):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def append(self, char: str) -> StringWriter: ...
    @typing.overload
    def append(self, charSequence: java.lang.CharSequence | str) -> StringWriter: ...
    @typing.overload
    def append(
        self, charSequence: java.lang.CharSequence | str, int: int, int2: int
    ) -> StringWriter: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def getBuffer(self) -> java.lang.StringBuffer: ...
    def toString(self) -> java.lang.String: ...
    @typing.overload
    def write(
        self, charArray: list[str] | jpype.JArray, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def write(self, string: java.lang.String | str, int: int, int2: int) -> None: ...
    @typing.overload
    def write(self, charArray: list[str] | jpype.JArray) -> None: ...

class WriteAbortedException(ObjectStreamException):
    detail: java.lang.Exception = ...
    def __init__(
        self, string: java.lang.String | str, exception: java.lang.Exception
    ): ...
    def getCause(self) -> java.lang.Throwable: ...
    def getMessage(self) -> java.lang.String: ...

class BufferedInputStream(FilterInputStream):
    @typing.overload
    def __init__(self, inputStream: InputStream): ...
    @typing.overload
    def __init__(self, inputStream: InputStream, int: int): ...
    def available(self) -> int: ...
    def close(self) -> None: ...
    def mark(self, int: int) -> None: ...
    def markSupported(self) -> bool: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...
    def transferTo(self, outputStream: OutputStream) -> int: ...

class BufferedOutputStream(FilterOutputStream):
    @typing.overload
    def __init__(self, outputStream: OutputStream): ...
    @typing.overload
    def __init__(self, outputStream: OutputStream, int: int): ...
    def flush(self) -> None: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...

class DataInputStream(FilterInputStream, DataInput):
    def __init__(self, inputStream: InputStream): ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    def readBoolean(self) -> bool: ...
    def readByte(self) -> int: ...
    def readChar(self) -> str: ...
    def readDouble(self) -> float: ...
    def readFloat(self) -> float: ...
    @typing.overload
    def readFully(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def readFully(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    def readInt(self) -> int: ...
    def readLine(self) -> java.lang.String: ...
    def readLong(self) -> int: ...
    def readShort(self) -> int: ...
    @typing.overload
    def readUTF(self) -> java.lang.String: ...
    @typing.overload
    @staticmethod
    def readUTF(dataInput: DataInput) -> java.lang.String: ...
    def readUnsignedByte(self) -> int: ...
    def readUnsignedShort(self) -> int: ...
    def skipBytes(self, int: int) -> int: ...

class DataOutputStream(FilterOutputStream, DataOutput):
    def __init__(self, outputStream: OutputStream): ...
    def flush(self) -> None: ...
    def size(self) -> int: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    def writeBoolean(self, boolean: bool) -> None: ...
    def writeByte(self, int: int) -> None: ...
    def writeBytes(self, string: java.lang.String | str) -> None: ...
    def writeChar(self, int: int) -> None: ...
    def writeChars(self, string: java.lang.String | str) -> None: ...
    def writeDouble(self, double: float) -> None: ...
    def writeFloat(self, float: float) -> None: ...
    def writeInt(self, int: int) -> None: ...
    def writeLong(self, long: int) -> None: ...
    def writeShort(self, int: int) -> None: ...
    def writeUTF(self, string: java.lang.String | str) -> None: ...

class FileReader(InputStreamReader):
    @typing.overload
    def __init__(self, file: File | jpype.protocol.SupportsPath): ...
    @typing.overload
    def __init__(
        self,
        file: File | jpype.protocol.SupportsPath,
        charset: java.nio.charset.Charset,
    ): ...
    @typing.overload
    def __init__(self, fileDescriptor: FileDescriptor): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, charset: java.nio.charset.Charset
    ): ...

class FileWriter(OutputStreamWriter):
    @typing.overload
    def __init__(self, file: File | jpype.protocol.SupportsPath): ...
    @typing.overload
    def __init__(self, file: File | jpype.protocol.SupportsPath, boolean: bool): ...
    @typing.overload
    def __init__(
        self,
        file: File | jpype.protocol.SupportsPath,
        charset: java.nio.charset.Charset,
    ): ...
    @typing.overload
    def __init__(
        self,
        file: File | jpype.protocol.SupportsPath,
        charset: java.nio.charset.Charset,
        boolean: bool,
    ): ...
    @typing.overload
    def __init__(self, fileDescriptor: FileDescriptor): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str, boolean: bool): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, charset: java.nio.charset.Charset
    ): ...
    @typing.overload
    def __init__(
        self,
        string: java.lang.String | str,
        charset: java.nio.charset.Charset,
        boolean: bool,
    ): ...

class LineNumberInputStream(FilterInputStream):
    def __init__(self, inputStream: InputStream): ...
    def available(self) -> int: ...
    def getLineNumber(self) -> int: ...
    def mark(self, int: int) -> None: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def reset(self) -> None: ...
    def setLineNumber(self, int: int) -> None: ...
    def skip(self, long: int) -> int: ...

class LineNumberReader(BufferedReader):
    @typing.overload
    def __init__(self, reader: Reader): ...
    @typing.overload
    def __init__(self, reader: Reader, int: int): ...
    def getLineNumber(self) -> int: ...
    def mark(self, int: int) -> None: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray, int: int, int2: int) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray) -> int: ...
    @typing.overload
    def read(self, charBuffer: java.nio.CharBuffer) -> int: ...
    def readLine(self) -> java.lang.String: ...
    def reset(self) -> None: ...
    def setLineNumber(self, int: int) -> None: ...
    def skip(self, long: int) -> int: ...

class PrintStream(FilterOutputStream, java.lang.Appendable, Closeable):
    @typing.overload
    def __init__(self, file: File | jpype.protocol.SupportsPath): ...
    @typing.overload
    def __init__(
        self, file: File | jpype.protocol.SupportsPath, string: java.lang.String | str
    ): ...
    @typing.overload
    def __init__(
        self,
        file: File | jpype.protocol.SupportsPath,
        charset: java.nio.charset.Charset,
    ): ...
    @typing.overload
    def __init__(self, outputStream: OutputStream): ...
    @typing.overload
    def __init__(self, outputStream: OutputStream, boolean: bool): ...
    @typing.overload
    def __init__(
        self, outputStream: OutputStream, boolean: bool, string: java.lang.String | str
    ): ...
    @typing.overload
    def __init__(
        self,
        outputStream: OutputStream,
        boolean: bool,
        charset: java.nio.charset.Charset,
    ): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, charset: java.nio.charset.Charset
    ): ...
    @typing.overload
    def append(self, char: str) -> PrintStream: ...
    @typing.overload
    def append(self, charSequence: java.lang.CharSequence | str) -> PrintStream: ...
    @typing.overload
    def append(
        self, charSequence: java.lang.CharSequence | str, int: int, int2: int
    ) -> PrintStream: ...
    def charset(self) -> java.nio.charset.Charset: ...
    def checkError(self) -> bool: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    @typing.overload
    def format(
        self, string: java.lang.String | str, *object: typing.Any
    ) -> PrintStream: ...
    @typing.overload
    def format(
        self,
        locale: java.util.Locale,
        string: java.lang.String | str,
        *object: typing.Any,
    ) -> PrintStream: ...
    @typing.overload
    def print_(self, boolean: bool) -> None: ...
    @typing.overload
    def print_(self, char: str) -> None: ...
    @typing.overload
    def print_(self, charArray: list[str] | jpype.JArray) -> None: ...
    @typing.overload
    def print_(self, double: float) -> None: ...
    @typing.overload
    def print_(self, float: float) -> None: ...
    @typing.overload
    def print_(self, int: int) -> None: ...
    @typing.overload
    def print_(self, object: typing.Any) -> None: ...
    @typing.overload
    def print_(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def print_(self, long: int) -> None: ...
    @typing.overload
    def printf(
        self, string: java.lang.String | str, *object: typing.Any
    ) -> PrintStream: ...
    @typing.overload
    def printf(
        self,
        locale: java.util.Locale,
        string: java.lang.String | str,
        *object: typing.Any,
    ) -> PrintStream: ...
    @typing.overload
    def println(self) -> None: ...
    @typing.overload
    def println(self, boolean: bool) -> None: ...
    @typing.overload
    def println(self, char: str) -> None: ...
    @typing.overload
    def println(self, charArray: list[str] | jpype.JArray) -> None: ...
    @typing.overload
    def println(self, double: float) -> None: ...
    @typing.overload
    def println(self, float: float) -> None: ...
    @typing.overload
    def println(self, int: int) -> None: ...
    @typing.overload
    def println(self, object: typing.Any) -> None: ...
    @typing.overload
    def println(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def println(self, long: int) -> None: ...
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...
    def writeBytes(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...

class PushbackInputStream(FilterInputStream):
    @typing.overload
    def __init__(self, inputStream: InputStream): ...
    @typing.overload
    def __init__(self, inputStream: InputStream, int: int): ...
    def available(self) -> int: ...
    def close(self) -> None: ...
    def mark(self, int: int) -> None: ...
    def markSupported(self) -> bool: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...
    def transferTo(self, outputStream: OutputStream) -> int: ...
    @typing.overload
    def unread(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def unread(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def unread(self, int: int) -> None: ...

class PushbackReader(FilterReader):
    @typing.overload
    def __init__(self, reader: Reader): ...
    @typing.overload
    def __init__(self, reader: Reader, int: int): ...
    def close(self) -> None: ...
    def mark(self, int: int) -> None: ...
    def markSupported(self) -> bool: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray, int: int, int2: int) -> int: ...
    @typing.overload
    def read(self, charArray: list[str] | jpype.JArray) -> int: ...
    @typing.overload
    def read(self, charBuffer: java.nio.CharBuffer) -> int: ...
    def ready(self) -> bool: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...
    @typing.overload
    def unread(self, charArray: list[str] | jpype.JArray) -> None: ...
    @typing.overload
    def unread(
        self, charArray: list[str] | jpype.JArray, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def unread(self, int: int) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("java.io")``.

    BufferedInputStream: type[BufferedInputStream]
    BufferedOutputStream: type[BufferedOutputStream]
    BufferedReader: type[BufferedReader]
    BufferedWriter: type[BufferedWriter]
    ByteArrayInputStream: type[ByteArrayInputStream]
    ByteArrayOutputStream: type[ByteArrayOutputStream]
    CharArrayReader: type[CharArrayReader]
    CharArrayWriter: type[CharArrayWriter]
    CharConversionException: type[CharConversionException]
    Closeable: type[Closeable]
    Console: type[Console]
    DataInput: type[DataInput]
    DataInputStream: type[DataInputStream]
    DataOutput: type[DataOutput]
    DataOutputStream: type[DataOutputStream]
    EOFException: type[EOFException]
    Externalizable: type[Externalizable]
    File: type[File]
    FileDescriptor: type[FileDescriptor]
    FileFilter: type[FileFilter]
    FileInputStream: type[FileInputStream]
    FileNotFoundException: type[FileNotFoundException]
    FileOutputStream: type[FileOutputStream]
    FilePermission: type[FilePermission]
    FileReader: type[FileReader]
    FileWriter: type[FileWriter]
    FilenameFilter: type[FilenameFilter]
    FilterInputStream: type[FilterInputStream]
    FilterOutputStream: type[FilterOutputStream]
    FilterReader: type[FilterReader]
    FilterWriter: type[FilterWriter]
    Flushable: type[Flushable]
    IOError: type[IOError]
    IOException: type[IOException]
    InputStream: type[InputStream]
    InputStreamReader: type[InputStreamReader]
    InterruptedIOException: type[InterruptedIOException]
    InvalidClassException: type[InvalidClassException]
    InvalidObjectException: type[InvalidObjectException]
    LineNumberInputStream: type[LineNumberInputStream]
    LineNumberReader: type[LineNumberReader]
    NotActiveException: type[NotActiveException]
    NotSerializableException: type[NotSerializableException]
    ObjectInput: type[ObjectInput]
    ObjectInputFilter: type[ObjectInputFilter]
    ObjectInputStream: type[ObjectInputStream]
    ObjectInputValidation: type[ObjectInputValidation]
    ObjectOutput: type[ObjectOutput]
    ObjectOutputStream: type[ObjectOutputStream]
    ObjectStreamClass: type[ObjectStreamClass]
    ObjectStreamConstants: type[ObjectStreamConstants]
    ObjectStreamException: type[ObjectStreamException]
    ObjectStreamField: type[ObjectStreamField]
    OptionalDataException: type[OptionalDataException]
    OutputStream: type[OutputStream]
    OutputStreamWriter: type[OutputStreamWriter]
    PipedInputStream: type[PipedInputStream]
    PipedOutputStream: type[PipedOutputStream]
    PipedReader: type[PipedReader]
    PipedWriter: type[PipedWriter]
    PrintStream: type[PrintStream]
    PrintWriter: type[PrintWriter]
    PushbackInputStream: type[PushbackInputStream]
    PushbackReader: type[PushbackReader]
    RandomAccessFile: type[RandomAccessFile]
    Reader: type[Reader]
    SequenceInputStream: type[SequenceInputStream]
    Serial: type[Serial]
    Serializable: type[Serializable]
    SerializablePermission: type[SerializablePermission]
    StreamCorruptedException: type[StreamCorruptedException]
    StreamTokenizer: type[StreamTokenizer]
    StringBufferInputStream: type[StringBufferInputStream]
    StringReader: type[StringReader]
    StringWriter: type[StringWriter]
    SyncFailedException: type[SyncFailedException]
    UTFDataFormatException: type[UTFDataFormatException]
    UncheckedIOException: type[UncheckedIOException]
    UnsupportedEncodingException: type[UnsupportedEncodingException]
    WriteAbortedException: type[WriteAbortedException]
    Writer: type[Writer]
