import typing
from typing import Protocol

import java.lang
import java.util
import loci
import loci.poi.hssf.record

class AreaReference:
    def __init__(self, string: java.lang.String | str): ...
    def getCells(self) -> typing.MutableSequence[CellReference]: ...
    def getDim(self) -> int: ...
    def toString(self) -> java.lang.String: ...

class CellReference:
    @typing.overload
    def __init__(self, int: int, int2: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, boolean: bool, boolean2: bool): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    def getCol(self) -> int: ...
    def getRow(self) -> int: ...
    def getSheetName(self) -> java.lang.String: ...
    def isColAbsolute(self) -> bool: ...
    def isRowAbsolute(self) -> bool: ...
    def toString(self) -> java.lang.String: ...

class PaneInformation:
    PANE_LOWER_RIGHT: typing.ClassVar[int] = ...
    PANE_UPPER_RIGHT: typing.ClassVar[int] = ...
    PANE_LOWER_LEFT: typing.ClassVar[int] = ...
    PANE_UPPER_LEFT: typing.ClassVar[int] = ...
    def __init__(
        self,
        short: int,
        short2: int,
        short3: int,
        short4: int,
        byte: int,
        boolean: bool,
    ): ...
    def getActivePane(self) -> int: ...
    def getHorizontalSplitPosition(self) -> int: ...
    def getHorizontalSplitTopRow(self) -> int: ...
    def getVerticalSplitLeftColumn(self) -> int: ...
    def getVerticalSplitPosition(self) -> int: ...
    def isFreezePane(self) -> bool: ...

class RKUtil:
    @staticmethod
    def decodeNumber(int: int) -> float: ...

class RangeAddress:
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    def get26Sys(self, string: java.lang.String | str) -> int: ...
    def getAddress(self) -> java.lang.String: ...
    def getCharPart(self, string: java.lang.String | str) -> java.lang.String: ...
    def getDigitPart(self, string: java.lang.String | str) -> java.lang.String: ...
    def getFromCell(self) -> java.lang.String: ...
    def getHeight(self) -> int: ...
    def getRange(self) -> java.lang.String: ...
    def getSheetName(self) -> java.lang.String: ...
    def getToCell(self) -> java.lang.String: ...
    def getWidth(self) -> int: ...
    def getXPosition(self, string: java.lang.String | str) -> int: ...
    def getYPosition(self, string: java.lang.String | str) -> int: ...
    def hasCell(self) -> bool: ...
    def hasRange(self) -> bool: ...
    def hasSheetName(self) -> bool: ...
    def isCellOk(self, string: java.lang.String | str) -> bool: ...
    @typing.overload
    def isSheetNameOk(self) -> bool: ...
    @typing.overload
    @staticmethod
    def isSheetNameOk(string: java.lang.String | str) -> bool: ...
    def numTo26Sys(self, int: int) -> java.lang.String: ...
    def removeString(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ) -> java.lang.String: ...
    def replaceString(
        self,
        string: java.lang.String | str,
        string2: java.lang.String | str,
        string3: java.lang.String | str,
    ) -> java.lang.String: ...
    def setSize(self, int: int, int2: int) -> None: ...

class Region(java.lang.Comparable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int, short: int, int2: int, short2: int): ...
    @typing.overload
    def __init__(
        self, mergedRegion: loci.poi.hssf.record.MergeCellsRecord.MergedRegion
    ): ...
    @typing.overload
    def compareTo(self, object: typing.Any) -> int: ...
    @typing.overload
    def compareTo(self, region: Region) -> int: ...
    def contains(self, int: int, short: int) -> bool: ...
    @typing.overload
    def equals(self, object: typing.Any) -> bool: ...
    @typing.overload
    def equals(self, region: Region) -> bool: ...
    def getArea(self) -> int: ...
    def getColumnFrom(self) -> int: ...
    def getColumnTo(self) -> int: ...
    def getRowFrom(self) -> int: ...
    def getRowTo(self) -> int: ...
    def setColumnFrom(self, short: int) -> None: ...
    def setColumnTo(self, short: int) -> None: ...
    def setRowFrom(self, int: int) -> None: ...
    def setRowTo(self, int: int) -> None: ...

class SheetReferences:
    def __init__(self): ...
    def addSheetReference(self, string: java.lang.String | str, int: int) -> None: ...
    def getSheetName(self, int: int) -> java.lang.String: ...

class HSSFColor:
    def __init__(self): ...
    def getHexString(self) -> java.lang.String: ...
    def getIndex(self) -> int: ...
    @staticmethod
    def getIndexHash() -> java.util.Hashtable: ...
    def getTriplet(self) -> typing.MutableSequence[int]: ...
    @staticmethod
    def getTripletHash() -> java.util.Hashtable: ...
    class AQUA(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class AUTOMATIC(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        @staticmethod
        def getInstance() -> HSSFColor: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class BLACK(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class BLUE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        index2: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class BLUE_GREY(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class BRIGHT_GREEN(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        index2: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class BROWN(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class CORAL(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class CORNFLOWER_BLUE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class DARK_BLUE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        index2: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class DARK_GREEN(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class DARK_RED(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        index2: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class DARK_TEAL(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class DARK_YELLOW(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class GOLD(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class GREEN(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class GREY_25_PERCENT(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class GREY_40_PERCENT(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class GREY_50_PERCENT(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class GREY_80_PERCENT(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class INDIGO(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class LAVENDER(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class LEMON_CHIFFON(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class LIGHT_BLUE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class LIGHT_CORNFLOWER_BLUE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class LIGHT_GREEN(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class LIGHT_ORANGE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class LIGHT_TURQUOISE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        index2: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class LIGHT_YELLOW(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class LIME(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class MAROON(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class OLIVE_GREEN(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class ORANGE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class ORCHID(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class PALE_BLUE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class PINK(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        index2: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class PLUM(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        index2: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class RED(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class ROSE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class ROYAL_BLUE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class SEA_GREEN(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class SKY_BLUE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class TAN(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class TEAL(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        index2: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class TURQUOISE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        index2: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class VIOLET(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        index2: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class WHITE(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

    class YELLOW(loci.poi.hssf.util.HSSFColor):
        index: typing.ClassVar[int] = ...
        index2: typing.ClassVar[int] = ...
        triplet: typing.ClassVar[typing.MutableSequence[int]] = ...
        hexString: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
        def getHexString(self) -> java.lang.String: ...
        def getIndex(self) -> int: ...
        def getTriplet(self) -> typing.MutableSequence[int]: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("loci.poi.hssf.util")``.

    AreaReference: type[AreaReference]
    CellReference: type[CellReference]
    HSSFColor: type[HSSFColor]
    PaneInformation: type[PaneInformation]
    RKUtil: type[RKUtil]
    RangeAddress: type[RangeAddress]
    Region: type[Region]
    SheetReferences: type[SheetReferences]
