import typing
from typing import Protocol

import java.io
import java.util
import jpype
import loci
import loci.common
import loci.poi.poifs.filesystem
import loci.poi.poifs.property

class BlockAllocationTableReader:
    def __init__(
        self,
        int: int,
        intArray: list[int] | jpype.JArray,
        int3: int,
        int4: int,
        blockList: BlockList,
        int5: int,
    ): ...

class BlockList:
    def fetchBlocks(self, int: int) -> typing.MutableSequence[ListManagedBlock]: ...
    def remove(self, int: int) -> ListManagedBlock: ...
    def setBAT(
        self, blockAllocationTableReader: BlockAllocationTableReader
    ) -> None: ...
    def zap(self, int: int) -> None: ...

class BlockWritable:
    def writeBlocks(self, outputStream: java.io.OutputStream) -> None: ...

class HeaderBlockConstants:
    _signature: typing.ClassVar[int] = ...
    _bat_array_offset: typing.ClassVar[int] = ...
    _signature_offset: typing.ClassVar[int] = ...
    _bat_count_offset: typing.ClassVar[int] = ...
    _property_start_offset: typing.ClassVar[int] = ...
    _sbat_start_offset: typing.ClassVar[int] = ...
    _sbat_block_count_offset: typing.ClassVar[int] = ...
    _xbat_start_offset: typing.ClassVar[int] = ...
    _xbat_count_offset: typing.ClassVar[int] = ...

class ListManagedBlock:
    def getData(self) -> typing.MutableSequence[int]: ...

class SmallBlockTableReader:
    def __init__(self): ...
    @staticmethod
    def getSmallDocumentBlocks(
        rawDataBlockList: RawDataBlockList,
        rootProperty: loci.poi.poifs.property.RootProperty,
        int: int,
    ) -> BlockList: ...

class BlockAllocationTableWriter(BlockWritable, loci.poi.poifs.filesystem.BATManaged):
    def __init__(self): ...
    def allocateSpace(self, int: int) -> int: ...
    def countBlocks(self) -> int: ...
    def createBlocks(self, int: int) -> int: ...
    def getStartBlock(self) -> int: ...
    def setStartBlock(self, int: int) -> None: ...
    def writeBlocks(self, outputStream: java.io.OutputStream) -> None: ...

class HeaderBlockReader(HeaderBlockConstants):
    def __init__(self, inputStream: java.io.InputStream, int: int): ...
    def getBATArray(self) -> typing.MutableSequence[int]: ...
    def getBATCount(self) -> int: ...
    def getPropertyStart(self) -> int: ...
    def getSBATStart(self) -> int: ...
    def getXBATCount(self) -> int: ...
    def getXBATIndex(self) -> int: ...

class RawDataBlock(ListManagedBlock):
    def __init__(
        self,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
        int: int,
        long: int,
    ): ...
    def eof(self) -> bool: ...
    def getBlockSize(self) -> int: ...
    def getData(self) -> typing.MutableSequence[int]: ...
    def getLength(self) -> int: ...
    def getOffset(self) -> int: ...

class SmallBlockTableWriter(BlockWritable, loci.poi.poifs.filesystem.BATManaged):
    def __init__(
        self, list: java.util.List, rootProperty: loci.poi.poifs.property.RootProperty
    ): ...
    def countBlocks(self) -> int: ...
    def getSBAT(self) -> BlockAllocationTableWriter: ...
    def getSBATBlockCount(self) -> int: ...
    def setStartBlock(self, int: int) -> None: ...
    def writeBlocks(self, outputStream: java.io.OutputStream) -> None: ...

class SmallDocumentBlock(BlockWritable, ListManagedBlock):
    @staticmethod
    def calcSize(int: int) -> int: ...
    @typing.overload
    @staticmethod
    def convert(
        byteArray: list[int] | jpype.JArray | bytes, int: int
    ) -> typing.MutableSequence[SmallDocumentBlock]: ...
    @typing.overload
    @staticmethod
    def convert(
        blockWritableArray: list[BlockWritable] | jpype.JArray, int: int
    ) -> typing.MutableSequence[SmallDocumentBlock]: ...
    @staticmethod
    def extract(
        listManagedBlockArray: list[ListManagedBlock] | jpype.JArray, int: int
    ) -> java.util.List: ...
    @staticmethod
    def fill(list: java.util.List, int: int) -> int: ...
    def getBigBlockSize(self) -> int: ...
    def getData(self) -> typing.MutableSequence[int]: ...
    @staticmethod
    def read(
        blockWritableArray: list[BlockWritable] | jpype.JArray,
        byteArray: list[int] | jpype.JArray | bytes,
        int: int,
    ) -> None: ...
    def writeBlocks(self, outputStream: java.io.OutputStream) -> None: ...

class BATBlock(loci.poi.poifs.storage.BigBlock):
    @staticmethod
    def calculateStorageRequirements(int: int, int2: int) -> int: ...
    @staticmethod
    def calculateXBATStorageRequirements(int: int, int2: int) -> int: ...
    @staticmethod
    def createBATBlocks(
        intArray: list[int] | jpype.JArray, int2: int
    ) -> typing.MutableSequence[BATBlock]: ...
    @staticmethod
    def createXBATBlocks(
        intArray: list[int] | jpype.JArray, int2: int, int3: int
    ) -> typing.MutableSequence[BATBlock]: ...
    @staticmethod
    def entriesPerBlock(int: int) -> int: ...
    @staticmethod
    def entriesPerXBATBlock(int: int) -> int: ...
    def getBigBlockSize(self) -> int: ...
    @staticmethod
    def getXBATChainOffset(int: int) -> int: ...

class DocumentBlock(loci.poi.poifs.storage.BigBlock):
    @typing.overload
    def __init__(
        self, randomAccessInputStream: loci.common.RandomAccessInputStream, int: int
    ): ...
    @typing.overload
    def __init__(self, rawDataBlock: RawDataBlock, int: int): ...
    @staticmethod
    def convert(
        long: int,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
        int: int,
        int2: int,
        int3: int,
    ) -> typing.MutableSequence[DocumentBlock]: ...
    def getBigBlockSize(self) -> int: ...
    @staticmethod
    def getFillByte() -> int: ...
    def partiallyRead(self) -> bool: ...
    @staticmethod
    def read(
        documentBlockArray: list[DocumentBlock] | jpype.JArray,
        byteArray: list[int] | jpype.JArray | bytes,
        int: int,
        int2: int,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
    ) -> None: ...
    def size(self) -> int: ...

class HeaderBlockWriter(loci.poi.poifs.storage.BigBlock, HeaderBlockConstants):
    def __init__(self, int: int): ...
    def getBigBlockSize(self) -> int: ...
    def setBATBlocks(
        self, int: int, int2: int, int3: int
    ) -> typing.MutableSequence[BATBlock]: ...
    def setPropertyStart(self, int: int) -> None: ...
    def setSBATBlockCount(self, int: int) -> None: ...
    def setSBATStart(self, int: int) -> None: ...

class PropertyBlock(loci.poi.poifs.storage.BigBlock):
    @staticmethod
    def createPropertyBlockArray(
        list: java.util.List, int: int
    ) -> typing.MutableSequence[BlockWritable]: ...
    def getBigBlockSize(self) -> int: ...

class RawDataBlockList(loci.poi.poifs.storage.BlockListImpl):
    def __init__(
        self, randomAccessInputStream: loci.common.RandomAccessInputStream, int: int
    ): ...
    def getBigBlockSize(self) -> int: ...
    def getBlocks(self) -> typing.MutableSequence[ListManagedBlock]: ...

class SmallDocumentBlockList(loci.poi.poifs.storage.BlockListImpl):
    def __init__(self, list: java.util.List): ...
    def getBlocks(self) -> typing.MutableSequence[ListManagedBlock]: ...

class BigBlock: ...
class BlockListImpl: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("loci.poi.poifs.storage")``.

    BATBlock: type[BATBlock]
    BigBlock: type[BigBlock]
    BlockAllocationTableReader: type[BlockAllocationTableReader]
    BlockAllocationTableWriter: type[BlockAllocationTableWriter]
    BlockList: type[BlockList]
    BlockListImpl: type[BlockListImpl]
    BlockWritable: type[BlockWritable]
    DocumentBlock: type[DocumentBlock]
    HeaderBlockConstants: type[HeaderBlockConstants]
    HeaderBlockReader: type[HeaderBlockReader]
    HeaderBlockWriter: type[HeaderBlockWriter]
    ListManagedBlock: type[ListManagedBlock]
    PropertyBlock: type[PropertyBlock]
    RawDataBlock: type[RawDataBlock]
    RawDataBlockList: type[RawDataBlockList]
    SmallBlockTableReader: type[SmallBlockTableReader]
    SmallBlockTableWriter: type[SmallBlockTableWriter]
    SmallDocumentBlock: type[SmallDocumentBlock]
    SmallDocumentBlockList: type[SmallDocumentBlockList]
