import typing
from typing import Protocol

import java.lang
import java.util
import loci.common

class Column:
    def __init__(self, string: java.lang.String | str): ...
    def getName(self) -> java.lang.String: ...
    def getType(self) -> type: ...
    def getTypeString(self) -> java.lang.String: ...

class ColumnMap:
    def __init__(
        self,
        column: Column,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
        int: int,
    ): ...
    def getValueList(self) -> java.util.ArrayList: ...
    def getValues(self) -> typing.MutableSequence[typing.Any]: ...
    def isFixedMap(self) -> bool: ...

class MetakitException(java.lang.Exception):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, throwable: java.lang.Throwable
    ): ...
    @typing.overload
    def __init__(self, throwable: java.lang.Throwable): ...

class MetakitReader:
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, randomAccessInputStream: loci.common.RandomAccessInputStream
    ): ...
    def close(self) -> None: ...
    @typing.overload
    def getColumnNames(self, int: int) -> typing.MutableSequence[java.lang.String]: ...
    @typing.overload
    def getColumnNames(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[java.lang.String]: ...
    @typing.overload
    def getColumnTypes(self, int: int) -> typing.MutableSequence[type]: ...
    @typing.overload
    def getColumnTypes(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[type]: ...
    @typing.overload
    def getRowCount(self, int: int) -> int: ...
    @typing.overload
    def getRowCount(self, string: java.lang.String | str) -> int: ...
    @typing.overload
    def getRowData(self, int: int, int2: int) -> typing.MutableSequence[typing.Any]: ...
    @typing.overload
    def getRowData(
        self, int: int, string: java.lang.String | str
    ) -> typing.MutableSequence[typing.Any]: ...
    def getTableCount(self) -> int: ...
    @typing.overload
    def getTableData(
        self, int: int
    ) -> typing.MutableSequence[typing.MutableSequence[typing.Any]]: ...
    @typing.overload
    def getTableData(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[typing.MutableSequence[typing.Any]]: ...
    def getTableNames(self) -> typing.MutableSequence[java.lang.String]: ...

class MetakitTools:
    def __init__(self): ...
    @staticmethod
    def readBpInt(
        randomAccessInputStream: loci.common.RandomAccessInputStream,
    ) -> int: ...
    @staticmethod
    def readPString(
        randomAccessInputStream: loci.common.RandomAccessInputStream,
    ) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("ome.metakit")``.

    Column: type[Column]
    ColumnMap: type[ColumnMap]
    MetakitException: type[MetakitException]
    MetakitReader: type[MetakitReader]
    MetakitTools: type[MetakitTools]
