import typing
from typing import Protocol

import java.io
import java.lang
import java.nio
import jpype
import jpype.protocol
import ome

class DecodeContext:
    def __init__(self): ...
    def decodeFirstFrame(
        self, byteArray: list[int] | jpype.JArray | bytes, long: int, long2: int
    ) -> typing.MutableSequence[int]: ...
    def delete(self) -> None: ...

class DecodeException(java.lang.Exception):
    def __init__(self, string: java.lang.String | str): ...

class FormatError(java.lang.Exception):
    def __init__(self, string: java.lang.String | str): ...
    def delete(self) -> None: ...
    def getMessage(self) -> java.lang.String: ...

class GUID:
    def __init__(self): ...
    def delete(self) -> None: ...
    def getData1(self) -> int: ...
    def getData2(self) -> int: ...
    def getData3(self) -> int: ...
    def getData4(self) -> typing.MutableSequence[int]: ...
    def setData1(self, long: int) -> None: ...
    def setData2(self, int: int) -> None: ...
    def setData3(self, int: int) -> None: ...
    def setData4(self, shortArray: list[int] | jpype.JArray) -> None: ...

class ImageData:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, long: int): ...
    def add(self, char: str) -> None: ...
    def capacity(self) -> int: ...
    def clear(self) -> None: ...
    def delete(self) -> None: ...
    def get(self, int: int) -> str: ...
    def isEmpty(self) -> bool: ...
    def reserve(self, long: int) -> None: ...
    def set(self, int: int, char: str) -> None: ...
    def size(self) -> int: ...

class Decode(ome.jxrlib.AbstractDecode):
    @typing.overload
    def __init__(self, byteArray: list[int] | jpype.JArray | bytes): ...
    @typing.overload
    def __init__(self, file: java.io.File | jpype.protocol.SupportsPath): ...
    @typing.overload
    def __init__(self, byteBuffer: java.nio.ByteBuffer): ...
    @typing.overload
    def __init__(self, byteBuffer: java.nio.ByteBuffer, int: int, int2: int): ...
    @staticmethod
    def decodeFirstFrame(
        byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> typing.MutableSequence[int]: ...

class AbstractDecode: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("ome.jxrlib")``.

    AbstractDecode: type[AbstractDecode]
    Decode: type[Decode]
    DecodeContext: type[DecodeContext]
    DecodeException: type[DecodeException]
    FormatError: type[FormatError]
    GUID: type[GUID]
    ImageData: type[ImageData]
