import datetime
import typing
from typing import Protocol

import java.io
import java.lang
import java.nio
import java.security
import java.time
import java.util
import java.util.concurrent

class AclEntry:
    def equals(self, object: typing.Any) -> bool: ...
    def flags(self) -> java.util.Set[AclEntryFlag]: ...
    def hashCode(self) -> int: ...
    @typing.overload
    @staticmethod
    def newBuilder() -> AclEntry.Builder: ...
    @typing.overload
    @staticmethod
    def newBuilder(aclEntry: AclEntry) -> AclEntry.Builder: ...
    def permissions(self) -> java.util.Set[AclEntryPermission]: ...
    def principal(self) -> UserPrincipal: ...
    def toString(self) -> java.lang.String: ...
    def type(self) -> AclEntryType: ...
    class Builder:
        def build(self) -> AclEntry: ...
        @typing.overload
        def setFlags(self, *aclEntryFlag: AclEntryFlag) -> AclEntry.Builder: ...
        @typing.overload
        def setFlags(self, set: java.util.Set[AclEntryFlag]) -> AclEntry.Builder: ...
        @typing.overload
        def setPermissions(
            self, *aclEntryPermission: AclEntryPermission
        ) -> AclEntry.Builder: ...
        @typing.overload
        def setPermissions(
            self, set: java.util.Set[AclEntryPermission]
        ) -> AclEntry.Builder: ...
        def setPrincipal(
            self, userPrincipal: UserPrincipal | typing.Callable
        ) -> AclEntry.Builder: ...
        def setType(self, aclEntryType: AclEntryType) -> AclEntry.Builder: ...

class AclEntryFlag(java.lang.Enum["AclEntryFlag"]):
    FILE_INHERIT: typing.ClassVar[AclEntryFlag] = ...
    DIRECTORY_INHERIT: typing.ClassVar[AclEntryFlag] = ...
    NO_PROPAGATE_INHERIT: typing.ClassVar[AclEntryFlag] = ...
    INHERIT_ONLY: typing.ClassVar[AclEntryFlag] = ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: type[_valueOf_0__T], string: java.lang.String | str
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: java.lang.String | str) -> AclEntryFlag: ...
    @staticmethod
    def values() -> typing.MutableSequence[AclEntryFlag]: ...

class AclEntryPermission(java.lang.Enum["AclEntryPermission"]):
    READ_DATA: typing.ClassVar[AclEntryPermission] = ...
    WRITE_DATA: typing.ClassVar[AclEntryPermission] = ...
    APPEND_DATA: typing.ClassVar[AclEntryPermission] = ...
    READ_NAMED_ATTRS: typing.ClassVar[AclEntryPermission] = ...
    WRITE_NAMED_ATTRS: typing.ClassVar[AclEntryPermission] = ...
    EXECUTE: typing.ClassVar[AclEntryPermission] = ...
    DELETE_CHILD: typing.ClassVar[AclEntryPermission] = ...
    READ_ATTRIBUTES: typing.ClassVar[AclEntryPermission] = ...
    WRITE_ATTRIBUTES: typing.ClassVar[AclEntryPermission] = ...
    DELETE: typing.ClassVar[AclEntryPermission] = ...
    READ_ACL: typing.ClassVar[AclEntryPermission] = ...
    WRITE_ACL: typing.ClassVar[AclEntryPermission] = ...
    WRITE_OWNER: typing.ClassVar[AclEntryPermission] = ...
    SYNCHRONIZE: typing.ClassVar[AclEntryPermission] = ...
    LIST_DIRECTORY: typing.ClassVar[AclEntryPermission] = ...
    ADD_FILE: typing.ClassVar[AclEntryPermission] = ...
    ADD_SUBDIRECTORY: typing.ClassVar[AclEntryPermission] = ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: type[_valueOf_0__T], string: java.lang.String | str
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: java.lang.String | str) -> AclEntryPermission: ...
    @staticmethod
    def values() -> typing.MutableSequence[AclEntryPermission]: ...

class AclEntryType(java.lang.Enum["AclEntryType"]):
    ALLOW: typing.ClassVar[AclEntryType] = ...
    DENY: typing.ClassVar[AclEntryType] = ...
    AUDIT: typing.ClassVar[AclEntryType] = ...
    ALARM: typing.ClassVar[AclEntryType] = ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: type[_valueOf_0__T], string: java.lang.String | str
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: java.lang.String | str) -> AclEntryType: ...
    @staticmethod
    def values() -> typing.MutableSequence[AclEntryType]: ...

class AttributeView:
    def name(self) -> java.lang.String: ...

class BasicFileAttributes:
    def creationTime(self) -> FileTime: ...
    def fileKey(self) -> typing.Any: ...
    def isDirectory(self) -> bool: ...
    def isOther(self) -> bool: ...
    def isRegularFile(self) -> bool: ...
    def isSymbolicLink(self) -> bool: ...
    def lastAccessTime(self) -> FileTime: ...
    def lastModifiedTime(self) -> FileTime: ...
    def size(self) -> int: ...

_FileAttribute__T = typing.TypeVar("_FileAttribute__T")  # <T>

class FileAttribute(typing.Generic[_FileAttribute__T]):
    def name(self) -> java.lang.String: ...
    def value(self) -> _FileAttribute__T: ...

class FileTime(java.lang.Comparable["FileTime"]):
    def compareTo(self, fileTime: FileTime) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromMillis(long: int) -> FileTime: ...
    @typing.overload
    @staticmethod
    def from_(instant: java.time.Instant | datetime.datetime) -> FileTime: ...
    @typing.overload
    @staticmethod
    def from_(long: int, timeUnit: java.util.concurrent.TimeUnit) -> FileTime: ...
    def hashCode(self) -> int: ...
    def to(self, timeUnit: java.util.concurrent.TimeUnit) -> int: ...
    def toInstant(self) -> java.time.Instant: ...
    def toMillis(self) -> int: ...
    def toString(self) -> java.lang.String: ...

class PosixFilePermission(java.lang.Enum["PosixFilePermission"]):
    OWNER_READ: typing.ClassVar[PosixFilePermission] = ...
    OWNER_WRITE: typing.ClassVar[PosixFilePermission] = ...
    OWNER_EXECUTE: typing.ClassVar[PosixFilePermission] = ...
    GROUP_READ: typing.ClassVar[PosixFilePermission] = ...
    GROUP_WRITE: typing.ClassVar[PosixFilePermission] = ...
    GROUP_EXECUTE: typing.ClassVar[PosixFilePermission] = ...
    OTHERS_READ: typing.ClassVar[PosixFilePermission] = ...
    OTHERS_WRITE: typing.ClassVar[PosixFilePermission] = ...
    OTHERS_EXECUTE: typing.ClassVar[PosixFilePermission] = ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: type[_valueOf_0__T], string: java.lang.String | str
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: java.lang.String | str) -> PosixFilePermission: ...
    @staticmethod
    def values() -> typing.MutableSequence[PosixFilePermission]: ...

class PosixFilePermissions:
    @staticmethod
    def asFileAttribute(
        set: java.util.Set[PosixFilePermission],
    ) -> FileAttribute[java.util.Set[PosixFilePermission]]: ...
    @staticmethod
    def fromString(
        string: java.lang.String | str,
    ) -> java.util.Set[PosixFilePermission]: ...
    @typing.overload
    def toString(self) -> java.lang.String: ...
    @typing.overload
    @staticmethod
    def toString(set: java.util.Set[PosixFilePermission]) -> java.lang.String: ...

class UserPrincipal(java.security.Principal):
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> java.lang.String: ...

class UserPrincipalLookupService:
    def lookupPrincipalByGroupName(
        self, string: java.lang.String | str
    ) -> GroupPrincipal: ...
    def lookupPrincipalByName(
        self, string: java.lang.String | str
    ) -> UserPrincipal: ...

class UserPrincipalNotFoundException(java.io.IOException):
    def __init__(self, string: java.lang.String | str): ...
    def getName(self) -> java.lang.String: ...

class DosFileAttributes(BasicFileAttributes):
    def isArchive(self) -> bool: ...
    def isHidden(self) -> bool: ...
    def isReadOnly(self) -> bool: ...
    def isSystem(self) -> bool: ...

class FileAttributeView(AttributeView): ...
class FileStoreAttributeView(AttributeView): ...

class GroupPrincipal(UserPrincipal):
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> java.lang.String: ...

class PosixFileAttributes(BasicFileAttributes):
    def group(self) -> GroupPrincipal: ...
    def owner(self) -> UserPrincipal: ...
    def permissions(self) -> java.util.Set[PosixFilePermission]: ...

class BasicFileAttributeView(FileAttributeView):
    def name(self) -> java.lang.String: ...
    def readAttributes(self) -> BasicFileAttributes: ...
    def setTimes(
        self, fileTime: FileTime, fileTime2: FileTime, fileTime3: FileTime
    ) -> None: ...

class FileOwnerAttributeView(FileAttributeView):
    def getOwner(self) -> UserPrincipal: ...
    def name(self) -> java.lang.String: ...
    def setOwner(self, userPrincipal: UserPrincipal | typing.Callable) -> None: ...

class UserDefinedFileAttributeView(FileAttributeView):
    def delete(self, string: java.lang.String | str) -> None: ...
    def list(self) -> java.util.List[java.lang.String]: ...
    def name(self) -> java.lang.String: ...
    def read(
        self, string: java.lang.String | str, byteBuffer: java.nio.ByteBuffer
    ) -> int: ...
    def size(self, string: java.lang.String | str) -> int: ...
    def write(
        self, string: java.lang.String | str, byteBuffer: java.nio.ByteBuffer
    ) -> int: ...

class AclFileAttributeView(FileOwnerAttributeView):
    def getAcl(self) -> java.util.List[AclEntry]: ...
    def name(self) -> java.lang.String: ...
    def setAcl(self, list: java.util.List[AclEntry]) -> None: ...

class DosFileAttributeView(BasicFileAttributeView):
    def name(self) -> java.lang.String: ...
    def readAttributes(self) -> DosFileAttributes: ...
    def setArchive(self, boolean: bool) -> None: ...
    def setHidden(self, boolean: bool) -> None: ...
    def setReadOnly(self, boolean: bool) -> None: ...
    def setSystem(self, boolean: bool) -> None: ...

class PosixFileAttributeView(BasicFileAttributeView, FileOwnerAttributeView):
    def name(self) -> java.lang.String: ...
    def readAttributes(self) -> PosixFileAttributes: ...
    def setGroup(self, groupPrincipal: GroupPrincipal | typing.Callable) -> None: ...
    def setPermissions(self, set: java.util.Set[PosixFilePermission]) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("java.nio.file.attribute")``.

    AclEntry: type[AclEntry]
    AclEntryFlag: type[AclEntryFlag]
    AclEntryPermission: type[AclEntryPermission]
    AclEntryType: type[AclEntryType]
    AclFileAttributeView: type[AclFileAttributeView]
    AttributeView: type[AttributeView]
    BasicFileAttributeView: type[BasicFileAttributeView]
    BasicFileAttributes: type[BasicFileAttributes]
    DosFileAttributeView: type[DosFileAttributeView]
    DosFileAttributes: type[DosFileAttributes]
    FileAttribute: type[FileAttribute]
    FileAttributeView: type[FileAttributeView]
    FileOwnerAttributeView: type[FileOwnerAttributeView]
    FileStoreAttributeView: type[FileStoreAttributeView]
    FileTime: type[FileTime]
    GroupPrincipal: type[GroupPrincipal]
    PosixFileAttributeView: type[PosixFileAttributeView]
    PosixFileAttributes: type[PosixFileAttributes]
    PosixFilePermission: type[PosixFilePermission]
    PosixFilePermissions: type[PosixFilePermissions]
    UserDefinedFileAttributeView: type[UserDefinedFileAttributeView]
    UserPrincipal: type[UserPrincipal]
    UserPrincipalLookupService: type[UserPrincipalLookupService]
    UserPrincipalNotFoundException: type[UserPrincipalNotFoundException]
