import typing
from typing import Protocol

import java.io
import java.lang
import jpype
import loci.poi.hssf.record

class BiffViewer:
    def __init__(self, stringArray: list[java.lang.String] | jpype.JArray): ...
    @staticmethod
    def createRecords(
        inputStream: java.io.InputStream, boolean: bool
    ) -> typing.MutableSequence[loci.poi.hssf.record.Record]: ...
    @staticmethod
    def main(stringArray: list[java.lang.String] | jpype.JArray) -> None: ...
    def run(self) -> None: ...
    def setDump(self, boolean: bool) -> None: ...

class EFBiffViewer:
    def __init__(self): ...
    @staticmethod
    def main(stringArray: list[java.lang.String] | jpype.JArray) -> None: ...
    def run(self) -> None: ...
    def setFile(self, string: java.lang.String | str) -> None: ...

class FormulaViewer:
    def __init__(self): ...
    @staticmethod
    def main(stringArray: list[java.lang.String] | jpype.JArray) -> None: ...
    def parseFormulaRecord(
        self, formulaRecord: loci.poi.hssf.record.FormulaRecord
    ) -> None: ...
    def run(self) -> None: ...
    def setFile(self, string: java.lang.String | str) -> None: ...
    def setList(self, boolean: bool) -> None: ...

class HSSF:
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str, boolean: bool): ...
    @typing.overload
    def __init__(
        self,
        string: java.lang.String | str,
        string2: java.lang.String | str,
        boolean: bool,
    ): ...
    @staticmethod
    def main(stringArray: list[java.lang.String] | jpype.JArray) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("loci.poi.hssf.dev")``.

    BiffViewer: type[BiffViewer]
    EFBiffViewer: type[EFBiffViewer]
    FormulaViewer: type[FormulaViewer]
    HSSF: type[HSSF]
