import typing
from typing import Protocol

import java.awt.event
import java.awt.image
import java.io
import java.lang
import java.util
import javax.swing
import jpype
import jpype.protocol
import loci.common
import loci.formats

class AmiraParameters:
    width: int = ...
    height: int = ...
    depth: int = ...
    firstDataStream: int = ...
    x0: float = ...
    y0: float = ...
    z0: float = ...
    x1: float = ...
    y1: float = ...
    z1: float = ...
    littleEndian: bool = ...
    ascii: bool = ...
    nStreams: int = ...
    streamNames: typing.MutableSequence[java.lang.String] = ...
    streamTypes: typing.MutableSequence[java.lang.String] = ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, randomAccessInputStream: loci.common.RandomAccessInputStream
    ): ...
    @staticmethod
    def entryToString(
        object: typing.Any, string: java.lang.String | str
    ) -> java.lang.String: ...
    def getMap(self) -> java.util.Map: ...
    def getStreams(self) -> java.util.Map: ...
    @staticmethod
    def main(stringArray: list[java.lang.String] | jpype.JArray) -> None: ...
    @typing.overload
    def toString(self) -> java.lang.String: ...
    @typing.overload
    @staticmethod
    def toString(
        map: java.util.Map | typing.Mapping, string: java.lang.String | str
    ) -> java.lang.String: ...

class AsciiImage:
    def __init__(self, bufferedImage: java.awt.image.BufferedImage): ...
    def toString(self) -> java.lang.String: ...

class BioFormatsExtensionPrinter:
    def __init__(self): ...
    @staticmethod
    def main(stringArray: list[java.lang.String] | jpype.JArray) -> None: ...

class CacheConsole:
    @staticmethod
    def main(stringArray: list[java.lang.String] | jpype.JArray) -> None: ...

class EditTiffG(javax.swing.JFrame, java.awt.event.ActionListener):
    def __init__(self): ...
    def actionPerformed(self, actionEvent: java.awt.event.ActionEvent) -> None: ...
    def exit(self) -> None: ...
    def getXML(self) -> java.lang.String: ...
    @staticmethod
    def main(stringArray: list[java.lang.String] | jpype.JArray) -> None: ...
    @typing.overload
    @staticmethod
    def open(string: java.lang.String | str) -> loci.common.RandomAccessInputStream: ...
    @typing.overload
    def open(self) -> None: ...
    @typing.overload
    @staticmethod
    def openFile(string: java.lang.String | str) -> None: ...
    @typing.overload
    def openFile(self, file: java.io.File | jpype.protocol.SupportsPath) -> None: ...
    @typing.overload
    def openFile(
        self,
        file: java.io.File | jpype.protocol.SupportsPath,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
    ) -> None: ...
    def save(self) -> None: ...
    def saveFile(self, file: java.io.File | jpype.protocol.SupportsPath) -> None: ...
    def setXML(self, string: java.lang.String | str) -> None: ...
    def showError(self, throwable: java.lang.Throwable) -> None: ...

class FakeImage:
    def __init__(self, location: loci.common.Location): ...
    def generateScreen(
        self, int: int, int2: int, int3: int, int4: int, int5: int
    ) -> loci.common.Location: ...
    @staticmethod
    def isValidRange(int: int, int2: int, int3: int) -> None: ...

class MakeTestOmeTiff:
    sizeZsub: int = ...
    sizeTsub: int = ...
    sizeCsub: int = ...
    isModulo: bool = ...
    def __init__(self): ...
    @staticmethod
    def main(stringArray: list[java.lang.String] | jpype.JArray) -> None: ...
    @typing.overload
    def makeOmeTiff(self, *string: java.lang.String | str) -> int: ...
    @typing.overload
    def makeOmeTiff(
        self, string: java.lang.String | str, coreMetadata: loci.formats.CoreMetadata
    ) -> None: ...
    def makeOmeTiffExtensions(self, *string: java.lang.String | str) -> None: ...
    def makeSamples(self) -> None: ...

class UpgradeCheck:
    def __init__(self): ...
    @staticmethod
    def main(stringArray: list[java.lang.String] | jpype.JArray) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("loci.formats.tools")``.

    AmiraParameters: type[AmiraParameters]
    AsciiImage: type[AsciiImage]
    BioFormatsExtensionPrinter: type[BioFormatsExtensionPrinter]
    CacheConsole: type[CacheConsole]
    EditTiffG: type[EditTiffG]
    FakeImage: type[FakeImage]
    MakeTestOmeTiff: type[MakeTestOmeTiff]
    UpgradeCheck: type[UpgradeCheck]
