import typing
from typing import Protocol

import ch.systemsx.cisd.base.mdarray
import ch.systemsx.cisd.hdf5
import com.esotericsoftware.kryo
import com.esotericsoftware.kryo.io
import java.awt.image
import java.io
import java.lang
import java.util
import jpype
import loci.common
import loci.common.services
import loci.formats
import loci.formats.codec
import loci.formats.meta
import loci.formats.ome
import ome.xml.model
import org.w3c.dom

class EXIFService(loci.common.services.Service):
    def close(self) -> None: ...
    def getCreationDate(self) -> java.util.Date: ...
    def getTags(self) -> java.util.HashMap[java.lang.String, java.lang.String]: ...
    def initialize(self, string: java.lang.String | str) -> None: ...

class JAIIIOService(loci.common.services.Service):
    @typing.overload
    def readImage(
        self, inputStream: java.io.InputStream
    ) -> java.awt.image.BufferedImage: ...
    @typing.overload
    def readImage(
        self,
        inputStream: java.io.InputStream,
        jPEG2000CodecOptions: loci.formats.codec.JPEG2000CodecOptions,
    ) -> java.awt.image.BufferedImage: ...
    @typing.overload
    def readRaster(self, inputStream: java.io.InputStream) -> java.awt.image.Raster: ...
    @typing.overload
    def readRaster(
        self,
        inputStream: java.io.InputStream,
        jPEG2000CodecOptions: loci.formats.codec.JPEG2000CodecOptions,
    ) -> java.awt.image.Raster: ...
    def writeImage(
        self,
        outputStream: java.io.OutputStream,
        bufferedImage: java.awt.image.BufferedImage,
        jPEG2000CodecOptions: loci.formats.codec.JPEG2000CodecOptions,
    ) -> None: ...

class JHDFService(loci.common.services.Service):
    def close(self) -> None: ...
    def createGroup(self, string: java.lang.String | str) -> None: ...
    def exists(self, string: java.lang.String | str) -> bool: ...
    def getElementSize(self, string: java.lang.String | str) -> int: ...
    def getFile(self) -> java.lang.String: ...
    def getMember(
        self, string: java.lang.String | str
    ) -> java.util.List[java.lang.String]: ...
    def getShape(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[int]: ...
    def initIntArray(
        self,
        string: java.lang.String | str,
        longArray: list[int] | jpype.JArray,
        long2: int,
    ) -> None: ...
    def readByteArray(
        self, string: java.lang.String | str
    ) -> ch.systemsx.cisd.base.mdarray.MDByteArray: ...
    def readByteBlockArray(
        self,
        string: java.lang.String | str,
        intArray: list[int] | jpype.JArray,
        intArray2: list[int] | jpype.JArray,
    ) -> ch.systemsx.cisd.base.mdarray.MDByteArray: ...
    def readCompoundArrayDataMap(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[ch.systemsx.cisd.hdf5.HDF5CompoundDataMap]: ...
    def readIntArray(
        self, string: java.lang.String | str
    ) -> ch.systemsx.cisd.base.mdarray.MDIntArray: ...
    def readIntBlockArray(
        self,
        string: java.lang.String | str,
        intArray: list[int] | jpype.JArray,
        intArray2: list[int] | jpype.JArray,
    ) -> ch.systemsx.cisd.base.mdarray.MDIntArray: ...
    def readShortBlockArray(
        self,
        string: java.lang.String | str,
        intArray: list[int] | jpype.JArray,
        intArray2: list[int] | jpype.JArray,
    ) -> ch.systemsx.cisd.base.mdarray.MDShortArray: ...
    def readStringArray(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[java.lang.String]: ...
    def setFile(self, string: java.lang.String | str) -> None: ...
    def setFileForWrite(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def writeArraySlice(
        self,
        string: java.lang.String | str,
        mDByteArray: ch.systemsx.cisd.base.mdarray.MDByteArray,
        longArray: list[int] | jpype.JArray,
    ) -> None: ...
    @typing.overload
    def writeArraySlice(
        self,
        string: java.lang.String | str,
        mDIntArray: ch.systemsx.cisd.base.mdarray.MDIntArray,
        longArray: list[int] | jpype.JArray,
    ) -> None: ...
    @typing.overload
    def writeArraySlice(
        self,
        string: java.lang.String | str,
        mDShortArray: ch.systemsx.cisd.base.mdarray.MDShortArray,
        longArray: list[int] | jpype.JArray,
    ) -> None: ...

class JPEGTurboService(loci.common.services.Service):
    def close(self) -> None: ...
    @typing.overload
    def getCompressedTile(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getCompressedTile(self, int: int, int2: int) -> typing.MutableSequence[int]: ...
    def getRestartMarkers(self) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getTile(
        self,
        byteArray: list[int] | jpype.JArray | bytes,
        int: int,
        int2: int,
        int3: int,
        int4: int,
    ) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getTile(self, int: int, int2: int) -> typing.MutableSequence[int]: ...
    def getTileColumns(self) -> int: ...
    def getTileHeight(self) -> int: ...
    def getTileRows(self) -> int: ...
    def getTileWidth(self) -> int: ...
    def initialize(
        self,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
        int: int,
        int2: int,
    ) -> None: ...
    def isLibraryLoaded(self) -> bool: ...
    def setRestartMarkers(self, longArray: list[int] | jpype.JArray) -> None: ...

class JPEGXRService(loci.common.services.Service):
    def decompress(
        self, byteArray: list[int] | jpype.JArray | bytes
    ) -> typing.MutableSequence[int]: ...

class MDBService(loci.common.services.Service):
    def close(self) -> None: ...
    def initialize(self, string: java.lang.String | str) -> None: ...
    def parseDatabase(
        self,
    ) -> java.util.Vector[
        java.util.Vector[typing.MutableSequence[java.lang.String]]
    ]: ...
    def parseTable(
        self, string: java.lang.String | str
    ) -> java.util.Vector[typing.MutableSequence[java.lang.String]]: ...

class MetakitService(loci.common.services.Service):
    def close(self) -> None: ...
    def getColumNames(self, int: int) -> typing.MutableSequence[java.lang.String]: ...
    def getColumnNames(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[java.lang.String]: ...
    @typing.overload
    def getColumnTypes(self, int: int) -> typing.MutableSequence[type]: ...
    @typing.overload
    def getColumnTypes(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[type]: ...
    @typing.overload
    def getRowCount(self, int: int) -> int: ...
    @typing.overload
    def getRowCount(self, string: java.lang.String | str) -> int: ...
    @typing.overload
    def getRowData(self, int: int, int2: int) -> typing.MutableSequence[typing.Any]: ...
    @typing.overload
    def getRowData(
        self, int: int, string: java.lang.String | str
    ) -> typing.MutableSequence[typing.Any]: ...
    def getTableCount(self) -> int: ...
    @typing.overload
    def getTableData(
        self, int: int
    ) -> typing.MutableSequence[typing.MutableSequence[typing.Any]]: ...
    @typing.overload
    def getTableData(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[typing.MutableSequence[typing.Any]]: ...
    def getTableNames(self) -> typing.MutableSequence[java.lang.String]: ...
    @typing.overload
    def initialize(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def initialize(
        self, randomAccessInputStream: loci.common.RandomAccessInputStream
    ) -> None: ...

class NetCDFService(loci.common.services.Service):
    def close(self) -> None: ...
    def getArray(
        self,
        string: java.lang.String | str,
        intArray: list[int] | jpype.JArray,
        intArray2: list[int] | jpype.JArray,
    ) -> typing.Any: ...
    def getAttributeList(self) -> java.util.Vector[java.lang.String]: ...
    def getAttributeValue(self, string: java.lang.String | str) -> java.lang.String: ...
    def getDimension(self, string: java.lang.String | str) -> int: ...
    def getFile(self) -> java.lang.String: ...
    def getVariableAttributes(
        self, string: java.lang.String | str
    ) -> java.util.Hashtable[java.lang.String, typing.Any]: ...
    def getVariableList(self) -> java.util.Vector[java.lang.String]: ...
    def getVariableValue(self, string: java.lang.String | str) -> typing.Any: ...
    def setFile(self, string: java.lang.String | str) -> None: ...

class OMEXMLService(loci.common.services.Service):
    @typing.overload
    def addMetadataOnly(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata, int: int
    ) -> None: ...
    @typing.overload
    def addMetadataOnly(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata, int: int, boolean: bool
    ) -> None: ...
    def addModuloAlong(
        self,
        oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata,
        coreMetadata: loci.formats.CoreMetadata,
        int: int,
    ) -> None: ...
    def asRetrieve(
        self, metadataStore: loci.formats.meta.MetadataStore
    ) -> loci.formats.meta.MetadataRetrieve: ...
    def asStore(
        self, metadataRetrieve: loci.formats.meta.MetadataRetrieve
    ) -> loci.formats.meta.MetadataStore: ...
    @typing.overload
    def convertMetadata(
        self,
        string: java.lang.String | str,
        metadataStore: loci.formats.meta.MetadataStore,
    ) -> None: ...
    @typing.overload
    def convertMetadata(
        self,
        metadataRetrieve: loci.formats.meta.MetadataRetrieve,
        metadataStore: loci.formats.meta.MetadataStore,
    ) -> None: ...
    @typing.overload
    def createOMEXMLMetadata(self) -> loci.formats.ome.OMEXMLMetadata: ...
    @typing.overload
    def createOMEXMLMetadata(
        self, string: java.lang.String | str
    ) -> loci.formats.ome.OMEXMLMetadata: ...
    @typing.overload
    def createOMEXMLMetadata(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ) -> loci.formats.ome.OMEXMLMetadata: ...
    def createOMEXMLRoot(
        self, string: java.lang.String | str
    ) -> ome.xml.model.OMEModelObject: ...
    def getLatestVersion(self) -> java.lang.String: ...
    def getModuloAlongC(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata, int: int
    ) -> loci.formats.Modulo: ...
    def getModuloAlongT(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata, int: int
    ) -> loci.formats.Modulo: ...
    def getModuloAlongZ(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata, int: int
    ) -> loci.formats.Modulo: ...
    def getOMEMetadata(
        self, metadataRetrieve: loci.formats.meta.MetadataRetrieve
    ) -> loci.formats.ome.OMEXMLMetadata: ...
    def getOMEXML(
        self, metadataRetrieve: loci.formats.meta.MetadataRetrieve
    ) -> java.lang.String: ...
    def getOMEXMLVersion(self, object: typing.Any) -> java.lang.String: ...
    def getOriginalMetadata(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata
    ) -> java.util.Hashtable: ...
    def isEqual(
        self,
        oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata,
        oMEXMLMetadata2: loci.formats.ome.OMEXMLMetadata,
    ) -> bool: ...
    def isOMEXMLMetadata(self, object: typing.Any) -> bool: ...
    def isOMEXMLRoot(self, object: typing.Any) -> bool: ...
    @typing.overload
    def populateOriginalMetadata(
        self,
        oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata,
        string: java.lang.String | str,
        string2: java.lang.String | str,
    ) -> None: ...
    @typing.overload
    def populateOriginalMetadata(
        self,
        oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata,
        hashtable: java.util.Hashtable[java.lang.String | str, typing.Any],
    ) -> None: ...
    def removeBinData(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata
    ) -> None: ...
    def removeChannels(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata, int: int, int2: int
    ) -> None: ...
    def removeTiffData(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata
    ) -> None: ...
    def transformToLatestVersion(
        self, string: java.lang.String | str
    ) -> java.lang.String: ...
    @typing.overload
    def validateOMEXML(self, string: java.lang.String | str) -> bool: ...
    @typing.overload
    def validateOMEXML(self, string: java.lang.String | str, boolean: bool) -> bool: ...

class POIService(loci.common.services.Service):
    def close(self) -> None: ...
    @typing.overload
    def getDocumentBytes(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getDocumentBytes(
        self, string: java.lang.String | str, int: int
    ) -> typing.MutableSequence[int]: ...
    def getDocumentList(self) -> java.util.Vector[java.lang.String]: ...
    def getDocumentStream(
        self, string: java.lang.String | str
    ) -> loci.common.RandomAccessInputStream: ...
    def getFileSize(self, string: java.lang.String | str) -> int: ...
    def getInputStream(self, string: java.lang.String | str) -> java.io.InputStream: ...
    @typing.overload
    def initialize(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def initialize(
        self, randomAccessInputStream: loci.common.RandomAccessInputStream
    ) -> None: ...

class EXIFServiceImpl(loci.common.services.AbstractService, EXIFService):
    def __init__(self): ...
    def close(self) -> None: ...
    def getCreationDate(self) -> java.util.Date: ...
    def getTags(self) -> java.util.HashMap[java.lang.String, java.lang.String]: ...
    def initialize(self, string: java.lang.String | str) -> None: ...

class JAIIIOServiceImpl(loci.common.services.AbstractService, JAIIIOService):
    NO_J2K_MSG: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    @typing.overload
    def readImage(
        self, inputStream: java.io.InputStream
    ) -> java.awt.image.BufferedImage: ...
    @typing.overload
    def readImage(
        self,
        inputStream: java.io.InputStream,
        jPEG2000CodecOptions: loci.formats.codec.JPEG2000CodecOptions,
    ) -> java.awt.image.BufferedImage: ...
    @typing.overload
    def readRaster(self, inputStream: java.io.InputStream) -> java.awt.image.Raster: ...
    @typing.overload
    def readRaster(
        self,
        inputStream: java.io.InputStream,
        jPEG2000CodecOptions: loci.formats.codec.JPEG2000CodecOptions,
    ) -> java.awt.image.Raster: ...
    def writeImage(
        self,
        outputStream: java.io.OutputStream,
        bufferedImage: java.awt.image.BufferedImage,
        jPEG2000CodecOptions: loci.formats.codec.JPEG2000CodecOptions,
    ) -> None: ...

class JHDFServiceImpl(loci.common.services.AbstractService, JHDFService):
    NO_JHDF_MSG: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def close(self) -> None: ...
    def createGroup(self, string: java.lang.String | str) -> None: ...
    def exists(self, string: java.lang.String | str) -> bool: ...
    def getElementSize(self, string: java.lang.String | str) -> int: ...
    def getFile(self) -> java.lang.String: ...
    def getMember(
        self, string: java.lang.String | str
    ) -> java.util.List[java.lang.String]: ...
    def getShape(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[int]: ...
    def initIntArray(
        self,
        string: java.lang.String | str,
        longArray: list[int] | jpype.JArray,
        long2: int,
    ) -> None: ...
    def readByteArray(
        self, string: java.lang.String | str
    ) -> ch.systemsx.cisd.base.mdarray.MDByteArray: ...
    def readByteBlockArray(
        self,
        string: java.lang.String | str,
        intArray: list[int] | jpype.JArray,
        intArray2: list[int] | jpype.JArray,
    ) -> ch.systemsx.cisd.base.mdarray.MDByteArray: ...
    def readCompoundArrayDataMap(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[ch.systemsx.cisd.hdf5.HDF5CompoundDataMap]: ...
    def readIntArray(
        self, string: java.lang.String | str
    ) -> ch.systemsx.cisd.base.mdarray.MDIntArray: ...
    def readIntBlockArray(
        self,
        string: java.lang.String | str,
        intArray: list[int] | jpype.JArray,
        intArray2: list[int] | jpype.JArray,
    ) -> ch.systemsx.cisd.base.mdarray.MDIntArray: ...
    def readShortBlockArray(
        self,
        string: java.lang.String | str,
        intArray: list[int] | jpype.JArray,
        intArray2: list[int] | jpype.JArray,
    ) -> ch.systemsx.cisd.base.mdarray.MDShortArray: ...
    def readStringArray(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[java.lang.String]: ...
    def setFile(self, string: java.lang.String | str) -> None: ...
    def setFileForWrite(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def writeArraySlice(
        self,
        string: java.lang.String | str,
        mDByteArray: ch.systemsx.cisd.base.mdarray.MDByteArray,
        longArray: list[int] | jpype.JArray,
    ) -> None: ...
    @typing.overload
    def writeArraySlice(
        self,
        string: java.lang.String | str,
        mDIntArray: ch.systemsx.cisd.base.mdarray.MDIntArray,
        longArray: list[int] | jpype.JArray,
    ) -> None: ...
    @typing.overload
    def writeArraySlice(
        self,
        string: java.lang.String | str,
        mDShortArray: ch.systemsx.cisd.base.mdarray.MDShortArray,
        longArray: list[int] | jpype.JArray,
    ) -> None: ...

class JPEGTurboServiceImpl(JPEGTurboService):
    def __init__(self): ...
    def close(self) -> None: ...
    @typing.overload
    def getCompressedTile(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getCompressedTile(self, int: int, int2: int) -> typing.MutableSequence[int]: ...
    def getRestartMarkers(self) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getTile(
        self,
        byteArray: list[int] | jpype.JArray | bytes,
        int: int,
        int2: int,
        int3: int,
        int4: int,
    ) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getTile(self, int: int, int2: int) -> typing.MutableSequence[int]: ...
    def getTileColumns(self) -> int: ...
    def getTileHeight(self) -> int: ...
    def getTileRows(self) -> int: ...
    def getTileWidth(self) -> int: ...
    def initialize(
        self,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
        int: int,
        int2: int,
    ) -> None: ...
    def isLibraryLoaded(self) -> bool: ...
    def setRestartMarkers(self, longArray: list[int] | jpype.JArray) -> None: ...

class JPEGXRServiceImpl(loci.common.services.AbstractService, JPEGXRService):
    def __init__(self): ...
    def decompress(
        self, byteArray: list[int] | jpype.JArray | bytes
    ) -> typing.MutableSequence[int]: ...

class MDBServiceImpl(loci.common.services.AbstractService, MDBService):
    def __init__(self): ...
    def close(self) -> None: ...
    def initialize(self, string: java.lang.String | str) -> None: ...
    def parseDatabase(
        self,
    ) -> java.util.Vector[
        java.util.Vector[typing.MutableSequence[java.lang.String]]
    ]: ...
    def parseTable(
        self, string: java.lang.String | str
    ) -> java.util.Vector[typing.MutableSequence[java.lang.String]]: ...

class MetakitServiceImpl(MetakitService):
    def __init__(self): ...
    def close(self) -> None: ...
    def getColumNames(self, int: int) -> typing.MutableSequence[java.lang.String]: ...
    def getColumnNames(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[java.lang.String]: ...
    @typing.overload
    def getColumnTypes(self, int: int) -> typing.MutableSequence[type]: ...
    @typing.overload
    def getColumnTypes(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[type]: ...
    @typing.overload
    def getRowCount(self, int: int) -> int: ...
    @typing.overload
    def getRowCount(self, string: java.lang.String | str) -> int: ...
    @typing.overload
    def getRowData(self, int: int, int2: int) -> typing.MutableSequence[typing.Any]: ...
    @typing.overload
    def getRowData(
        self, int: int, string: java.lang.String | str
    ) -> typing.MutableSequence[typing.Any]: ...
    def getTableCount(self) -> int: ...
    @typing.overload
    def getTableData(
        self, int: int
    ) -> typing.MutableSequence[typing.MutableSequence[typing.Any]]: ...
    @typing.overload
    def getTableData(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[typing.MutableSequence[typing.Any]]: ...
    def getTableNames(self) -> typing.MutableSequence[java.lang.String]: ...
    @typing.overload
    def initialize(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def initialize(
        self, randomAccessInputStream: loci.common.RandomAccessInputStream
    ) -> None: ...

class NetCDFServiceImpl(
    loci.common.services.AbstractService,
    NetCDFService,
    com.esotericsoftware.kryo.KryoSerializable,
):
    NO_NETCDF_MSG: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def close(self) -> None: ...
    def getArray(
        self,
        string: java.lang.String | str,
        intArray: list[int] | jpype.JArray,
        intArray2: list[int] | jpype.JArray,
    ) -> typing.Any: ...
    def getAttributeList(self) -> java.util.Vector[java.lang.String]: ...
    def getAttributeValue(self, string: java.lang.String | str) -> java.lang.String: ...
    def getDimension(self, string: java.lang.String | str) -> int: ...
    def getFile(self) -> java.lang.String: ...
    def getVariableAttributes(
        self, string: java.lang.String | str
    ) -> java.util.Hashtable[java.lang.String, typing.Any]: ...
    def getVariableList(self) -> java.util.Vector[java.lang.String]: ...
    def getVariableValue(self, string: java.lang.String | str) -> typing.Any: ...
    def read(
        self,
        kryo: com.esotericsoftware.kryo.Kryo,
        input: com.esotericsoftware.kryo.io.Input,
    ) -> None: ...
    def setFile(self, string: java.lang.String | str) -> None: ...
    def write(
        self,
        kryo: com.esotericsoftware.kryo.Kryo,
        output: com.esotericsoftware.kryo.io.Output,
    ) -> None: ...

class OMEXMLServiceImpl(loci.common.services.AbstractService, OMEXMLService):
    LATEST_VERSION: typing.ClassVar[java.lang.String] = ...
    NO_OME_XML_MSG: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    @typing.overload
    def addMetadataOnly(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata, int: int
    ) -> None: ...
    @typing.overload
    def addMetadataOnly(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata, int: int, boolean: bool
    ) -> None: ...
    def addModuloAlong(
        self,
        oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata,
        coreMetadata: loci.formats.CoreMetadata,
        int: int,
    ) -> None: ...
    def asRetrieve(
        self, metadataStore: loci.formats.meta.MetadataStore
    ) -> loci.formats.meta.MetadataRetrieve: ...
    def asStore(
        self, metadataRetrieve: loci.formats.meta.MetadataRetrieve
    ) -> loci.formats.meta.MetadataStore: ...
    @typing.overload
    def convertMetadata(
        self,
        string: java.lang.String | str,
        metadataStore: loci.formats.meta.MetadataStore,
    ) -> None: ...
    @typing.overload
    def convertMetadata(
        self,
        metadataRetrieve: loci.formats.meta.MetadataRetrieve,
        metadataStore: loci.formats.meta.MetadataStore,
    ) -> None: ...
    @typing.overload
    def createOMEXMLMetadata(self) -> loci.formats.ome.OMEXMLMetadata: ...
    @typing.overload
    def createOMEXMLMetadata(
        self, string: java.lang.String | str
    ) -> loci.formats.ome.OMEXMLMetadata: ...
    @typing.overload
    def createOMEXMLMetadata(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ) -> loci.formats.ome.OMEXMLMetadata: ...
    def createOMEXMLRoot(
        self, string: java.lang.String | str
    ) -> ome.xml.model.OMEModelObject: ...
    @typing.overload
    def equals(self, object: typing.Any) -> bool: ...
    @typing.overload
    def equals(self, node: org.w3c.dom.Node, node2: org.w3c.dom.Node) -> bool: ...
    def getLatestVersion(self) -> java.lang.String: ...
    def getModuloAlongC(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata, int: int
    ) -> loci.formats.Modulo: ...
    def getModuloAlongT(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata, int: int
    ) -> loci.formats.Modulo: ...
    def getModuloAlongZ(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata, int: int
    ) -> loci.formats.Modulo: ...
    def getOMEMetadata(
        self, metadataRetrieve: loci.formats.meta.MetadataRetrieve
    ) -> loci.formats.ome.OMEXMLMetadata: ...
    def getOMEXML(
        self, metadataRetrieve: loci.formats.meta.MetadataRetrieve
    ) -> java.lang.String: ...
    def getOMEXMLVersion(self, object: typing.Any) -> java.lang.String: ...
    def getOriginalMetadata(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata
    ) -> java.util.Hashtable: ...
    def isEqual(
        self,
        oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata,
        oMEXMLMetadata2: loci.formats.ome.OMEXMLMetadata,
    ) -> bool: ...
    def isOMEXMLMetadata(self, object: typing.Any) -> bool: ...
    def isOMEXMLRoot(self, object: typing.Any) -> bool: ...
    @typing.overload
    def populateOriginalMetadata(
        self,
        oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata,
        string: java.lang.String | str,
        string2: java.lang.String | str,
    ) -> None: ...
    @typing.overload
    def populateOriginalMetadata(
        self,
        oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata,
        hashtable: java.util.Hashtable[java.lang.String | str, typing.Any],
    ) -> None: ...
    def removeBinData(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata
    ) -> None: ...
    def removeChannels(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata, int: int, int2: int
    ) -> None: ...
    def removeTiffData(
        self, oMEXMLMetadata: loci.formats.ome.OMEXMLMetadata
    ) -> None: ...
    def transformToLatestVersion(
        self, string: java.lang.String | str
    ) -> java.lang.String: ...
    @typing.overload
    def validateOMEXML(self, string: java.lang.String | str) -> bool: ...
    @typing.overload
    def validateOMEXML(self, string: java.lang.String | str, boolean: bool) -> bool: ...

class POIServiceImpl(loci.common.services.AbstractService, POIService):
    def __init__(self): ...
    def close(self) -> None: ...
    @typing.overload
    def getDocumentBytes(
        self, string: java.lang.String | str
    ) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getDocumentBytes(
        self, string: java.lang.String | str, int: int
    ) -> typing.MutableSequence[int]: ...
    def getDocumentList(self) -> java.util.Vector[java.lang.String]: ...
    def getDocumentStream(
        self, string: java.lang.String | str
    ) -> loci.common.RandomAccessInputStream: ...
    def getFileSize(self, string: java.lang.String | str) -> int: ...
    def getInputStream(self, string: java.lang.String | str) -> java.io.InputStream: ...
    @typing.overload
    def initialize(self, string: java.lang.String | str) -> None: ...
    @typing.overload
    def initialize(
        self, randomAccessInputStream: loci.common.RandomAccessInputStream
    ) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("loci.formats.services")``.

    EXIFService: type[EXIFService]
    EXIFServiceImpl: type[EXIFServiceImpl]
    JAIIIOService: type[JAIIIOService]
    JAIIIOServiceImpl: type[JAIIIOServiceImpl]
    JHDFService: type[JHDFService]
    JHDFServiceImpl: type[JHDFServiceImpl]
    JPEGTurboService: type[JPEGTurboService]
    JPEGTurboServiceImpl: type[JPEGTurboServiceImpl]
    JPEGXRService: type[JPEGXRService]
    JPEGXRServiceImpl: type[JPEGXRServiceImpl]
    MDBService: type[MDBService]
    MDBServiceImpl: type[MDBServiceImpl]
    MetakitService: type[MetakitService]
    MetakitServiceImpl: type[MetakitServiceImpl]
    NetCDFService: type[NetCDFService]
    NetCDFServiceImpl: type[NetCDFServiceImpl]
    OMEXMLService: type[OMEXMLService]
    OMEXMLServiceImpl: type[OMEXMLServiceImpl]
    POIService: type[POIService]
    POIServiceImpl: type[POIServiceImpl]
