import typing
from typing import Protocol

import java.io
import java.lang
import java.util
import jpype

class BackingStoreException(java.lang.Exception):
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(self, throwable: java.lang.Throwable): ...

class InvalidPreferencesFormatException(java.lang.Exception):
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    @typing.overload
    def __init__(
        self, string: java.lang.String | str, throwable: java.lang.Throwable
    ): ...
    @typing.overload
    def __init__(self, throwable: java.lang.Throwable): ...

class NodeChangeEvent(java.util.EventObject):
    def __init__(self, preferences: Preferences, preferences2: Preferences): ...
    def getChild(self) -> Preferences: ...
    def getParent(self) -> Preferences: ...

class NodeChangeListener(java.util.EventListener):
    def childAdded(self, nodeChangeEvent: NodeChangeEvent) -> None: ...
    def childRemoved(self, nodeChangeEvent: NodeChangeEvent) -> None: ...

class PreferenceChangeEvent(java.util.EventObject):
    def __init__(
        self,
        preferences: Preferences,
        string: java.lang.String | str,
        string2: java.lang.String | str,
    ): ...
    def getKey(self) -> java.lang.String: ...
    def getNewValue(self) -> java.lang.String: ...
    def getNode(self) -> Preferences: ...

class PreferenceChangeListener(java.util.EventListener):
    def preferenceChange(
        self, preferenceChangeEvent: PreferenceChangeEvent
    ) -> None: ...

class Preferences:
    MAX_KEY_LENGTH: typing.ClassVar[int] = ...
    MAX_VALUE_LENGTH: typing.ClassVar[int] = ...
    MAX_NAME_LENGTH: typing.ClassVar[int] = ...
    def absolutePath(self) -> java.lang.String: ...
    def addNodeChangeListener(self, nodeChangeListener: NodeChangeListener) -> None: ...
    def addPreferenceChangeListener(
        self, preferenceChangeListener: PreferenceChangeListener | typing.Callable
    ) -> None: ...
    def childrenNames(self) -> typing.MutableSequence[java.lang.String]: ...
    def clear(self) -> None: ...
    def exportNode(self, outputStream: java.io.OutputStream) -> None: ...
    def exportSubtree(self, outputStream: java.io.OutputStream) -> None: ...
    def flush(self) -> None: ...
    def get(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ) -> java.lang.String: ...
    def getBoolean(self, string: java.lang.String | str, boolean: bool) -> bool: ...
    def getByteArray(
        self,
        string: java.lang.String | str,
        byteArray: list[int] | jpype.JArray | bytes,
    ) -> typing.MutableSequence[int]: ...
    def getDouble(self, string: java.lang.String | str, double: float) -> float: ...
    def getFloat(self, string: java.lang.String | str, float: float) -> float: ...
    def getInt(self, string: java.lang.String | str, int: int) -> int: ...
    def getLong(self, string: java.lang.String | str, long: int) -> int: ...
    @staticmethod
    def importPreferences(inputStream: java.io.InputStream) -> None: ...
    def isUserNode(self) -> bool: ...
    def keys(self) -> typing.MutableSequence[java.lang.String]: ...
    def name(self) -> java.lang.String: ...
    def node(self, string: java.lang.String | str) -> Preferences: ...
    def nodeExists(self, string: java.lang.String | str) -> bool: ...
    def parent(self) -> Preferences: ...
    def put(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ) -> None: ...
    def putBoolean(self, string: java.lang.String | str, boolean: bool) -> None: ...
    def putByteArray(
        self,
        string: java.lang.String | str,
        byteArray: list[int] | jpype.JArray | bytes,
    ) -> None: ...
    def putDouble(self, string: java.lang.String | str, double: float) -> None: ...
    def putFloat(self, string: java.lang.String | str, float: float) -> None: ...
    def putInt(self, string: java.lang.String | str, int: int) -> None: ...
    def putLong(self, string: java.lang.String | str, long: int) -> None: ...
    def remove(self, string: java.lang.String | str) -> None: ...
    def removeNode(self) -> None: ...
    def removeNodeChangeListener(
        self, nodeChangeListener: NodeChangeListener
    ) -> None: ...
    def removePreferenceChangeListener(
        self, preferenceChangeListener: PreferenceChangeListener | typing.Callable
    ) -> None: ...
    def sync(self) -> None: ...
    @staticmethod
    def systemNodeForPackage(class_: type[typing.Any]) -> Preferences: ...
    @staticmethod
    def systemRoot() -> Preferences: ...
    def toString(self) -> java.lang.String: ...
    @staticmethod
    def userNodeForPackage(class_: type[typing.Any]) -> Preferences: ...
    @staticmethod
    def userRoot() -> Preferences: ...

class PreferencesFactory:
    def systemRoot(self) -> Preferences: ...
    def userRoot(self) -> Preferences: ...

class AbstractPreferences(Preferences):
    def absolutePath(self) -> java.lang.String: ...
    def addNodeChangeListener(self, nodeChangeListener: NodeChangeListener) -> None: ...
    def addPreferenceChangeListener(
        self, preferenceChangeListener: PreferenceChangeListener | typing.Callable
    ) -> None: ...
    def childrenNames(self) -> typing.MutableSequence[java.lang.String]: ...
    def clear(self) -> None: ...
    def exportNode(self, outputStream: java.io.OutputStream) -> None: ...
    def exportSubtree(self, outputStream: java.io.OutputStream) -> None: ...
    def flush(self) -> None: ...
    def get(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ) -> java.lang.String: ...
    def getBoolean(self, string: java.lang.String | str, boolean: bool) -> bool: ...
    def getByteArray(
        self,
        string: java.lang.String | str,
        byteArray: list[int] | jpype.JArray | bytes,
    ) -> typing.MutableSequence[int]: ...
    def getDouble(self, string: java.lang.String | str, double: float) -> float: ...
    def getFloat(self, string: java.lang.String | str, float: float) -> float: ...
    def getInt(self, string: java.lang.String | str, int: int) -> int: ...
    def getLong(self, string: java.lang.String | str, long: int) -> int: ...
    def isUserNode(self) -> bool: ...
    def keys(self) -> typing.MutableSequence[java.lang.String]: ...
    def name(self) -> java.lang.String: ...
    def node(self, string: java.lang.String | str) -> Preferences: ...
    def nodeExists(self, string: java.lang.String | str) -> bool: ...
    def parent(self) -> Preferences: ...
    def put(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ) -> None: ...
    def putBoolean(self, string: java.lang.String | str, boolean: bool) -> None: ...
    def putByteArray(
        self,
        string: java.lang.String | str,
        byteArray: list[int] | jpype.JArray | bytes,
    ) -> None: ...
    def putDouble(self, string: java.lang.String | str, double: float) -> None: ...
    def putFloat(self, string: java.lang.String | str, float: float) -> None: ...
    def putInt(self, string: java.lang.String | str, int: int) -> None: ...
    def putLong(self, string: java.lang.String | str, long: int) -> None: ...
    def remove(self, string: java.lang.String | str) -> None: ...
    def removeNode(self) -> None: ...
    def removeNodeChangeListener(
        self, nodeChangeListener: NodeChangeListener
    ) -> None: ...
    def removePreferenceChangeListener(
        self, preferenceChangeListener: PreferenceChangeListener | typing.Callable
    ) -> None: ...
    def sync(self) -> None: ...
    def toString(self) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("java.util.prefs")``.

    AbstractPreferences: type[AbstractPreferences]
    BackingStoreException: type[BackingStoreException]
    InvalidPreferencesFormatException: type[InvalidPreferencesFormatException]
    NodeChangeEvent: type[NodeChangeEvent]
    NodeChangeListener: type[NodeChangeListener]
    PreferenceChangeEvent: type[PreferenceChangeEvent]
    PreferenceChangeListener: type[PreferenceChangeListener]
    Preferences: type[Preferences]
    PreferencesFactory: type[PreferencesFactory]
