import typing
from typing import Protocol

import java.lang
import java.util
import jpype
import loci.poi.ddf
import loci.poi.hssf.record
import loci.poi.hssf.record.formula
import loci.poi.hssf.usermodel
import loci.poi.hssf.util

class AbstractShape:
    @staticmethod
    def createShape(
        hSSFShape: loci.poi.hssf.usermodel.HSSFShape, int: int
    ) -> AbstractShape: ...
    def getObjRecord(self) -> loci.poi.hssf.record.ObjRecord: ...
    def getSpContainer(self) -> loci.poi.ddf.EscherContainerRecord: ...

class ConvertAnchor:
    def __init__(self): ...
    @staticmethod
    def createAnchor(
        hSSFAnchor: loci.poi.hssf.usermodel.HSSFAnchor,
    ) -> loci.poi.ddf.EscherRecord: ...

class DrawingManager:
    def __init__(self, escherDggRecord: loci.poi.ddf.EscherDggRecord): ...
    def allocateShapeId(self, short: int) -> int: ...
    def createDgRecord(self) -> loci.poi.ddf.EscherDgRecord: ...
    def getDgg(self) -> loci.poi.ddf.EscherDggRecord: ...

class DrawingManager2:
    def __init__(self, escherDggRecord: loci.poi.ddf.EscherDggRecord): ...
    def allocateShapeId(self, short: int) -> int: ...
    def createDgRecord(self) -> loci.poi.ddf.EscherDgRecord: ...
    def getDgg(self) -> loci.poi.ddf.EscherDggRecord: ...

class FormulaParser:
    FORMULA_TYPE_CELL: typing.ClassVar[int] = ...
    FORMULA_TYPE_SHARED: typing.ClassVar[int] = ...
    FORMULA_TYPE_ARRAY: typing.ClassVar[int] = ...
    FORMULA_TYPE_CONDFOMRAT: typing.ClassVar[int] = ...
    FORMULA_TYPE_NAMEDRANGE: typing.ClassVar[int] = ...
    def __init__(self, string: java.lang.String | str, workbook: Workbook): ...
    @typing.overload
    def getRPNPtg(self) -> typing.MutableSequence[loci.poi.hssf.record.formula.Ptg]: ...
    @typing.overload
    def getRPNPtg(
        self, int: int
    ) -> typing.MutableSequence[loci.poi.hssf.record.formula.Ptg]: ...
    def parse(self) -> None: ...
    @typing.overload
    def toFormulaString(self, list: java.util.List) -> java.lang.String: ...
    @typing.overload
    def toFormulaString(
        self, ptgArray: list[loci.poi.hssf.record.formula.Ptg] | jpype.JArray
    ) -> java.lang.String: ...
    @typing.overload
    @staticmethod
    def toFormulaString(
        workbook: Workbook, list: java.util.List
    ) -> java.lang.String: ...
    @typing.overload
    @staticmethod
    def toFormulaString(
        workbook: Workbook,
        ptgArray: list[loci.poi.hssf.record.formula.Ptg] | jpype.JArray,
    ) -> java.lang.String: ...
    def toString(self) -> java.lang.String: ...

class Model: ...

class WorkbookRecordList:
    def __init__(self): ...
    def add(self, int: int, record: loci.poi.hssf.record.Record) -> None: ...
    def get(self, int: int) -> loci.poi.hssf.record.Record: ...
    def getBackuppos(self) -> int: ...
    def getBspos(self) -> int: ...
    def getExternsheetPos(self) -> int: ...
    def getFontpos(self) -> int: ...
    def getNamepos(self) -> int: ...
    def getPalettepos(self) -> int: ...
    def getProtpos(self) -> int: ...
    def getRecords(self) -> java.util.List: ...
    def getSupbookpos(self) -> int: ...
    def getTabpos(self) -> int: ...
    def getXfpos(self) -> int: ...
    def iterator(self) -> java.util.Iterator: ...
    @typing.overload
    def remove(self, int: int) -> None: ...
    @typing.overload
    def remove(self, object: typing.Any) -> None: ...
    def setBackuppos(self, int: int) -> None: ...
    def setBspos(self, int: int) -> None: ...
    def setExternsheetPos(self, int: int) -> None: ...
    def setFontpos(self, int: int) -> None: ...
    def setNamepos(self, int: int) -> None: ...
    def setPalettepos(self, int: int) -> None: ...
    def setProtpos(self, int: int) -> None: ...
    def setRecords(self, list: java.util.List) -> None: ...
    def setSupbookpos(self, int: int) -> None: ...
    def setTabpos(self, int: int) -> None: ...
    def setXfpos(self, int: int) -> None: ...
    def size(self) -> int: ...

class LineShape(AbstractShape):
    def getObjRecord(self) -> loci.poi.hssf.record.ObjRecord: ...
    def getSpContainer(self) -> loci.poi.ddf.EscherContainerRecord: ...

class PictureShape(AbstractShape):
    def getObjRecord(self) -> loci.poi.hssf.record.ObjRecord: ...
    def getSpContainer(self) -> loci.poi.ddf.EscherContainerRecord: ...

class PolygonShape(AbstractShape):
    OBJECT_TYPE_MICROSOFT_OFFICE_DRAWING: typing.ClassVar[int] = ...
    def getObjRecord(self) -> loci.poi.hssf.record.ObjRecord: ...
    def getSpContainer(self) -> loci.poi.ddf.EscherContainerRecord: ...

class Sheet(Model):
    LeftMargin: typing.ClassVar[int] = ...
    RightMargin: typing.ClassVar[int] = ...
    TopMargin: typing.ClassVar[int] = ...
    BottomMargin: typing.ClassVar[int] = ...
    PANE_LOWER_RIGHT: typing.ClassVar[int] = ...
    PANE_UPPER_RIGHT: typing.ClassVar[int] = ...
    PANE_LOWER_LEFT: typing.ClassVar[int] = ...
    PANE_UPPER_LEFT: typing.ClassVar[int] = ...
    def __init__(self): ...
    def addMergedRegion(self, int: int, short: int, int2: int, short2: int) -> int: ...
    def addRow(self, rowRecord: loci.poi.hssf.record.RowRecord) -> None: ...
    def addValueRecord(
        self,
        int: int,
        cellValueRecordInterface: loci.poi.hssf.record.CellValueRecordInterface,
    ) -> None: ...
    def aggregateDrawingRecords(self, drawingManager2: DrawingManager2) -> int: ...
    def checkDimsLoc(self, record: loci.poi.hssf.record.Record, int: int) -> None: ...
    def cloneSheet(self) -> Sheet: ...
    def createBlank(self, int: int, short: int) -> loci.poi.hssf.record.BlankRecord: ...
    def createFormula(
        self, int: int, short: int, string: java.lang.String | str
    ) -> loci.poi.hssf.record.FormulaRecord: ...
    def createFreezePane(self, int: int, int2: int, int3: int, int4: int) -> None: ...
    def createLabelSST(
        self, int: int, short: int, int2: int
    ) -> loci.poi.hssf.record.LabelSSTRecord: ...
    def createNumber(
        self, int: int, short: int, double: float
    ) -> loci.poi.hssf.record.NumberRecord: ...
    def createRow(self, int: int) -> loci.poi.hssf.record.RowRecord: ...
    @typing.overload
    @staticmethod
    def createSheet() -> Sheet: ...
    @typing.overload
    @staticmethod
    def createSheet(list: java.util.List, int: int) -> Sheet: ...
    @typing.overload
    @staticmethod
    def createSheet(list: java.util.List, int: int, int2: int) -> Sheet: ...
    def createSplitPane(
        self, int: int, int2: int, int3: int, int4: int, int5: int
    ) -> None: ...
    def findFirstRecordBySid(self, short: int) -> loci.poi.hssf.record.Record: ...
    def findFirstRecordLocBySid(self, short: int) -> int: ...
    def getActiveCellCol(self) -> int: ...
    def getActiveCellRow(self) -> int: ...
    def getColumnBreaks(self) -> java.util.Iterator: ...
    def getColumnWidth(self, short: int) -> int: ...
    def getDefaultColumnWidth(self) -> int: ...
    def getDefaultRowHeight(self) -> int: ...
    def getDimsLoc(self) -> int: ...
    def getEofLoc(self) -> int: ...
    def getFooter(self) -> loci.poi.hssf.record.FooterRecord: ...
    def getGridsetRecord(self) -> loci.poi.hssf.record.GridsetRecord: ...
    def getHeader(self) -> loci.poi.hssf.record.HeaderRecord: ...
    def getLeftCol(self) -> int: ...
    def getLoc(self) -> int: ...
    def getMargin(self, short: int) -> float: ...
    def getMergedRegionAt(
        self, int: int
    ) -> loci.poi.hssf.record.MergeCellsRecord.MergedRegion: ...
    def getNextRow(self) -> loci.poi.hssf.record.RowRecord: ...
    def getNextValueRecord(self) -> loci.poi.hssf.record.CellValueRecordInterface: ...
    def getNumColumnBreaks(self) -> int: ...
    def getNumMergedRegions(self) -> int: ...
    def getNumRecords(self) -> int: ...
    def getNumRowBreaks(self) -> int: ...
    def getPaneInformation(self) -> loci.poi.hssf.util.PaneInformation: ...
    def getPassword(self) -> loci.poi.hssf.record.PasswordRecord: ...
    def getPreOffset(self) -> int: ...
    def getPrintGridlines(self) -> loci.poi.hssf.record.PrintGridlinesRecord: ...
    def getPrintSetup(self) -> loci.poi.hssf.record.PrintSetupRecord: ...
    def getProtect(self) -> loci.poi.hssf.record.ProtectRecord: ...
    def getRecords(self) -> java.util.List: ...
    def getRow(self, int: int) -> loci.poi.hssf.record.RowRecord: ...
    def getRowBreaks(self) -> java.util.Iterator: ...
    def getSelection(self) -> loci.poi.hssf.record.SelectionRecord: ...
    def getSize(self) -> int: ...
    def getTopRow(self) -> int: ...
    def getXFIndexForColAt(self, short: int) -> int: ...
    def groupColumnRange(self, short: int, short2: int, boolean: bool) -> None: ...
    def groupRowRange(self, int: int, int2: int, boolean: bool) -> None: ...
    def isColumnBroken(self, short: int) -> bool: ...
    def isColumnHidden(self, short: int) -> bool: ...
    def isDisplayFormulas(self) -> bool: ...
    def isDisplayGridlines(self) -> bool: ...
    def isDisplayRowColHeadings(self) -> bool: ...
    def isGridsPrinted(self) -> bool: ...
    def isProtected(self) -> typing.MutableSequence[bool]: ...
    def isRowBroken(self, int: int) -> bool: ...
    def preSerialize(self) -> None: ...
    def protectSheet(
        self, string: java.lang.String | str, boolean: bool, boolean2: bool
    ) -> None: ...
    def removeColumnBreak(self, short: int) -> None: ...
    def removeMergedRegion(self, int: int) -> None: ...
    def removeRow(self, rowRecord: loci.poi.hssf.record.RowRecord) -> None: ...
    def removeRowBreak(self, int: int) -> None: ...
    def removeValueRecord(
        self,
        int: int,
        cellValueRecordInterface: loci.poi.hssf.record.CellValueRecordInterface,
    ) -> None: ...
    def replaceValueRecord(
        self, cellValueRecordInterface: loci.poi.hssf.record.CellValueRecordInterface
    ) -> None: ...
    def serialize(
        self, int: int, byteArray: list[int] | jpype.JArray | bytes
    ) -> int: ...
    def setActiveCellCol(self, short: int) -> None: ...
    def setActiveCellRow(self, int: int) -> None: ...
    @typing.overload
    def setColumn(
        self, short: int, short2: int, integer: int, boolean: bool, boolean2: bool
    ) -> None: ...
    @typing.overload
    def setColumn(
        self,
        short: int,
        short2: int,
        short3: int,
        integer: int,
        boolean: bool,
        boolean2: bool,
    ) -> None: ...
    def setColumnBreak(self, short: int, short2: int, short3: int) -> None: ...
    def setColumnGroupCollapsed(self, short: int, boolean: bool) -> None: ...
    def setColumnHidden(self, short: int, boolean: bool) -> None: ...
    def setColumnWidth(self, short: int, short2: int) -> None: ...
    def setDefaultColumnWidth(self, short: int) -> None: ...
    def setDefaultRowHeight(self, short: int) -> None: ...
    def setDimensions(self, int: int, short: int, int2: int, short2: int) -> None: ...
    def setDisplayFormulas(self, boolean: bool) -> None: ...
    def setDisplayGridlines(self, boolean: bool) -> None: ...
    def setDisplayRowColHeadings(self, boolean: bool) -> None: ...
    def setFooter(self, footerRecord: loci.poi.hssf.record.FooterRecord) -> None: ...
    def setGridsPrinted(self, boolean: bool) -> None: ...
    def setHeader(self, headerRecord: loci.poi.hssf.record.HeaderRecord) -> None: ...
    def setLeftCol(self, short: int) -> None: ...
    def setLoc(self, int: int) -> None: ...
    def setMargin(self, short: int, double: float) -> None: ...
    def setPreOffset(self, int: int) -> None: ...
    def setPrintGridlines(
        self, printGridlinesRecord: loci.poi.hssf.record.PrintGridlinesRecord
    ) -> None: ...
    def setPrintSetup(
        self, printSetupRecord: loci.poi.hssf.record.PrintSetupRecord
    ) -> None: ...
    def setRowBreak(self, int: int, short: int, short2: int) -> None: ...
    def setRowGroupCollapsed(self, int: int, boolean: bool) -> None: ...
    def setSCLRecord(self, sCLRecord: loci.poi.hssf.record.SCLRecord) -> None: ...
    def setSelected(self, boolean: bool) -> None: ...
    def setSelection(
        self, selectionRecord: loci.poi.hssf.record.SelectionRecord
    ) -> None: ...
    def setTopRow(self, short: int) -> None: ...
    def shiftBreaks(
        self,
        pageBreakRecord: loci.poi.hssf.record.PageBreakRecord,
        short: int,
        short2: int,
        int: int,
    ) -> None: ...
    def shiftColumnBreaks(self, short: int, short2: int, short3: int) -> None: ...
    def shiftRowBreaks(self, int: int, int2: int, int3: int) -> None: ...
    def unprotectSheet(self, boolean: bool, boolean2: bool, boolean3: bool) -> None: ...

class SimpleFilledShape(AbstractShape):
    def getObjRecord(self) -> loci.poi.hssf.record.ObjRecord: ...
    def getSpContainer(self) -> loci.poi.ddf.EscherContainerRecord: ...

class TextboxShape(AbstractShape):
    def getEscherTextbox(self) -> loci.poi.ddf.EscherRecord: ...
    def getObjRecord(self) -> loci.poi.hssf.record.ObjRecord: ...
    def getSpContainer(self) -> loci.poi.ddf.EscherContainerRecord: ...
    def getTextObjectRecord(self) -> loci.poi.hssf.record.TextObjectRecord: ...

class Workbook(Model):
    def __init__(self): ...
    def addBSERecord(self, escherBSERecord: loci.poi.ddf.EscherBSERecord) -> int: ...
    def addName(
        self, nameRecord: loci.poi.hssf.record.NameRecord
    ) -> loci.poi.hssf.record.NameRecord: ...
    def addSSTString(
        self, unicodeString: loci.poi.hssf.record.UnicodeString
    ) -> int: ...
    def checkExternSheet(self, int: int) -> int: ...
    def createBuiltInName(
        self, byte: int, int: int
    ) -> loci.poi.hssf.record.NameRecord: ...
    def createCellXF(self) -> loci.poi.hssf.record.ExtendedFormatRecord: ...
    def createDrawingGroup(self) -> None: ...
    def createFormat(self, string: java.lang.String | str) -> int: ...
    def createName(self) -> loci.poi.hssf.record.NameRecord: ...
    def createNewFont(self) -> loci.poi.hssf.record.FontRecord: ...
    @typing.overload
    @staticmethod
    def createWorkbook() -> Workbook: ...
    @typing.overload
    @staticmethod
    def createWorkbook(list: java.util.List) -> Workbook: ...
    def doesContainsSheetName(
        self, string: java.lang.String | str, int: int
    ) -> bool: ...
    def findFirstRecordBySid(self, short: int) -> loci.poi.hssf.record.Record: ...
    def findFirstRecordLocBySid(self, short: int) -> int: ...
    def findNextRecordBySid(
        self, short: int, int: int
    ) -> loci.poi.hssf.record.Record: ...
    def findSheetNameFromExternSheet(self, short: int) -> java.lang.String: ...
    def getBSERecord(self, int: int) -> loci.poi.ddf.EscherBSERecord: ...
    def getBackupRecord(self) -> loci.poi.hssf.record.BackupRecord: ...
    def getCustomPalette(self) -> loci.poi.hssf.record.PaletteRecord: ...
    def getDrawingManager(self) -> DrawingManager2: ...
    def getExFormatAt(self, int: int) -> loci.poi.hssf.record.ExtendedFormatRecord: ...
    def getFileSharing(self) -> loci.poi.hssf.record.FileSharingRecord: ...
    def getFontRecordAt(self, int: int) -> loci.poi.hssf.record.FontRecord: ...
    def getFormat(self, string: java.lang.String | str, boolean: bool) -> int: ...
    def getFormats(self) -> java.util.ArrayList: ...
    def getNameRecord(self, int: int) -> loci.poi.hssf.record.NameRecord: ...
    def getNumExFormats(self) -> int: ...
    def getNumNames(self) -> int: ...
    def getNumRecords(self) -> int: ...
    def getNumSheets(self) -> int: ...
    def getNumberOfFontRecords(self) -> int: ...
    def getRecords(self) -> java.util.List: ...
    def getSSTString(self, int: int) -> loci.poi.hssf.record.UnicodeString: ...
    def getSheetIndex(self, string: java.lang.String | str) -> int: ...
    def getSheetIndexFromExternSheetIndex(self, int: int) -> int: ...
    def getSheetName(self, int: int) -> java.lang.String: ...
    def getSheetReferences(self) -> loci.poi.hssf.util.SheetReferences: ...
    def getSize(self) -> int: ...
    def getSpecificBuiltinRecord(
        self, byte: int, int: int
    ) -> loci.poi.hssf.record.NameRecord: ...
    def getWindowOne(self) -> loci.poi.hssf.record.WindowOneRecord: ...
    def getWriteAccess(self) -> loci.poi.hssf.record.WriteAccessRecord: ...
    def getWriteProtect(self) -> loci.poi.hssf.record.WriteProtectRecord: ...
    def insertSST(self) -> None: ...
    def isUsing1904DateWindowing(self) -> bool: ...
    def removeBuiltinRecord(self, byte: int, int: int) -> None: ...
    def removeName(self, int: int) -> None: ...
    def removeSheet(self, int: int) -> None: ...
    def serialize(
        self, int: int, byteArray: list[int] | jpype.JArray | bytes
    ) -> int: ...
    def setSheetBof(self, int: int, int2: int) -> None: ...
    @typing.overload
    def setSheetName(self, int: int, string: java.lang.String | str) -> None: ...
    @typing.overload
    def setSheetName(
        self, int: int, string: java.lang.String | str, short: int
    ) -> None: ...
    def setSheetOrder(self, string: java.lang.String | str, int: int) -> None: ...
    def unwriteProtectWorkbook(self) -> None: ...
    def writeProtectWorkbook(
        self, string: java.lang.String | str, string2: java.lang.String | str
    ) -> None: ...

class CommentShape(TextboxShape):
    def __init__(self, hSSFComment: loci.poi.hssf.usermodel.HSSFComment, int: int): ...
    def getNoteRecord(self) -> loci.poi.hssf.record.NoteRecord: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("loci.poi.hssf.model")``.

    AbstractShape: type[AbstractShape]
    CommentShape: type[CommentShape]
    ConvertAnchor: type[ConvertAnchor]
    DrawingManager: type[DrawingManager]
    DrawingManager2: type[DrawingManager2]
    FormulaParser: type[FormulaParser]
    LineShape: type[LineShape]
    Model: type[Model]
    PictureShape: type[PictureShape]
    PolygonShape: type[PolygonShape]
    Sheet: type[Sheet]
    SimpleFilledShape: type[SimpleFilledShape]
    TextboxShape: type[TextboxShape]
    Workbook: type[Workbook]
    WorkbookRecordList: type[WorkbookRecordList]
