import typing
from typing import Protocol

import java.awt
import java.io
import java.lang
import javax.xml.transform.stream
import jpype
import jpype.protocol
import ome.xml.model
import ome.xml.model.enums
import org.w3c.dom
import org.w3c.dom.ls

class OmeValidator:
    JAXP_SCHEMA_LANGUAGE: typing.ClassVar[java.lang.String] = ...
    W3C_XML_SCHEMA: typing.ClassVar[java.lang.String] = ...
    JAXP_SCHEMA_SOURCE: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    @typing.overload
    def isValidFile(
        self,
        file: java.io.File | jpype.protocol.SupportsPath,
        file2: java.io.File | jpype.protocol.SupportsPath,
    ) -> bool: ...
    @typing.overload
    def isValidFile(
        self,
        file: java.io.File | jpype.protocol.SupportsPath,
        streamSourceArray: list[javax.xml.transform.stream.StreamSource] | jpype.JArray,
    ) -> bool: ...
    @typing.overload
    def parseFile(
        self, file: java.io.File | jpype.protocol.SupportsPath
    ) -> org.w3c.dom.Document: ...
    @typing.overload
    def parseFile(
        self,
        file: java.io.File | jpype.protocol.SupportsPath,
        file2: java.io.File | jpype.protocol.SupportsPath,
    ) -> org.w3c.dom.Document: ...
    def parseFileWithStreamArray(
        self,
        file: java.io.File | jpype.protocol.SupportsPath,
        streamSourceArray: list[javax.xml.transform.stream.StreamSource] | jpype.JArray,
    ) -> org.w3c.dom.Document: ...
    def parseFileWithStreamArrayToSdtErr(
        self,
        file: java.io.File | jpype.protocol.SupportsPath,
        streamSourceArray: list[javax.xml.transform.stream.StreamSource] | jpype.JArray,
    ) -> org.w3c.dom.Document: ...
    @typing.overload
    def validateFile(
        self,
        file: java.io.File | jpype.protocol.SupportsPath,
        file2: java.io.File | jpype.protocol.SupportsPath,
    ) -> None: ...
    @typing.overload
    def validateFile(
        self,
        file: java.io.File | jpype.protocol.SupportsPath,
        streamSourceArray: list[javax.xml.transform.stream.StreamSource] | jpype.JArray,
    ) -> None: ...
    def validateFileToStdError(
        self,
        file: java.io.File | jpype.protocol.SupportsPath,
        streamSourceArray: list[javax.xml.transform.stream.StreamSource] | jpype.JArray,
    ) -> None: ...

class SchemaResolver(org.w3c.dom.ls.LSResourceResolver):
    def __init__(self): ...
    def resolveResource(
        self,
        string: java.lang.String | str,
        string2: java.lang.String | str,
        string3: java.lang.String | str,
        string4: java.lang.String | str,
        string5: java.lang.String | str,
    ) -> org.w3c.dom.ls.LSInput: ...

class XMLMockObjects:
    DEFAULT_COLOR: typing.ClassVar[java.awt.Color] = ...
    LIGHTSOURCE_POWER: typing.ClassVar[float] = ...
    COMPONENT_MODEL: typing.ClassVar[java.lang.String] = ...
    COMPONENT_MANUFACTURER: typing.ClassVar[java.lang.String] = ...
    COMPONENT_SERIAL_NUMBER: typing.ClassVar[java.lang.String] = ...
    COMPONENT_LOT_NUMBER: typing.ClassVar[java.lang.String] = ...
    LASER_TYPE: typing.ClassVar[ome.xml.model.enums.LaserType] = ...
    ARC_TYPE: typing.ClassVar[ome.xml.model.enums.ArcType] = ...
    FILAMENT_TYPE: typing.ClassVar[ome.xml.model.enums.FilamentType] = ...
    DETECTOR_TYPE: typing.ClassVar[ome.xml.model.enums.DetectorType] = ...
    CORRECTION: typing.ClassVar[ome.xml.model.enums.Correction] = ...
    IMMERSION: typing.ClassVar[ome.xml.model.enums.Immersion] = ...
    FILTER_TYPE: typing.ClassVar[ome.xml.model.enums.FilterType] = ...
    MICROSCOPE_TYPE: typing.ClassVar[ome.xml.model.enums.MicroscopeType] = ...
    EXPERIMENT_TYPE: typing.ClassVar[ome.xml.model.enums.ExperimentType] = ...
    MICROBEAM_MANIPULATION_TYPE: typing.ClassVar[
        ome.xml.model.enums.MicrobeamManipulationType
    ] = ...
    BINNING: typing.ClassVar[ome.xml.model.enums.Binning] = ...
    MEDIUM: typing.ClassVar[ome.xml.model.enums.Medium] = ...
    LASER_MEDIUM: typing.ClassVar[ome.xml.model.enums.LaserMedium] = ...
    SIZE_X: typing.ClassVar[int] = ...
    SIZE_Y: typing.ClassVar[int] = ...
    SIZE_Z: typing.ClassVar[int] = ...
    SIZE_C: typing.ClassVar[int] = ...
    SIZE_T: typing.ClassVar[int] = ...
    BYTES_PER_PIXEL: typing.ClassVar[int] = ...
    ROWS: typing.ClassVar[int] = ...
    COLUMNS: typing.ClassVar[int] = ...
    FIELDS: typing.ClassVar[int] = ...
    LIGHT_SOURCES: typing.ClassVar[typing.MutableSequence[java.lang.String]] = ...
    SHAPES: typing.ClassVar[typing.MutableSequence[java.lang.String]] = ...
    ANNOTATIONS: typing.ClassVar[typing.MutableSequence[java.lang.String]] = ...
    ROW_NAMING_CONVENTION: typing.ClassVar[ome.xml.model.enums.NamingConvention] = ...
    COLUMN_NAMING_CONVENTION: typing.ClassVar[
        ome.xml.model.enums.NamingConvention
    ] = ...
    DIMENSION_ORDER: typing.ClassVar[ome.xml.model.enums.DimensionOrder] = ...
    PIXEL_TYPE: typing.ClassVar[ome.xml.model.enums.PixelType] = ...
    NUMBER_OF_DECTECTORS: typing.ClassVar[int] = ...
    NUMBER_OF_OBJECTIVES: typing.ClassVar[int] = ...
    NUMBER_OF_FILTERS: typing.ClassVar[int] = ...
    NUMBER_OF_DICHROICS: typing.ClassVar[int] = ...
    POINTS: typing.ClassVar[java.lang.String] = ...
    TIME: typing.ClassVar[java.lang.String] = ...
    CUT_IN: typing.ClassVar[float] = ...
    CUT_OUT: typing.ClassVar[float] = ...
    def __init__(self): ...
    def createAnnotatedImage(self) -> ome.xml.model.OME: ...
    def createAnnotation(
        self,
        string: java.lang.String | str,
        oMEModelObject: ome.xml.model.OMEModelObject,
        int: int,
    ) -> ome.xml.model.Annotation: ...
    def createBasicPlate(self, int: int) -> ome.xml.model.Plate: ...
    def createBasicPlateWithReagent(self) -> ome.xml.model.OME: ...
    def createBinData(
        self, int: int, int2: int, int3: int
    ) -> ome.xml.model.BinData: ...
    def createBinaryFile(self) -> ome.xml.model.BinaryFile: ...
    def createChannel(self, int: int) -> ome.xml.model.Channel: ...
    def createDataset(self, int: int) -> ome.xml.model.Dataset: ...
    def createDetector(self, int: int) -> ome.xml.model.Detector: ...
    def createDetectorSettings(self, int: int) -> ome.xml.model.DetectorSettings: ...
    def createDichroic(self, int: int) -> ome.xml.model.Dichroic: ...
    def createExperiment(self, int: int) -> ome.xml.model.Experiment: ...
    def createExperimentWithMicrobeam(self, int: int) -> ome.xml.model.Experiment: ...
    def createExperimenter(self, int: int) -> ome.xml.model.Experimenter: ...
    def createFilter(
        self, int: int, double: float, double2: float
    ) -> ome.xml.model.Filter: ...
    def createFilterSet(self, int: int) -> ome.xml.model.FilterSet: ...
    def createFullPopulatedPlate(self, int: int) -> ome.xml.model.OME: ...
    @typing.overload
    def createImage(self, int: int) -> ome.xml.model.Image: ...
    @typing.overload
    def createImage(self, int: int, boolean: bool) -> ome.xml.model.Image: ...
    @typing.overload
    def createImage(self) -> ome.xml.model.OME: ...
    @typing.overload
    def createImage(self, boolean: bool) -> ome.xml.model.OME: ...
    def createImageEnvironment(self) -> ome.xml.model.ImagingEnvironment: ...
    def createImageWithAcquisitionData(self) -> ome.xml.model.OME: ...
    def createImageWithAnnotatedAcquisitionData(self) -> ome.xml.model.OME: ...
    def createImageWithExperiment(
        self, int: int, boolean: bool, experiment: ome.xml.model.Experiment
    ) -> ome.xml.model.Image: ...
    def createImageWithROI(self) -> ome.xml.model.OME: ...
    def createInstrument(self, boolean: bool) -> ome.xml.model.Instrument: ...
    def createLightPath(self) -> ome.xml.model.LightPath: ...
    def createLightSource(
        self, string: java.lang.String | str, int: int
    ) -> ome.xml.model.LightSource: ...
    def createLightSourceSettings(
        self, int: int
    ) -> ome.xml.model.LightSourceSettings: ...
    def createMicrobeamManipulation(
        self, int: int
    ) -> ome.xml.model.MicrobeamManipulation: ...
    def createMicroscope(self) -> ome.xml.model.Microscope: ...
    def createObjective(self, int: int) -> ome.xml.model.Objective: ...
    def createObjectiveSettings(self, int: int) -> ome.xml.model.ObjectiveSettings: ...
    def createPlane(self, int: int, int2: int, int3: int) -> ome.xml.model.Plane: ...
    @typing.overload
    def createPlate(self, int: int, int2: int, int3: int) -> ome.xml.model.Plate: ...
    @typing.overload
    def createPlate(
        self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int
    ) -> ome.xml.model.Plate: ...
    @typing.overload
    def createPlate(
        self,
        int: int,
        int2: int,
        int3: int,
        int4: int,
        int5: int,
        int6: int,
        boolean: bool,
    ) -> ome.xml.model.Plate: ...
    @typing.overload
    def createPlate(
        self,
        int: int,
        int2: int,
        int3: int,
        int4: int,
        int5: int,
        int6: int,
        int7: int,
        int8: int,
    ) -> ome.xml.model.Plate: ...
    @typing.overload
    def createPlate(
        self,
        int: int,
        int2: int,
        int3: int,
        int4: int,
        int5: int,
        int6: int,
        int7: int,
        int8: int,
        boolean: bool,
    ) -> ome.xml.model.Plate: ...
    @typing.overload
    def createPopulatedPlate(self, int: int) -> ome.xml.model.OME: ...
    @typing.overload
    def createPopulatedPlate(self, int: int, int2: int) -> ome.xml.model.OME: ...
    @typing.overload
    def createPopulatedPlate(
        self, int: int, int2: int, int3: int, int4: int, int5: int
    ) -> ome.xml.model.OME: ...
    @typing.overload
    def createPopulatedPlate(
        self, int: int, int2: int, int3: int, int4: int, int5: int, boolean: bool
    ) -> ome.xml.model.OME: ...
    @typing.overload
    def createPopulatedScreen(self) -> ome.xml.model.OME: ...
    @typing.overload
    def createPopulatedScreen(
        self, int: int, int2: int, int3: int, int4: int, int5: int
    ) -> ome.xml.model.OME: ...
    @typing.overload
    def createPopulatedScreen(
        self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int
    ) -> ome.xml.model.OME: ...
    @typing.overload
    def createPopulatedScreen(
        self,
        int: int,
        int2: int,
        int3: int,
        int4: int,
        int5: int,
        int6: int,
        boolean: bool,
    ) -> ome.xml.model.OME: ...
    def createProject(self, int: int) -> ome.xml.model.Project: ...
    def createROI(
        self, int: int, int2: int, int3: int, int4: int
    ) -> ome.xml.model.ROI: ...
    def createReagent(self, int: int) -> ome.xml.model.Reagent: ...
    def createScreen(self, int: int) -> ome.xml.model.Screen: ...
    def createShape(
        self, int: int, string: java.lang.String | str, int2: int, int3: int, int4: int
    ) -> ome.xml.model.Shape: ...
    def createStageLabel(self) -> ome.xml.model.StageLabel: ...
    def getRoot(self) -> ome.xml.model.OME: ...

class XMLWriter:
    ID_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
    NAME_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
    DIMENSION_ORDER_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
    PIXELS_TYPE_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
    SIZE_C_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
    SIZE_T_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
    SIZE_Z_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
    SIZE_X_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
    SIZE_Y_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
    COMPRESSION_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
    BIG_ENDIAN_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
    LENGTH_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
    OME_TAG: typing.ClassVar[java.lang.String] = ...
    IMAGE_TAG: typing.ClassVar[java.lang.String] = ...
    PIXELS_TAG: typing.ClassVar[java.lang.String] = ...
    BIN_DATA_TAG: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    @typing.overload
    def writeFile(
        self, file: java.io.File | jpype.protocol.SupportsPath, oME: ome.xml.model.OME
    ) -> None: ...
    @typing.overload
    def writeFile(
        self,
        file: java.io.File | jpype.protocol.SupportsPath,
        oME: ome.xml.model.OME,
        boolean: bool,
    ) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("ome.specification")``.

    OmeValidator: type[OmeValidator]
    SchemaResolver: type[SchemaResolver]
    XMLMockObjects: type[XMLMockObjects]
    XMLWriter: type[XMLWriter]
