import typing
from typing import Protocol

import java.lang
import java.util
import loci.common
import loci.formats
import ome.units.quantity
import ome.xml.model.primitives

class DicomAttribute(java.lang.Enum["DicomAttribute"]):
    FILE_META_INFO_GROUP_LENGTH: typing.ClassVar[DicomAttribute] = ...
    FILE_META_INFO_VERSION: typing.ClassVar[DicomAttribute] = ...
    MEDIA_SOP_CLASS_UID: typing.ClassVar[DicomAttribute] = ...
    MEDIA_SOP_INSTANCE_UID: typing.ClassVar[DicomAttribute] = ...
    TRANSFER_SYNTAX_UID: typing.ClassVar[DicomAttribute] = ...
    IMPLEMENTATION_UID: typing.ClassVar[DicomAttribute] = ...
    IMPLEMENTATION_VERSION: typing.ClassVar[DicomAttribute] = ...
    SOURCE_APPLICATION: typing.ClassVar[DicomAttribute] = ...
    SPECIFIC_CHARSET: typing.ClassVar[DicomAttribute] = ...
    IMAGE_TYPE: typing.ClassVar[DicomAttribute] = ...
    RECOGNITION_CODE: typing.ClassVar[DicomAttribute] = ...
    CREATION_DATE: typing.ClassVar[DicomAttribute] = ...
    CREATION_TIME: typing.ClassVar[DicomAttribute] = ...
    INSTANCE_CREATOR: typing.ClassVar[DicomAttribute] = ...
    SOP_CLASS_UID: typing.ClassVar[DicomAttribute] = ...
    SOP_INSTANCE_UID: typing.ClassVar[DicomAttribute] = ...
    RELATED_SOP_CLASS_UID: typing.ClassVar[DicomAttribute] = ...
    ORIGINAL_SOP_CLASS_UID: typing.ClassVar[DicomAttribute] = ...
    STUDY_DATE: typing.ClassVar[DicomAttribute] = ...
    SERIES_DATE: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_DATE: typing.ClassVar[DicomAttribute] = ...
    CONTENT_DATE: typing.ClassVar[DicomAttribute] = ...
    OVERLAY_DATE: typing.ClassVar[DicomAttribute] = ...
    CURVE_DATE: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_TIMESTAMP: typing.ClassVar[DicomAttribute] = ...
    STUDY_TIME: typing.ClassVar[DicomAttribute] = ...
    SERIES_TIME: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_TIME: typing.ClassVar[DicomAttribute] = ...
    CONTENT_TIME: typing.ClassVar[DicomAttribute] = ...
    OVERLAY_TIME: typing.ClassVar[DicomAttribute] = ...
    CURVE_TIME: typing.ClassVar[DicomAttribute] = ...
    DATASET_SUBTYPE: typing.ClassVar[DicomAttribute] = ...
    ACCESSION_NUMBER: typing.ClassVar[DicomAttribute] = ...
    QUERY_LEVEL: typing.ClassVar[DicomAttribute] = ...
    RETRIEVE_TITLE: typing.ClassVar[DicomAttribute] = ...
    INSTANCE_AVAILABILITY: typing.ClassVar[DicomAttribute] = ...
    FAILED_SOP_UID_LIST: typing.ClassVar[DicomAttribute] = ...
    MODALITY: typing.ClassVar[DicomAttribute] = ...
    MODALITIES_IN_STUDY: typing.ClassVar[DicomAttribute] = ...
    CLASSES_IN_STUDY: typing.ClassVar[DicomAttribute] = ...
    CONVERSION_TYPE: typing.ClassVar[DicomAttribute] = ...
    PRESENTATION_INTENT_TYPE: typing.ClassVar[DicomAttribute] = ...
    MANUFACTURER: typing.ClassVar[DicomAttribute] = ...
    INSTITUTION_NAME: typing.ClassVar[DicomAttribute] = ...
    INSTITUTION_ADDRESS: typing.ClassVar[DicomAttribute] = ...
    INSTITUTION_CODE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERRING_PHYSICIAN_NAME: typing.ClassVar[DicomAttribute] = ...
    REFERRING_PHYSICIAN_ADDRESS: typing.ClassVar[DicomAttribute] = ...
    REFERRING_PHYSICIAN_TELEPHONE: typing.ClassVar[DicomAttribute] = ...
    REFERRING_PHYSICIAN_ID: typing.ClassVar[DicomAttribute] = ...
    CODE_VALUE: typing.ClassVar[DicomAttribute] = ...
    CODING_SCHEME_DESIGNATOR: typing.ClassVar[DicomAttribute] = ...
    CODING_SCHEME_VERSION: typing.ClassVar[DicomAttribute] = ...
    CODE_MEANING: typing.ClassVar[DicomAttribute] = ...
    MAPPING_RESOURCE: typing.ClassVar[DicomAttribute] = ...
    CONTEXT_GROUP_VERSION: typing.ClassVar[DicomAttribute] = ...
    CONTEXT_GROUP_LOCAL_VERSION: typing.ClassVar[DicomAttribute] = ...
    CONTEXT_GROUP_EXTENSION_FLAG: typing.ClassVar[DicomAttribute] = ...
    CODING_SCHEME_UID: typing.ClassVar[DicomAttribute] = ...
    CONTEXT_GROUP_EXTENSION_CREATOR: typing.ClassVar[DicomAttribute] = ...
    CONTEXT_ID: typing.ClassVar[DicomAttribute] = ...
    CODING_SCHEME_ID: typing.ClassVar[DicomAttribute] = ...
    CODING_SCHEME_REGISTRY: typing.ClassVar[DicomAttribute] = ...
    CODING_SCHEME_EXTERNAL_ID: typing.ClassVar[DicomAttribute] = ...
    CODING_SCHEME_NAME: typing.ClassVar[DicomAttribute] = ...
    RESPONSIBLE_ORGANIZATION: typing.ClassVar[DicomAttribute] = ...
    TIMEZONE_OFFSET_UTC: typing.ClassVar[DicomAttribute] = ...
    STATION_NAME: typing.ClassVar[DicomAttribute] = ...
    STUDY_DESCRIPTION: typing.ClassVar[DicomAttribute] = ...
    PROCEDURE_CODE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    SERIES_DESCRIPTION: typing.ClassVar[DicomAttribute] = ...
    INSTITUTIONAL_DEPARTMENT_NAME: typing.ClassVar[DicomAttribute] = ...
    PHYSICIANS: typing.ClassVar[DicomAttribute] = ...
    PHYSICIANS_ID: typing.ClassVar[DicomAttribute] = ...
    PHYSICIAN_NAME: typing.ClassVar[DicomAttribute] = ...
    PHYSICIAN_ID: typing.ClassVar[DicomAttribute] = ...
    PHYSICIAN_READING: typing.ClassVar[DicomAttribute] = ...
    PHYSICIAN_READING_ID: typing.ClassVar[DicomAttribute] = ...
    OPERATOR_NAME: typing.ClassVar[DicomAttribute] = ...
    OPERATOR_ID: typing.ClassVar[DicomAttribute] = ...
    ADMITTING_DIAGNOSES_DESCRIPTION: typing.ClassVar[DicomAttribute] = ...
    ADMITTING_DIAGNOSES_CODE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    MANUFACTURER_MODEL_NAME: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_RESULTS_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_STUDY_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_PERFORMED_PROCEDURE_STEP: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_SERIES_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_PATIENT_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_VISIT_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_OVERLAY_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_WAVEFORM_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_IMAGE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_CURVE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_INSTANCE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_SOP_CLASS_UID: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_SOP_INSTANCE_UID: typing.ClassVar[DicomAttribute] = ...
    SOP_CLASSES_SUPPORTED: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_FRAME_NUMBER: typing.ClassVar[DicomAttribute] = ...
    TRANSACTION_UID: typing.ClassVar[DicomAttribute] = ...
    FAILURE_REASON: typing.ClassVar[DicomAttribute] = ...
    FAILED_SOP_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_SOP_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    STUDIES_WITH_REFERENCED_INSTANCES: typing.ClassVar[DicomAttribute] = ...
    RELATED_SERIES_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    DERIVATION_DESCRIPTION: typing.ClassVar[DicomAttribute] = ...
    SOURCE_IMAGE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    STAGE_NAME: typing.ClassVar[DicomAttribute] = ...
    STAGE_NUMBER: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_STAGES: typing.ClassVar[DicomAttribute] = ...
    VIEW_NAME: typing.ClassVar[DicomAttribute] = ...
    VIEW_NUMBER: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_EVENT_TIMERS: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_VIEWS_STAGE: typing.ClassVar[DicomAttribute] = ...
    EVENT_ELAPSED_TIME: typing.ClassVar[DicomAttribute] = ...
    EVENT_TIMER_NAME: typing.ClassVar[DicomAttribute] = ...
    START_TRIM: typing.ClassVar[DicomAttribute] = ...
    STOP_TRIM: typing.ClassVar[DicomAttribute] = ...
    RECOMMENDED_DISPLAY_FRAMERATE: typing.ClassVar[DicomAttribute] = ...
    ANATOMIC_REGION_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    ANATOMIC_REGION_MODIFIER_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    PRIMARY_ANATOMIC_STRUCTURE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    ANATOMIC_STRUCTURE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    PRIMARY_ANATOMIC_STRUCTURE_MODIFIER: typing.ClassVar[DicomAttribute] = ...
    TRANSDUCER_POSITION_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    TRANSDUCER_POSITION_MODIFIER_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    TRANSDUCER_ORIENTATION_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    TRANSDUCER_ORIENTATION_MODIFIER: typing.ClassVar[DicomAttribute] = ...
    ALTERNATE_REPRESENTATION_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    FRAME_TYPE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_IMAGE_EVIDENCE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_RAW_DATA_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    CREATOR_VERSION_UID: typing.ClassVar[DicomAttribute] = ...
    DERIVATION_IMAGE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    SOURCE_IMAGE_EVIDENCE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    PIXEL_PRESENTATION: typing.ClassVar[DicomAttribute] = ...
    VOLUMETRIC_PROPERTIES: typing.ClassVar[DicomAttribute] = ...
    VOLUME_BASED_CALCULATION_TECHNIQUE: typing.ClassVar[DicomAttribute] = ...
    COMPLEX_IMAGE_COMPONENT: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_CONTRAST: typing.ClassVar[DicomAttribute] = ...
    DERIVATION_CODE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCE_GRAYSCALE_PRESENTATION_STATE: typing.ClassVar[DicomAttribute] = ...
    PATIENT_NAME: typing.ClassVar[DicomAttribute] = ...
    PATIENT_ID: typing.ClassVar[DicomAttribute] = ...
    ISSUER_OF_PATIENT_ID: typing.ClassVar[DicomAttribute] = ...
    PATIENT_BIRTH_DATE: typing.ClassVar[DicomAttribute] = ...
    PATIENT_BIRTH_TIME: typing.ClassVar[DicomAttribute] = ...
    PATIENT_SEX: typing.ClassVar[DicomAttribute] = ...
    PATIENT_INSURANCE_PLAN_CODE: typing.ClassVar[DicomAttribute] = ...
    PATIENT_PRIMARY_LANGUAGE_CODE: typing.ClassVar[DicomAttribute] = ...
    PATIENT_PRIMARY_LANGUAGE_MODIFIER: typing.ClassVar[DicomAttribute] = ...
    OTHER_PATIENT_IDS: typing.ClassVar[DicomAttribute] = ...
    OTHER_PATIENT_NAMES: typing.ClassVar[DicomAttribute] = ...
    PATIENT_BIRTH_NAME: typing.ClassVar[DicomAttribute] = ...
    PATIENT_AGE: typing.ClassVar[DicomAttribute] = ...
    PATIENT_SIZE: typing.ClassVar[DicomAttribute] = ...
    PATIENT_WEIGHT: typing.ClassVar[DicomAttribute] = ...
    PATIENT_ADDRESS: typing.ClassVar[DicomAttribute] = ...
    PATIENT_MOTHER_BIRTH_NAME: typing.ClassVar[DicomAttribute] = ...
    MILITARY_RANK: typing.ClassVar[DicomAttribute] = ...
    BRANCH_OF_SERVICE: typing.ClassVar[DicomAttribute] = ...
    MEDICAL_RECORD_LOCATOR: typing.ClassVar[DicomAttribute] = ...
    MEDICAL_ALERTS: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_ALLERGIES: typing.ClassVar[DicomAttribute] = ...
    COUNTRY_OF_RESIDENCE: typing.ClassVar[DicomAttribute] = ...
    REGION_OF_RESIDENCE: typing.ClassVar[DicomAttribute] = ...
    PATIENT_TELEPHONE_NUMBER: typing.ClassVar[DicomAttribute] = ...
    ETHNIC_GROUP: typing.ClassVar[DicomAttribute] = ...
    OCCUPATION: typing.ClassVar[DicomAttribute] = ...
    SMOKING_STATUS: typing.ClassVar[DicomAttribute] = ...
    ADDITIONAL_PATIENT_HISTORY: typing.ClassVar[DicomAttribute] = ...
    PREGNANCY_STATUS: typing.ClassVar[DicomAttribute] = ...
    LAST_MENSTRUAL_DATE: typing.ClassVar[DicomAttribute] = ...
    PATIENT_RELIGIOUS_PREFERENCE: typing.ClassVar[DicomAttribute] = ...
    PATIENT_COMMENTS: typing.ClassVar[DicomAttribute] = ...
    CLINICAL_TRIAL_SPONSOR_NAME: typing.ClassVar[DicomAttribute] = ...
    CLINICAL_TRIAL_PROTOCOL_ID: typing.ClassVar[DicomAttribute] = ...
    CLINICAL_TRIAL_PROTOCOL_NAME: typing.ClassVar[DicomAttribute] = ...
    CLINICAL_TRIAL_SITE_ID: typing.ClassVar[DicomAttribute] = ...
    CLINICAL_TRIAL_SITE_NAME: typing.ClassVar[DicomAttribute] = ...
    CLINICAL_TRIAL_SUBJECT_ID: typing.ClassVar[DicomAttribute] = ...
    CLINICAL_TRIAL_SUBJECT_READING_ID: typing.ClassVar[DicomAttribute] = ...
    CLINICAL_TRIAL_TIME_POINT_ID: typing.ClassVar[DicomAttribute] = ...
    CLINICAL_TRIAL_TIME_POINT_DESCRIPTION: typing.ClassVar[DicomAttribute] = ...
    CLINICAL_TRIAL_COORDINATING_CENTER: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_BOLUS_AGENT: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_BOLUS_AGENT_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_BOLUS_ADMIN_ROUTE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    BODY_PART_EXAMINED: typing.ClassVar[DicomAttribute] = ...
    SCANNING_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    SEQUENCE_VARIANT: typing.ClassVar[DicomAttribute] = ...
    SCAN_OPTIONS: typing.ClassVar[DicomAttribute] = ...
    MR_ACQUISITION_TYPE: typing.ClassVar[DicomAttribute] = ...
    SEQUENCE_NAME: typing.ClassVar[DicomAttribute] = ...
    ANGIO_FLAG: typing.ClassVar[DicomAttribute] = ...
    INTERVENTION_DRUG_INFORMATION_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    INTERVENTION_DRUG_STOP_TIME: typing.ClassVar[DicomAttribute] = ...
    INTERVENTION_DRUG_DOSE: typing.ClassVar[DicomAttribute] = ...
    INTERVENTION_DRUG_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    ADDITIONAL_DRUG_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    RADIOPHARMACEUTICAL: typing.ClassVar[DicomAttribute] = ...
    INTERVENTION_DRUG_NAME: typing.ClassVar[DicomAttribute] = ...
    INTERVENTION_DRUG_START_TIME: typing.ClassVar[DicomAttribute] = ...
    INTERVENTION_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    INTERVENTION_STATUS: typing.ClassVar[DicomAttribute] = ...
    INTERVENTION_DESCRIPTION: typing.ClassVar[DicomAttribute] = ...
    CINE_RATE: typing.ClassVar[DicomAttribute] = ...
    SLICE_THICKNESS: typing.ClassVar[DicomAttribute] = ...
    KVP: typing.ClassVar[DicomAttribute] = ...
    COUNTS_ACCUMULATED: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_TERMINATION_CONDITION: typing.ClassVar[DicomAttribute] = ...
    EFFECTIVE_DURATION: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_START_CONDITION: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_START_CONDITION_DATA: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_TERMINATION_CONDITION_DATA: typing.ClassVar[DicomAttribute] = ...
    REPETITION_TIME: typing.ClassVar[DicomAttribute] = ...
    ECHO_TIME: typing.ClassVar[DicomAttribute] = ...
    INVERSION_TIME: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_AVERAGES: typing.ClassVar[DicomAttribute] = ...
    IMAGING_FREQUENCY: typing.ClassVar[DicomAttribute] = ...
    IMAGED_NUCLEUS: typing.ClassVar[DicomAttribute] = ...
    ECHO_NUMBER: typing.ClassVar[DicomAttribute] = ...
    MAGNETIC_FIELD_STRENGTH: typing.ClassVar[DicomAttribute] = ...
    SLICE_SPACING: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_PHASE_ENCODING_STEPS: typing.ClassVar[DicomAttribute] = ...
    DATA_COLLECTION_DIAMETER: typing.ClassVar[DicomAttribute] = ...
    ECHO_TRAIN_LENGTH: typing.ClassVar[DicomAttribute] = ...
    PERCENT_SAMPLING: typing.ClassVar[DicomAttribute] = ...
    PERCENT_PHASE_FOV: typing.ClassVar[DicomAttribute] = ...
    PIXEL_BANDWIDTH: typing.ClassVar[DicomAttribute] = ...
    DEVICE_SERIAL_NUMBER: typing.ClassVar[DicomAttribute] = ...
    PLATE_ID: typing.ClassVar[DicomAttribute] = ...
    SECONDARY_CAPTURE_DEVICE_ID: typing.ClassVar[DicomAttribute] = ...
    HARDCOPY_CREATION_DEVICE_ID: typing.ClassVar[DicomAttribute] = ...
    DATE_OF_SECONDARY_CAPTURE: typing.ClassVar[DicomAttribute] = ...
    TIME_OF_SECONDARY_CAPTURE: typing.ClassVar[DicomAttribute] = ...
    SECONDARY_CAPTURE_DEVICE_MANUFACTURER: typing.ClassVar[DicomAttribute] = ...
    HARDCOPY_DEVICE_MANUFACTURER: typing.ClassVar[DicomAttribute] = ...
    SECONDARY_CAPTURE_DEVICE_MODEL_NAME: typing.ClassVar[DicomAttribute] = ...
    SECONDARY_CAPTURE_DEVICE_SOFTWARE_VERSION: typing.ClassVar[DicomAttribute] = ...
    HARDCOPY_DEVICE_SOFTWARE_VERSION: typing.ClassVar[DicomAttribute] = ...
    HARDCOPY_DEVICE_MODEL_NAME: typing.ClassVar[DicomAttribute] = ...
    SOFTWARE_VERSION: typing.ClassVar[DicomAttribute] = ...
    VIDEO_IMAGE_FORMAT_ACQUIRED: typing.ClassVar[DicomAttribute] = ...
    DIGITAL_IMAGE_FORMAT_ACQUIRED: typing.ClassVar[DicomAttribute] = ...
    PROTOCOL_NAME: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_BOLUS_ROUTE: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_BOLUS_VOLUME: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_BOLUS_START_TIME: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_BOLUS_STOP_TIME: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_BOLUS_TOTAL_DOSE: typing.ClassVar[DicomAttribute] = ...
    SYRINGE_COUNTS: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_FLOW_RATE: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_FLOW_DURATION: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_BOLUS_INGREDIENT: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_INGREDIENT_CONCENTRATION: typing.ClassVar[DicomAttribute] = ...
    SPATIAL_RESOLUTION: typing.ClassVar[DicomAttribute] = ...
    TRIGGER_TIME: typing.ClassVar[DicomAttribute] = ...
    TRIGGER_SOURCE_OR_TYPE: typing.ClassVar[DicomAttribute] = ...
    NOMINAL_INTERVAL: typing.ClassVar[DicomAttribute] = ...
    FRAME_TIME: typing.ClassVar[DicomAttribute] = ...
    FRAMING_TYPE: typing.ClassVar[DicomAttribute] = ...
    FRAME_TIME_VECTOR: typing.ClassVar[DicomAttribute] = ...
    FRAME_DELAY: typing.ClassVar[DicomAttribute] = ...
    IMAGE_TRIGGER_DELAY: typing.ClassVar[DicomAttribute] = ...
    MULTIPLEX_GROUP_TIME_OFFSET: typing.ClassVar[DicomAttribute] = ...
    TRIGGER_TIME_OFFSET: typing.ClassVar[DicomAttribute] = ...
    SYNCHRONIZATION_TRIGGER: typing.ClassVar[DicomAttribute] = ...
    SYNCHRONIZATION_CHANNEL: typing.ClassVar[DicomAttribute] = ...
    TRIGGER_SAMPLE_POSITION: typing.ClassVar[DicomAttribute] = ...
    RADIOPHARMACEUTICAL_ROUTE: typing.ClassVar[DicomAttribute] = ...
    RADIOPHARMACEUTICAL_VOLUME: typing.ClassVar[DicomAttribute] = ...
    RADIOPHARMACEUTICAL_START_TIME: typing.ClassVar[DicomAttribute] = ...
    RADIOPHARMACEUTICAL_STOP_TIME: typing.ClassVar[DicomAttribute] = ...
    RADIONUCLIDE_TOTAL_DOSE: typing.ClassVar[DicomAttribute] = ...
    RADIONUCLIDE_HALF_LIFE: typing.ClassVar[DicomAttribute] = ...
    RADIONUCLIDE_POSITRON_FRACTION: typing.ClassVar[DicomAttribute] = ...
    RADIOPHARMACEUTICAL_SPECIFIC_ACTIVITY: typing.ClassVar[DicomAttribute] = ...
    BEAT_REJECTION_FLAG: typing.ClassVar[DicomAttribute] = ...
    LOW_RR_VALUE: typing.ClassVar[DicomAttribute] = ...
    HIGH_RR_VALUE: typing.ClassVar[DicomAttribute] = ...
    INTERVALS_ACQUIRED: typing.ClassVar[DicomAttribute] = ...
    INTERVALS_REJECTED: typing.ClassVar[DicomAttribute] = ...
    PVC_REJECTION: typing.ClassVar[DicomAttribute] = ...
    SKIP_BEATS: typing.ClassVar[DicomAttribute] = ...
    HEART_RATE: typing.ClassVar[DicomAttribute] = ...
    CARDIAC_NUMBER_OF_IMAGES: typing.ClassVar[DicomAttribute] = ...
    TRIGGER_WINDOW: typing.ClassVar[DicomAttribute] = ...
    RECONSTRUCTION_DIAMETER: typing.ClassVar[DicomAttribute] = ...
    DISTANCE_SOURCE_TO_DETECTOR: typing.ClassVar[DicomAttribute] = ...
    DISTANCE_SOURCE_TO_PATIENT: typing.ClassVar[DicomAttribute] = ...
    ESTIMATED_RADIOGRAPHIC_MAG_FACTOR: typing.ClassVar[DicomAttribute] = ...
    GANTRY_DETECTOR_TILT: typing.ClassVar[DicomAttribute] = ...
    GANTRY_DETECTOR_SKEW: typing.ClassVar[DicomAttribute] = ...
    TABLE_HEIGHT: typing.ClassVar[DicomAttribute] = ...
    TABLE_TRAVERSE: typing.ClassVar[DicomAttribute] = ...
    TABLE_MOTION: typing.ClassVar[DicomAttribute] = ...
    TABLE_VERTICAL_INCREMENT: typing.ClassVar[DicomAttribute] = ...
    TABLE_LATERAL_INCREMENT: typing.ClassVar[DicomAttribute] = ...
    TABLE_LONGITUDINAL_INCREMENT: typing.ClassVar[DicomAttribute] = ...
    TABLE_ANGLE: typing.ClassVar[DicomAttribute] = ...
    TABLE_TYPE: typing.ClassVar[DicomAttribute] = ...
    ROTATION_DIRECTION: typing.ClassVar[DicomAttribute] = ...
    ANGULAR_POSITION: typing.ClassVar[DicomAttribute] = ...
    RADIAL_POSITION: typing.ClassVar[DicomAttribute] = ...
    SCAN_ARC: typing.ClassVar[DicomAttribute] = ...
    ANGULAR_STEP: typing.ClassVar[DicomAttribute] = ...
    CENTER_OF_ROTATION_OFFSET: typing.ClassVar[DicomAttribute] = ...
    FOV_SHAPE: typing.ClassVar[DicomAttribute] = ...
    FOV_DIMENSIONS: typing.ClassVar[DicomAttribute] = ...
    EXPOSURE_TIME: typing.ClassVar[DicomAttribute] = ...
    XRAY_TUBE_CURRENT: typing.ClassVar[DicomAttribute] = ...
    EXPOSURE: typing.ClassVar[DicomAttribute] = ...
    EXPOSURE_IN_UAS: typing.ClassVar[DicomAttribute] = ...
    AVERAGE_PULSE_WIDTH: typing.ClassVar[DicomAttribute] = ...
    RADIATION_SETTING: typing.ClassVar[DicomAttribute] = ...
    RECTIFICATION_TYPE: typing.ClassVar[DicomAttribute] = ...
    RADIATION_MODE: typing.ClassVar[DicomAttribute] = ...
    IMAGE_AREA_DOSE_PRODUCT: typing.ClassVar[DicomAttribute] = ...
    FILTER_TYPE: typing.ClassVar[DicomAttribute] = ...
    TYPE_OF_FILTERS: typing.ClassVar[DicomAttribute] = ...
    INTENSIFIER_SIZE: typing.ClassVar[DicomAttribute] = ...
    IMAGER_PIXEL_SPACING: typing.ClassVar[DicomAttribute] = ...
    GRID: typing.ClassVar[DicomAttribute] = ...
    GENERATOR_POWER: typing.ClassVar[DicomAttribute] = ...
    COLLIMATOR_GRID_NAME: typing.ClassVar[DicomAttribute] = ...
    COLLIMATOR_TYPE: typing.ClassVar[DicomAttribute] = ...
    FOCAL_DISTANCE: typing.ClassVar[DicomAttribute] = ...
    X_FOCUS_CENTER: typing.ClassVar[DicomAttribute] = ...
    Y_FOCUS_CENTER: typing.ClassVar[DicomAttribute] = ...
    FOCAL_SPOTS: typing.ClassVar[DicomAttribute] = ...
    ANODE_TARGET_MATERIAL: typing.ClassVar[DicomAttribute] = ...
    BODY_PART_THICKNESS: typing.ClassVar[DicomAttribute] = ...
    COMPRESSION_FORCE: typing.ClassVar[DicomAttribute] = ...
    DATE_OF_LAST_CALIBRATION: typing.ClassVar[DicomAttribute] = ...
    TIME_OF_LAST_CALIBRATION: typing.ClassVar[DicomAttribute] = ...
    CONVOLUTION_KERNEL: typing.ClassVar[DicomAttribute] = ...
    ACTUAL_FRAME_DURATION: typing.ClassVar[DicomAttribute] = ...
    COUNT_RATE: typing.ClassVar[DicomAttribute] = ...
    PREFERRED_PLAYBACK_SEQUENCING: typing.ClassVar[DicomAttribute] = ...
    RECEIVE_COIL_NAME: typing.ClassVar[DicomAttribute] = ...
    TRANSMIT_COIL_NAME: typing.ClassVar[DicomAttribute] = ...
    PLATE_TYPE: typing.ClassVar[DicomAttribute] = ...
    PHOSPHOR_TYPE: typing.ClassVar[DicomAttribute] = ...
    SCAN_VELOCITY: typing.ClassVar[DicomAttribute] = ...
    WHOLE_BODY_TECHNIQUE: typing.ClassVar[DicomAttribute] = ...
    SCAN_LENGTH: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_MATRIX: typing.ClassVar[DicomAttribute] = ...
    INPLANE_PHASE_ENCODING_DIRECTION: typing.ClassVar[DicomAttribute] = ...
    FLIP_ANGLE: typing.ClassVar[DicomAttribute] = ...
    VARIABLE_FLIP_ANGLE_FLAG: typing.ClassVar[DicomAttribute] = ...
    SAR: typing.ClassVar[DicomAttribute] = ...
    DB_DT: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_DEVICE_PROCESSING_DESCRIPTION: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_DEVICE_PROCESSING_CODE: typing.ClassVar[DicomAttribute] = ...
    CASSETTE_ORIENTATION: typing.ClassVar[DicomAttribute] = ...
    CASSETTE_SIZE: typing.ClassVar[DicomAttribute] = ...
    EXPOSURES_ON_PLATE: typing.ClassVar[DicomAttribute] = ...
    RELATIVE_XRAY_EXPOSURE: typing.ClassVar[DicomAttribute] = ...
    COLUMN_ANGULATION: typing.ClassVar[DicomAttribute] = ...
    TOMO_LAYER_HEIGHT: typing.ClassVar[DicomAttribute] = ...
    TOMO_ANGLE: typing.ClassVar[DicomAttribute] = ...
    TOMO_TIME: typing.ClassVar[DicomAttribute] = ...
    TOMO_TYPE: typing.ClassVar[DicomAttribute] = ...
    TOMO_CLASS: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_TOMOSYNTHESIS_SOURCE_IMAGES: typing.ClassVar[DicomAttribute] = ...
    POSITIONER_MOTION: typing.ClassVar[DicomAttribute] = ...
    POSITIONER_TYPE: typing.ClassVar[DicomAttribute] = ...
    POSITIONER_PRIMARY_ANGLE: typing.ClassVar[DicomAttribute] = ...
    POSITIONER_SECONDARY_ANGLE: typing.ClassVar[DicomAttribute] = ...
    POSITIONER_PRIMARY_ANGLE_INCREMENT: typing.ClassVar[DicomAttribute] = ...
    POSITIONER_SECONDARY_ANGLE_INCREMENT: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_PRIMARY_ANGLE: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_SECONDARY_ANGLE: typing.ClassVar[DicomAttribute] = ...
    SHUTTER_SHAPE: typing.ClassVar[DicomAttribute] = ...
    SHUTTER_LEFT_VERTICAL_EDGE: typing.ClassVar[DicomAttribute] = ...
    SHUTTER_RIGHT_VERTICAL_EDGE: typing.ClassVar[DicomAttribute] = ...
    SHUTTER_UPPER_HORIZONTAL_EDGE: typing.ClassVar[DicomAttribute] = ...
    SHUTTER_LOWER_HORIZONTAL_EDGE: typing.ClassVar[DicomAttribute] = ...
    CENTER_OF_CIRCULAR_SHUTTER: typing.ClassVar[DicomAttribute] = ...
    RADIUS_OF_CIRCULAR_SHUTTER: typing.ClassVar[DicomAttribute] = ...
    VERTICES_OF_POLYGONAL_SHUTTER: typing.ClassVar[DicomAttribute] = ...
    SHUTTER_PRESENTATION_VALUE: typing.ClassVar[DicomAttribute] = ...
    SHUTTER_OVERLAY_GROUP: typing.ClassVar[DicomAttribute] = ...
    COLLIMATOR_SHAPE: typing.ClassVar[DicomAttribute] = ...
    COLLIMATOR_LEFT_VERTICAL_EDGE: typing.ClassVar[DicomAttribute] = ...
    COLLIMATOR_RIGHT_VERTICAL_EDGE: typing.ClassVar[DicomAttribute] = ...
    COLLIMATOR_UPPER_HORIZONTAL_EDGE: typing.ClassVar[DicomAttribute] = ...
    COLLIMATOR_LOWER_HORIZONTAL_EDGE: typing.ClassVar[DicomAttribute] = ...
    CENTER_OF_CIRCULAR_COLLIMATOR: typing.ClassVar[DicomAttribute] = ...
    RADIUS_OF_CIRCULAR_COLLIMATOR: typing.ClassVar[DicomAttribute] = ...
    VERTICES_OF_POLYGONAL_COLLIMATOR: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_TIME_SYNCHRONIZED: typing.ClassVar[DicomAttribute] = ...
    TIME_SOURCE: typing.ClassVar[DicomAttribute] = ...
    TIME_DISTRIBUTION_PROTOCOL: typing.ClassVar[DicomAttribute] = ...
    NTP_SOURCE_ADDRESS: typing.ClassVar[DicomAttribute] = ...
    PAGE_NUMBER_VECTOR: typing.ClassVar[DicomAttribute] = ...
    FRAME_LABEL_VECTOR: typing.ClassVar[DicomAttribute] = ...
    FRAME_PRIMARY_ANGLE_VECTOR: typing.ClassVar[DicomAttribute] = ...
    FRAME_SECONDARY_ANGLE_VECTOR: typing.ClassVar[DicomAttribute] = ...
    SLICE_LOCATION_VECTOR: typing.ClassVar[DicomAttribute] = ...
    DISPLAY_WINDOW_LABEL_VECTOR: typing.ClassVar[DicomAttribute] = ...
    NOMINAL_SCANNED_PIXEL_SPACING: typing.ClassVar[DicomAttribute] = ...
    DIGITIZING_DEVICE_TRANSPORT_DIRECTION: typing.ClassVar[DicomAttribute] = ...
    ROTATION_OF_SCANNED_FILM: typing.ClassVar[DicomAttribute] = ...
    IVUS_ACQUISITION: typing.ClassVar[DicomAttribute] = ...
    IVUS_PULLBACK_RATE: typing.ClassVar[DicomAttribute] = ...
    IVUS_GATED_RATE: typing.ClassVar[DicomAttribute] = ...
    IVUS_PULLBACK_START_FRAME_NUMBER: typing.ClassVar[DicomAttribute] = ...
    IVUS_PULLBACK_STOP_FRAME_NUMBER: typing.ClassVar[DicomAttribute] = ...
    LESION_NUMBER: typing.ClassVar[DicomAttribute] = ...
    OUTPUT_POWER: typing.ClassVar[DicomAttribute] = ...
    TRANSDUCER_DATA: typing.ClassVar[DicomAttribute] = ...
    FOCUS_DEPTH: typing.ClassVar[DicomAttribute] = ...
    PROCESSING_FUNCTION: typing.ClassVar[DicomAttribute] = ...
    POSTPROCESSING_FUNCTION: typing.ClassVar[DicomAttribute] = ...
    MECHANICAL_INDEX: typing.ClassVar[DicomAttribute] = ...
    BONE_THERMAL_INDEX: typing.ClassVar[DicomAttribute] = ...
    CRANIAL_THERMAL_INDEX: typing.ClassVar[DicomAttribute] = ...
    SOFT_TISSUE_THERMAL_INDEX: typing.ClassVar[DicomAttribute] = ...
    SOFT_TISSUE_FOCUS_THERMAL_INDEX: typing.ClassVar[DicomAttribute] = ...
    SOFT_TISSUE_SURFACE_THERMAL_INDEX: typing.ClassVar[DicomAttribute] = ...
    DEPTH_OF_SCAN_FIELD: typing.ClassVar[DicomAttribute] = ...
    PATIENT_POSITION: typing.ClassVar[DicomAttribute] = ...
    VIEW_POSITION: typing.ClassVar[DicomAttribute] = ...
    PROJECTION_EPONYMOUS_NAME_CODE: typing.ClassVar[DicomAttribute] = ...
    SENSITIVITY: typing.ClassVar[DicomAttribute] = ...
    SEQUENCE_OF_ULTRASOUND_REGIONS: typing.ClassVar[DicomAttribute] = ...
    REGION_SPATIAL_FORMAT: typing.ClassVar[DicomAttribute] = ...
    REGION_DATA_TYPE: typing.ClassVar[DicomAttribute] = ...
    REGION_FLAGS: typing.ClassVar[DicomAttribute] = ...
    REGION_LOCATION_MIN_X0: typing.ClassVar[DicomAttribute] = ...
    REGION_LOCATION_MIN_Y0: typing.ClassVar[DicomAttribute] = ...
    REGION_LOCATION_MAX_X1: typing.ClassVar[DicomAttribute] = ...
    REGION_LOCATION_MAX_Y1: typing.ClassVar[DicomAttribute] = ...
    REFERENCE_PIXEL_X0: typing.ClassVar[DicomAttribute] = ...
    REFERENCE_PIXEL_Y0: typing.ClassVar[DicomAttribute] = ...
    PHYSICAL_UNITS_X_DIRECTION: typing.ClassVar[DicomAttribute] = ...
    PHYSICAL_UNITS_Y_DIRECTION: typing.ClassVar[DicomAttribute] = ...
    REFERENCE_PIXEL_PHYSICAL_VALUE_X: typing.ClassVar[DicomAttribute] = ...
    REFERENCE_PIXEL_PHYSICAL_VALUE_Y: typing.ClassVar[DicomAttribute] = ...
    PHYSICAL_DELTA_X: typing.ClassVar[DicomAttribute] = ...
    PHYSICAL_DELTA_Y: typing.ClassVar[DicomAttribute] = ...
    TRANSDUCER_FREQUENCY: typing.ClassVar[DicomAttribute] = ...
    TRANSDUCER_TYPE: typing.ClassVar[DicomAttribute] = ...
    PULSE_REPETITION_FREQUENCY: typing.ClassVar[DicomAttribute] = ...
    DOPPLER_CORRECTION_ANGLE: typing.ClassVar[DicomAttribute] = ...
    STEERING_ANGLE: typing.ClassVar[DicomAttribute] = ...
    DOPPLER_SAMPLE_VOLUME_X_POSITION: typing.ClassVar[DicomAttribute] = ...
    DOPPLER_SAMPLE_VOLUME_Y_POSITION: typing.ClassVar[DicomAttribute] = ...
    TM_LINE_POSITION_X0: typing.ClassVar[DicomAttribute] = ...
    TM_LINE_POSITION_Y0: typing.ClassVar[DicomAttribute] = ...
    TM_LINE_POSITION_X1: typing.ClassVar[DicomAttribute] = ...
    TM_LINE_POSITION_Y1: typing.ClassVar[DicomAttribute] = ...
    PIXEL_COMPONENT_ORGANIZATION: typing.ClassVar[DicomAttribute] = ...
    PIXEL_COMPONENT_MASK: typing.ClassVar[DicomAttribute] = ...
    PIXEL_COMPONENT_RANGE_START: typing.ClassVar[DicomAttribute] = ...
    PIXEL_COMPONENT_RANGE_STOP: typing.ClassVar[DicomAttribute] = ...
    PIXEL_COMPONENT_PHYSICAL_UNITS: typing.ClassVar[DicomAttribute] = ...
    PIXEL_COMPONENT_DATA_TYPE: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_TABLE_BREAK_POINTS: typing.ClassVar[DicomAttribute] = ...
    TABLE_OF_X_BREAK_POINTS: typing.ClassVar[DicomAttribute] = ...
    TABLE_OF_Y_BREAK_POINTS: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_TABLE_ENTRIES: typing.ClassVar[DicomAttribute] = ...
    TABLE_OF_PIXEL_VALUES: typing.ClassVar[DicomAttribute] = ...
    TABLE_OF_PARAMETER_VALUES: typing.ClassVar[DicomAttribute] = ...
    R_WAVE_TIME_VECTOR: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_CONDITIONS_NOMINAL_FLAG: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_TEMPERATURE: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_TYPE: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_CONFIGURATION: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_DESCRIPTION: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_MODE: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_ID: typing.ClassVar[DicomAttribute] = ...
    DATE_OF_LAST_DETECTOR_CALIBRATION: typing.ClassVar[DicomAttribute] = ...
    TIME_OF_LAST_DETECTOR_CALIBRATION: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_TIME_SINCE_LAST_EXPOSURE: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_ACTIVE_TIME: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_ACTIVATION_OFFSET: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_BINNING: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_ELEMENT_PHYSICAL_SIZE: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_ELEMENT_SPACING: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_ACTIVE_SHAPE: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_ACTIVE_DIMENSIONS: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_ACTIVE_ORIGIN: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_MANUFACTURER_NAME: typing.ClassVar[DicomAttribute] = ...
    DETECTOR_MODEL_NAME: typing.ClassVar[DicomAttribute] = ...
    FOV_ORIGIN: typing.ClassVar[DicomAttribute] = ...
    FOV_ROTATION: typing.ClassVar[DicomAttribute] = ...
    FOV_HORIZONTAL_FLIP: typing.ClassVar[DicomAttribute] = ...
    GRID_ABSORBING_MATERIAL: typing.ClassVar[DicomAttribute] = ...
    GRID_SPACING_MATERIAL: typing.ClassVar[DicomAttribute] = ...
    GRID_THICKNESS: typing.ClassVar[DicomAttribute] = ...
    GRID_PITCH: typing.ClassVar[DicomAttribute] = ...
    GRID_ASPECT_RATIO: typing.ClassVar[DicomAttribute] = ...
    GRID_PERIOD: typing.ClassVar[DicomAttribute] = ...
    GRID_FOCAL_DISTANCE: typing.ClassVar[DicomAttribute] = ...
    FILTER_MATERIAL: typing.ClassVar[DicomAttribute] = ...
    FILTER_THICKNESS_MIN: typing.ClassVar[DicomAttribute] = ...
    FILTER_THICKNESS_MAX: typing.ClassVar[DicomAttribute] = ...
    EXPOSURE_CONTROL_MODE: typing.ClassVar[DicomAttribute] = ...
    STUDY_INSTANCE_UID: typing.ClassVar[DicomAttribute] = ...
    SERIES_INSTANCE_UID: typing.ClassVar[DicomAttribute] = ...
    STUDY_ID: typing.ClassVar[DicomAttribute] = ...
    SERIES_NUMBER: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_NUMBER: typing.ClassVar[DicomAttribute] = ...
    INSTANCE_NUMBER: typing.ClassVar[DicomAttribute] = ...
    PATIENT_ORIENTATION: typing.ClassVar[DicomAttribute] = ...
    IMAGE_POSITION: typing.ClassVar[DicomAttribute] = ...
    IMAGE_POSITION_PATIENT: typing.ClassVar[DicomAttribute] = ...
    IMAGE_ORIENTATION_PATIENT: typing.ClassVar[DicomAttribute] = ...
    LOCATION: typing.ClassVar[DicomAttribute] = ...
    FRAME_OF_REFERENCE_UID: typing.ClassVar[DicomAttribute] = ...
    IMAGE_GEOMETRY_TYPE: typing.ClassVar[DicomAttribute] = ...
    ACQUISITIONS_IN_SERIES: typing.ClassVar[DicomAttribute] = ...
    REFERENCE: typing.ClassVar[DicomAttribute] = ...
    SLICE_LOCATION: typing.ClassVar[DicomAttribute] = ...
    SAMPLES_PER_PIXEL: typing.ClassVar[DicomAttribute] = ...
    SAMPLES_PER_PIXEL_USED: typing.ClassVar[DicomAttribute] = ...
    PHOTOMETRIC_INTERPRETATION: typing.ClassVar[DicomAttribute] = ...
    PLANAR_CONFIGURATION: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_FRAMES: typing.ClassVar[DicomAttribute] = ...
    FRAME_INCREMENT_POINTER: typing.ClassVar[DicomAttribute] = ...
    FRAME_DIMENSION_POINTER: typing.ClassVar[DicomAttribute] = ...
    ROWS: typing.ClassVar[DicomAttribute] = ...
    COLUMNS: typing.ClassVar[DicomAttribute] = ...
    PLANES: typing.ClassVar[DicomAttribute] = ...
    ULTRASOUND_COLOR_DATA_PRESENT: typing.ClassVar[DicomAttribute] = ...
    PIXEL_SPACING: typing.ClassVar[DicomAttribute] = ...
    ZOOM_FACTOR: typing.ClassVar[DicomAttribute] = ...
    ZOOM_CENTER: typing.ClassVar[DicomAttribute] = ...
    PIXEL_ASPECT_RATIO: typing.ClassVar[DicomAttribute] = ...
    CORRECTED_IMAGE: typing.ClassVar[DicomAttribute] = ...
    BITS_ALLOCATED: typing.ClassVar[DicomAttribute] = ...
    BITS_STORED: typing.ClassVar[DicomAttribute] = ...
    HIGH_BIT: typing.ClassVar[DicomAttribute] = ...
    PIXEL_REPRESENTATION: typing.ClassVar[DicomAttribute] = ...
    SMALLEST_IMAGE_PIXEL_VALUE: typing.ClassVar[DicomAttribute] = ...
    LARGEST_IMAGE_PIXEL_VALUE: typing.ClassVar[DicomAttribute] = ...
    SMALLEST_PIXEL_VALUE_IN_SERIES: typing.ClassVar[DicomAttribute] = ...
    LARGEST_PIXEL_VALUE_IN_SERIES: typing.ClassVar[DicomAttribute] = ...
    SMALLEST_IMAGE_PIXEL_VALUE_IN_PLANE: typing.ClassVar[DicomAttribute] = ...
    LARGEST_IMAGE_PIXEL_VALUE_IN_PLANE: typing.ClassVar[DicomAttribute] = ...
    PIXEL_PADDING_VALUE: typing.ClassVar[DicomAttribute] = ...
    QUALITY_CONTROL_IMAGE: typing.ClassVar[DicomAttribute] = ...
    BURNED_IN_ANNOTATION: typing.ClassVar[DicomAttribute] = ...
    PIXEL_INTENSITY_RELATIONSHIP: typing.ClassVar[DicomAttribute] = ...
    PIXEL_SIGN: typing.ClassVar[DicomAttribute] = ...
    WINDOW_CENTER: typing.ClassVar[DicomAttribute] = ...
    WINDOW_WIDTH: typing.ClassVar[DicomAttribute] = ...
    RESCALE_INTERCEPT: typing.ClassVar[DicomAttribute] = ...
    RESCALE_SLOPE: typing.ClassVar[DicomAttribute] = ...
    RESCALE_TYPE: typing.ClassVar[DicomAttribute] = ...
    WINDOW_CENTER_AND_WIDTH_EXPLANATION: typing.ClassVar[DicomAttribute] = ...
    RECOMMENDED_VIEWING_MODE: typing.ClassVar[DicomAttribute] = ...
    RED_LUT_DESCRIPTOR: typing.ClassVar[DicomAttribute] = ...
    GREEN_LUT_DESCRIPTOR: typing.ClassVar[DicomAttribute] = ...
    BLUE_LUT_DESCRIPTOR: typing.ClassVar[DicomAttribute] = ...
    PALETTE_LUT_UID: typing.ClassVar[DicomAttribute] = ...
    RED_LUT_DATA: typing.ClassVar[DicomAttribute] = ...
    GREEN_LUT_DATA: typing.ClassVar[DicomAttribute] = ...
    BLUE_LUT_DATA: typing.ClassVar[DicomAttribute] = ...
    SEGMENTED_RED_LUT_DATA: typing.ClassVar[DicomAttribute] = ...
    SEGMENTED_GREEN_LUT_DATA: typing.ClassVar[DicomAttribute] = ...
    SEGMENTED_BLUE_LUT_DATA: typing.ClassVar[DicomAttribute] = ...
    IMPLANT_PRESENT: typing.ClassVar[DicomAttribute] = ...
    PARTIAL_VIEW: typing.ClassVar[DicomAttribute] = ...
    PARTIAL_VIEW_DESCRIPTION: typing.ClassVar[DicomAttribute] = ...
    LOSSY_IMAGE_COMPRESSION: typing.ClassVar[DicomAttribute] = ...
    LOSSY_IMAGE_COMPRESSION_RATIO: typing.ClassVar[DicomAttribute] = ...
    LOSSY_IMAGE_COMPRESSION_METHOD: typing.ClassVar[DicomAttribute] = ...
    MODALITY_LUT_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    LUT_DESCRIPTOR: typing.ClassVar[DicomAttribute] = ...
    LUT_EXPLANATION: typing.ClassVar[DicomAttribute] = ...
    MODALITY_LUT_TYPE: typing.ClassVar[DicomAttribute] = ...
    LUT_DATA: typing.ClassVar[DicomAttribute] = ...
    VOI_LUT_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    SOFTCOPY_VOI_LUT_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    BIPLANE_ACQUISITION_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REPRESENTATIVE_FRAME_NUMBER: typing.ClassVar[DicomAttribute] = ...
    FRAME_NUMBERS_OF_INTEREST: typing.ClassVar[DicomAttribute] = ...
    FRAME_OF_INTEREST_DESCRIPTION: typing.ClassVar[DicomAttribute] = ...
    FRAME_OF_INTEREST_TYPE: typing.ClassVar[DicomAttribute] = ...
    R_WAVE_POINTER: typing.ClassVar[DicomAttribute] = ...
    MASK_SUBTRACTION_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    MASK_OPERATION: typing.ClassVar[DicomAttribute] = ...
    APPLICABLE_FRAME_RANGE: typing.ClassVar[DicomAttribute] = ...
    MASK_FRAME_NUMBERS: typing.ClassVar[DicomAttribute] = ...
    CONTRAST_FRAME_AVERAGING: typing.ClassVar[DicomAttribute] = ...
    MASK_SUBPIXEL_SHIFT: typing.ClassVar[DicomAttribute] = ...
    TID_OFFSET: typing.ClassVar[DicomAttribute] = ...
    MASK_OPERATION_EXPLANATION: typing.ClassVar[DicomAttribute] = ...
    DATA_POINT_ROWS: typing.ClassVar[DicomAttribute] = ...
    DATA_POINT_COLUMNS: typing.ClassVar[DicomAttribute] = ...
    SIGNAL_DOMAIN_COLUMNS: typing.ClassVar[DicomAttribute] = ...
    DATA_REPRESENTATION: typing.ClassVar[DicomAttribute] = ...
    PIXEL_MEASURES_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    FRAME_VOI_LUT_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    PIXEL_VALUE_TRANSFORMATION_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    SIGNAL_DOMAIN_ROWS: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_ENERGY_WINDOWS: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_DETECTORS: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_ROTATIONS: typing.ClassVar[DicomAttribute] = ...
    SLICE_VECTOR: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_SLICES: typing.ClassVar[DicomAttribute] = ...
    TYPE_OF_DETECTOR_MOTION: typing.ClassVar[DicomAttribute] = ...
    IMAGE_ID: typing.ClassVar[DicomAttribute] = ...
    ICON_IMAGE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    BORDER_DENSITY: typing.ClassVar[DicomAttribute] = ...
    PIXEL_DATA_LENGTH: typing.ClassVar[DicomAttribute] = ...
    EXTENDED_OFFSET_TABLE: typing.ClassVar[DicomAttribute] = ...
    EXTENDED_OFFSET_TABLE_LENGTHS: typing.ClassVar[DicomAttribute] = ...
    FLOAT_PIXEL_DATA: typing.ClassVar[DicomAttribute] = ...
    DOUBLE_FLOAT_PIXEL_DATA: typing.ClassVar[DicomAttribute] = ...
    PIXEL_DATA: typing.ClassVar[DicomAttribute] = ...
    ITEM: typing.ClassVar[DicomAttribute] = ...
    ITEM_DELIMITATION_ITEM: typing.ClassVar[DicomAttribute] = ...
    SEQUENCE_DELIMITATION_ITEM: typing.ClassVar[DicomAttribute] = ...
    TRAILING_PADDING: typing.ClassVar[DicomAttribute] = ...
    FILE_SET_ID: typing.ClassVar[DicomAttribute] = ...
    FILE_SET_DESCRIPTOR_FILE_ID: typing.ClassVar[DicomAttribute] = ...
    CHARSET_OF_FILE_SET_DESCRIPTOR_FILE: typing.ClassVar[DicomAttribute] = ...
    OFFSET_FIRST_DIRECTORY_RECORD: typing.ClassVar[DicomAttribute] = ...
    OFFSET_LAST_DIRECTORY_RECORD: typing.ClassVar[DicomAttribute] = ...
    FILE_SET_CONSISTENCY_FLAG: typing.ClassVar[DicomAttribute] = ...
    DIRECTORY_RECORD_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    OFFSET_OF_NEXT_DIRECTORY_RECORD: typing.ClassVar[DicomAttribute] = ...
    RECORD_IN_USE_FLAG: typing.ClassVar[DicomAttribute] = ...
    OFFSET_OF_REFERENCED_DIRECTORY: typing.ClassVar[DicomAttribute] = ...
    DIRECTORY_RECORD_TYPE: typing.ClassVar[DicomAttribute] = ...
    PRIVATE_RECORD_UID: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_FILE_ID: typing.ClassVar[DicomAttribute] = ...
    MRDR_RECORD_OFFSET: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_SOP_CLASS_UID_FILE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_SOP_INSTANCE_UID_FILE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_TRANSFER_SYNTAX_UID_FILE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_RELATED_SOP_CLASS_UID_FILE: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_REFERENCES: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_DURATION: typing.ClassVar[DicomAttribute] = ...
    DIMENSION_ORGANIZATION_TYPE: typing.ClassVar[DicomAttribute] = ...
    DIMENSION_INDEX_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    DIMENSION_INDEX_POINTER: typing.ClassVar[DicomAttribute] = ...
    DIMENSION_INDEX_PRIVATE_CREATOR: typing.ClassVar[DicomAttribute] = ...
    FUNCTIONAL_GROUP_POINTER: typing.ClassVar[DicomAttribute] = ...
    FUNCTIONAL_GROUP_PRIVATE_CREATOR: typing.ClassVar[DicomAttribute] = ...
    IN_CONCATENATION_NUMBER: typing.ClassVar[DicomAttribute] = ...
    CONCATENATION_FRAME_OFFSET_NUMBER: typing.ClassVar[DicomAttribute] = ...
    DIMENSION_ORGANIZATION_UID: typing.ClassVar[DicomAttribute] = ...
    DIMENSION_ORGANIZATION_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    DIMENSION_DESCRIPTION_LABEL: typing.ClassVar[DicomAttribute] = ...
    ILLUMINATION_WAVELENGTH: typing.ClassVar[DicomAttribute] = ...
    ILLUMINATION_TYPE_CODE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    LIGHT_PATH_FILTER_TYPE_STACK_CODE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    LIGHT_PATH_FILTER_PASSTHROUGH_WAVELENGTH: typing.ClassVar[DicomAttribute] = ...
    LIGHT_PATH_FILTER_PASS_BAND: typing.ClassVar[DicomAttribute] = ...
    IMAGE_PATH_FILTER_PASSTHROUGH_WAVELENGTH: typing.ClassVar[DicomAttribute] = ...
    IMAGE_PATH_FILTER_PASS_BAND: typing.ClassVar[DicomAttribute] = ...
    IMAGE_PATH_FILTER_TYPE_STACK_CODE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    LENSES_CODE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    CHANNEL_DESCRIPTION_CODE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    ICC_PROFILE: typing.ClassVar[DicomAttribute] = ...
    COLOR_SPACE: typing.ClassVar[DicomAttribute] = ...
    CONTAINER_ID: typing.ClassVar[DicomAttribute] = ...
    CONTAINER_ID_ISSUER_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    CONTAINER_TYPE_CODE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    SPECIMEN_ID: typing.ClassVar[DicomAttribute] = ...
    SPECIMEN_UID: typing.ClassVar[DicomAttribute] = ...
    ACQUISITION_CONTEXT_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    SPECIMEN_DESCRIPTION_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    SPECIMEN_ID_ISSUER_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    SPECIMEN_PREP_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    WHOLE_SLIDE_FRAME_TYPE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    X_OFFSET_IN_SLIDE: typing.ClassVar[DicomAttribute] = ...
    Y_OFFSET_IN_SLIDE: typing.ClassVar[DicomAttribute] = ...
    Z_OFFSET_IN_SLIDE: typing.ClassVar[DicomAttribute] = ...
    IMAGED_VOLUME_WIDTH: typing.ClassVar[DicomAttribute] = ...
    IMAGED_VOLUME_HEIGHT: typing.ClassVar[DicomAttribute] = ...
    IMAGED_VOLUME_DEPTH: typing.ClassVar[DicomAttribute] = ...
    TOTAL_PIXEL_MATRIX_COLUMNS: typing.ClassVar[DicomAttribute] = ...
    TOTAL_PIXEL_MATRIX_ROWS: typing.ClassVar[DicomAttribute] = ...
    TOTAL_PIXEL_MATRIX_ORIGIN_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    SPECIMEN_LABEL_IN_IMAGE: typing.ClassVar[DicomAttribute] = ...
    FOCUS_METHOD: typing.ClassVar[DicomAttribute] = ...
    EXTENDED_DEPTH_OF_FIELD: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OF_FOCAL_PLANES: typing.ClassVar[DicomAttribute] = ...
    DISTANCE_BETWEEN_FOCAL_PLANES: typing.ClassVar[DicomAttribute] = ...
    RECOMMENDED_ABSENT_PIXEL_CIELAB_VALUE: typing.ClassVar[DicomAttribute] = ...
    SLIDE_IMAGE_ORIENTATION: typing.ClassVar[DicomAttribute] = ...
    OPTICAL_PATH_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    OPTICAL_PATH_ID: typing.ClassVar[DicomAttribute] = ...
    OPTICAL_PATH_DESCRIPTION: typing.ClassVar[DicomAttribute] = ...
    ILLUMINATOR_TYPE_CODE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    ILLUMINATION_COLOR_CODE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    CONDENSER_LENS_POWER: typing.ClassVar[DicomAttribute] = ...
    OBJECTIVE_LENS_POWER: typing.ClassVar[DicomAttribute] = ...
    OBJECTIVE_LENS_NA: typing.ClassVar[DicomAttribute] = ...
    PALETTE_COLOR_LUT_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    REFERENCED_IMAGE_NAVIGATION_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    OPTICAL_PATH_ID_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    NUMBER_OPTICAL_PATHS: typing.ClassVar[DicomAttribute] = ...
    TOTAL_PIXEL_MATRIX_FOCAL_PLANES: typing.ClassVar[DicomAttribute] = ...
    PRESENTATION_LUT_SHAPE: typing.ClassVar[DicomAttribute] = ...
    PLANE_POSITION_SLIDE_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    COLUMN_POSITION_IN_MATRIX: typing.ClassVar[DicomAttribute] = ...
    ROW_POSITION_IN_MATRIX: typing.ClassVar[DicomAttribute] = ...
    FRAME_CONTENT_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    FRAME_ACQUISITION_DATETIME: typing.ClassVar[DicomAttribute] = ...
    FRAME_REFERENCE_DATETIME: typing.ClassVar[DicomAttribute] = ...
    FRAME_ACQUISITION_DURATION: typing.ClassVar[DicomAttribute] = ...
    DIMENSION_INDEX_VALUES: typing.ClassVar[DicomAttribute] = ...
    SHARED_FUNCTIONAL_GROUPS_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    PER_FRAME_FUNCTIONAL_GROUPS_SEQUENCE: typing.ClassVar[DicomAttribute] = ...
    BARCODE_VALUE: typing.ClassVar[DicomAttribute] = ...
    LABEL_TEXT: typing.ClassVar[DicomAttribute] = ...
    VARIABLE_PIXEL_DATA: typing.ClassVar[DicomAttribute] = ...
    INVALID_PIXEL_DATA: typing.ClassVar[DicomAttribute] = ...
    INVALID: typing.ClassVar[DicomAttribute] = ...
    @staticmethod
    def formatTag(int: int) -> java.lang.String: ...
    @staticmethod
    def get(int: int) -> DicomAttribute: ...
    @typing.overload
    def getDefaultVR(self) -> DicomVR: ...
    @typing.overload
    @staticmethod
    def getDefaultVR(int: int) -> DicomVR: ...
    @typing.overload
    def getDescription(self) -> java.lang.String: ...
    @typing.overload
    @staticmethod
    def getDescription(int: int) -> java.lang.String: ...
    @typing.overload
    def getTag(self) -> int: ...
    @typing.overload
    @staticmethod
    def getTag(string: java.lang.String | str) -> int: ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: type[_valueOf_0__T], string: java.lang.String | str
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: java.lang.String | str) -> DicomAttribute: ...
    @staticmethod
    def values() -> typing.MutableSequence[DicomAttribute]: ...

class DicomFileInfo(java.lang.Comparable["DicomFileInfo"]):
    coreMetadata: loci.formats.CoreMetadata = ...
    file: java.lang.String = ...
    concatenationIndex: int = ...
    tiles: java.util.List = ...
    imageType: java.lang.String = ...
    zOffsets: java.util.List = ...
    edf: bool = ...
    timestamp: ome.xml.model.primitives.Timestamp = ...
    pixelSizeX: ome.units.quantity.Length = ...
    pixelSizeY: ome.units.quantity.Length = ...
    pixelSizeZ: ome.units.quantity.Length = ...
    positionX: java.util.List = ...
    positionY: java.util.List = ...
    positionZ: java.util.List = ...
    channelNames: java.util.List = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String | str): ...
    def compareTo(self, dicomFileInfo: DicomFileInfo) -> int: ...

class DicomTag(java.lang.Comparable["DicomTag"]):
    parent: DicomTag = ...
    children: java.util.List = ...
    tag: int = ...
    attribute: DicomAttribute = ...
    vr: DicomVR = ...
    key: java.lang.String = ...
    value: typing.Any = ...
    elementLength: int = ...
    strategy: ResolutionStrategy = ...
    @typing.overload
    def __init__(self, int: int, dicomVR: DicomVR): ...
    @typing.overload
    def __init__(
        self,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
        boolean: bool,
        long: int,
        boolean2: bool,
    ): ...
    @typing.overload
    def __init__(
        self,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
        boolean: bool,
        long: int,
        boolean2: bool,
        boolean3: bool,
    ): ...
    @typing.overload
    def __init__(self, dicomAttribute: DicomAttribute): ...
    @typing.overload
    def __init__(self, dicomAttribute: DicomAttribute, dicomVR: DicomVR): ...
    def compareTo(self, dicomTag: DicomTag) -> int: ...
    def getEndPointer(self) -> int: ...
    def getNumberValue(self) -> java.lang.Number: ...
    def getStringValue(self) -> java.lang.String: ...
    def getValueStartPointer(self) -> int: ...
    def isPrivateContentCreator(self) -> bool: ...
    def lookupChild(self, dicomAttribute: DicomAttribute) -> DicomTag: ...
    def toString(self) -> java.lang.String: ...
    def validate(self, list: java.util.List[DicomTag]) -> bool: ...
    def validateValue(self) -> None: ...

class DicomTile:
    region: loci.common.Region = ...
    file: java.lang.String = ...
    fileIndex: int = ...
    fileOffset: int = ...
    endOffset: int = ...
    zOffset: float = ...
    channel: int = ...
    last: bool = ...
    isJP2K: bool = ...
    isJPEG: bool = ...
    isRLE: bool = ...
    isDeflate: bool = ...
    def __init__(self): ...

class DicomVR(java.lang.Enum["DicomVR"]):
    AE: typing.ClassVar[DicomVR] = ...
    AS: typing.ClassVar[DicomVR] = ...
    AT: typing.ClassVar[DicomVR] = ...
    CS: typing.ClassVar[DicomVR] = ...
    DA: typing.ClassVar[DicomVR] = ...
    DS: typing.ClassVar[DicomVR] = ...
    DT: typing.ClassVar[DicomVR] = ...
    FD: typing.ClassVar[DicomVR] = ...
    FL: typing.ClassVar[DicomVR] = ...
    IS: typing.ClassVar[DicomVR] = ...
    LO: typing.ClassVar[DicomVR] = ...
    LT: typing.ClassVar[DicomVR] = ...
    OB: typing.ClassVar[DicomVR] = ...
    OD: typing.ClassVar[DicomVR] = ...
    OF: typing.ClassVar[DicomVR] = ...
    OL: typing.ClassVar[DicomVR] = ...
    OV: typing.ClassVar[DicomVR] = ...
    OW: typing.ClassVar[DicomVR] = ...
    PN: typing.ClassVar[DicomVR] = ...
    SH: typing.ClassVar[DicomVR] = ...
    SL: typing.ClassVar[DicomVR] = ...
    SQ: typing.ClassVar[DicomVR] = ...
    SS: typing.ClassVar[DicomVR] = ...
    ST: typing.ClassVar[DicomVR] = ...
    SV: typing.ClassVar[DicomVR] = ...
    TM: typing.ClassVar[DicomVR] = ...
    UC: typing.ClassVar[DicomVR] = ...
    UI: typing.ClassVar[DicomVR] = ...
    UL: typing.ClassVar[DicomVR] = ...
    UN: typing.ClassVar[DicomVR] = ...
    UR: typing.ClassVar[DicomVR] = ...
    US: typing.ClassVar[DicomVR] = ...
    UT: typing.ClassVar[DicomVR] = ...
    UV: typing.ClassVar[DicomVR] = ...
    QQ: typing.ClassVar[DicomVR] = ...
    IMPLICIT: typing.ClassVar[DicomVR] = ...
    RESERVED: typing.ClassVar[DicomVR] = ...
    @staticmethod
    def get(int: int) -> DicomVR: ...
    def getCode(self) -> int: ...
    def getWidth(self) -> int: ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: type[_valueOf_0__T], string: java.lang.String | str
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: java.lang.String | str) -> DicomVR: ...
    @staticmethod
    def values() -> typing.MutableSequence[DicomVR]: ...

class ITagProvider:
    def getTags(self) -> java.util.List[DicomTag]: ...
    def readTagSource(self, string: java.lang.String | str) -> None: ...

class ResolutionStrategy(java.lang.Enum["ResolutionStrategy"]):
    IGNORE: typing.ClassVar[ResolutionStrategy] = ...
    REPLACE: typing.ClassVar[ResolutionStrategy] = ...
    APPEND: typing.ClassVar[ResolutionStrategy] = ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: type[_valueOf_0__T], string: java.lang.String | str
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: java.lang.String | str) -> ResolutionStrategy: ...
    @staticmethod
    def values() -> typing.MutableSequence[ResolutionStrategy]: ...

class DicomJSONProvider(ITagProvider):
    def __init__(self): ...
    def getTags(self) -> java.util.List[DicomTag]: ...
    def readTagSource(self, string: java.lang.String | str) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("loci.formats.dicom")``.

    DicomAttribute: type[DicomAttribute]
    DicomFileInfo: type[DicomFileInfo]
    DicomJSONProvider: type[DicomJSONProvider]
    DicomTag: type[DicomTag]
    DicomTile: type[DicomTile]
    DicomVR: type[DicomVR]
    ITagProvider: type[ITagProvider]
    ResolutionStrategy: type[ResolutionStrategy]
