import typing
from typing import Protocol

import java.awt
import java.io
import java.lang
import java.net
import java.util
import javax.accessibility

class Applet(java.awt.Panel):
    def __init__(self): ...
    def destroy(self) -> None: ...
    def getAccessibleContext(self) -> javax.accessibility.AccessibleContext: ...
    def getAppletContext(self) -> AppletContext: ...
    def getAppletInfo(self) -> java.lang.String: ...
    @typing.overload
    def getAudioClip(self, uRL: java.net.URL) -> AudioClip: ...
    @typing.overload
    def getAudioClip(
        self, uRL: java.net.URL, string: java.lang.String | str
    ) -> AudioClip: ...
    def getCodeBase(self) -> java.net.URL: ...
    def getDocumentBase(self) -> java.net.URL: ...
    @typing.overload
    def getImage(self, uRL: java.net.URL) -> java.awt.Image: ...
    @typing.overload
    def getImage(
        self, uRL: java.net.URL, string: java.lang.String | str
    ) -> java.awt.Image: ...
    def getLocale(self) -> java.util.Locale: ...
    def getParameter(self, string: java.lang.String | str) -> java.lang.String: ...
    def getParameterInfo(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def init(self) -> None: ...
    def isActive(self) -> bool: ...
    def isValidateRoot(self) -> bool: ...
    @staticmethod
    def newAudioClip(uRL: java.net.URL) -> AudioClip: ...
    @typing.overload
    def play(self, uRL: java.net.URL) -> None: ...
    @typing.overload
    def play(self, uRL: java.net.URL, string: java.lang.String | str) -> None: ...
    @typing.overload
    def resize(self, int: int, int2: int) -> None: ...
    @typing.overload
    def resize(self, dimension: java.awt.Dimension) -> None: ...
    def setStub(self, appletStub: AppletStub) -> None: ...
    def showStatus(self, string: java.lang.String | str) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

class AppletContext:
    def getApplet(self, string: java.lang.String | str) -> Applet: ...
    def getApplets(self) -> java.util.Enumeration[Applet]: ...
    def getAudioClip(self, uRL: java.net.URL) -> AudioClip: ...
    def getImage(self, uRL: java.net.URL) -> java.awt.Image: ...
    def getStream(self, string: java.lang.String | str) -> java.io.InputStream: ...
    def getStreamKeys(self) -> java.util.Iterator[java.lang.String]: ...
    def setStream(
        self, string: java.lang.String | str, inputStream: java.io.InputStream
    ) -> None: ...
    @typing.overload
    def showDocument(self, uRL: java.net.URL) -> None: ...
    @typing.overload
    def showDocument(
        self, uRL: java.net.URL, string: java.lang.String | str
    ) -> None: ...
    def showStatus(self, string: java.lang.String | str) -> None: ...

class AppletStub:
    def appletResize(self, int: int, int2: int) -> None: ...
    def getAppletContext(self) -> AppletContext: ...
    def getCodeBase(self) -> java.net.URL: ...
    def getDocumentBase(self) -> java.net.URL: ...
    def getParameter(self, string: java.lang.String | str) -> java.lang.String: ...
    def isActive(self) -> bool: ...

class AudioClip:
    def loop(self) -> None: ...
    def play(self) -> None: ...
    def stop(self) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("java.applet")``.

    Applet: type[Applet]
    AppletContext: type[AppletContext]
    AppletStub: type[AppletStub]
    AudioClip: type[AudioClip]
