import typing
from typing import Protocol

import java.io
import java.lang
import java.util
import jpype
import loci.common
import loci.poi.hpsf
import loci.poi.poifs.dev
import loci.poi.poifs.storage

class BATManaged:
    def countBlocks(self) -> int: ...
    def setStartBlock(self, int: int) -> None: ...

class DocumentDescriptor:
    def __init__(
        self, pOIFSDocumentPath: POIFSDocumentPath, string: java.lang.String | str
    ): ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> java.lang.String: ...

class DocumentInputStream(java.io.InputStream):
    @typing.overload
    def __init__(
        self,
        documentEntry: DocumentEntry,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
    ): ...
    @typing.overload
    def __init__(
        self,
        pOIFSDocument: POIFSDocument,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
    ): ...
    def available(self) -> int: ...
    def close(self) -> None: ...
    def mark(self, int: int) -> None: ...
    def markSupported(self) -> bool: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, byteArray: list[int] | jpype.JArray | bytes) -> int: ...
    @typing.overload
    def read(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> int: ...
    def reset(self) -> None: ...
    def skip(self, long: int) -> int: ...

class DocumentOutputStream(java.io.OutputStream):
    def close(self) -> None: ...
    def flush(self) -> None: ...
    @typing.overload
    def write(self, byteArray: list[int] | jpype.JArray | bytes) -> None: ...
    @typing.overload
    def write(
        self, byteArray: list[int] | jpype.JArray | bytes, int: int, int2: int
    ) -> None: ...
    @typing.overload
    def write(self, int: int) -> None: ...

class Entry:
    def delete(self) -> bool: ...
    def getName(self) -> java.lang.String: ...
    def getParent(self) -> DirectoryEntry: ...
    def isDirectoryEntry(self) -> bool: ...
    def isDocumentEntry(self) -> bool: ...
    def renameTo(self, string: java.lang.String | str) -> bool: ...

class OfficeXmlFileException(java.lang.IllegalArgumentException):
    def __init__(self, string: java.lang.String | str): ...

class POIFSDocumentPath:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, stringArray: list[java.lang.String] | jpype.JArray): ...
    @typing.overload
    def __init__(
        self,
        pOIFSDocumentPath: POIFSDocumentPath,
        stringArray: list[java.lang.String] | jpype.JArray,
    ): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getComponent(self, int: int) -> java.lang.String: ...
    def getParent(self) -> POIFSDocumentPath: ...
    def hashCode(self) -> int: ...
    def length(self) -> int: ...
    def toString(self) -> java.lang.String: ...

class POIFSFileSystem(loci.poi.poifs.dev.POIFSViewable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self, randomAccessInputStream: loci.common.RandomAccessInputStream, int: int
    ): ...
    def createDirectory(self, string: java.lang.String | str) -> DirectoryEntry: ...
    @typing.overload
    def createDocument(
        self,
        string: java.lang.String | str,
        int: int,
        pOIFSWriterListener: POIFSWriterListener | typing.Callable,
    ) -> DocumentEntry: ...
    @typing.overload
    def createDocument(
        self,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
        string: java.lang.String | str,
    ) -> DocumentEntry: ...
    def createDocumentInputStream(
        self, string: java.lang.String | str
    ) -> DocumentInputStream: ...
    def getRoot(self) -> DirectoryEntry: ...
    def getShortDescription(self) -> java.lang.String: ...
    def getViewableArray(self) -> typing.MutableSequence[typing.Any]: ...
    def getViewableIterator(self) -> java.util.Iterator: ...
    @staticmethod
    def main(stringArray: list[java.lang.String] | jpype.JArray) -> None: ...
    def preferArray(self) -> bool: ...
    def writeFilesystem(self, outputStream: java.io.OutputStream) -> None: ...

class POIFSWriterEvent:
    def getLimit(self) -> int: ...
    def getName(self) -> java.lang.String: ...
    def getPath(self) -> POIFSDocumentPath: ...
    def getStream(self) -> DocumentOutputStream: ...

class POIFSWriterListener:
    def processPOIFSWriterEvent(self, pOIFSWriterEvent: POIFSWriterEvent) -> None: ...

class DirectoryEntry(Entry):
    def createDirectory(self, string: java.lang.String | str) -> DirectoryEntry: ...
    @typing.overload
    def createDocument(
        self,
        string: java.lang.String | str,
        int: int,
        pOIFSWriterListener: POIFSWriterListener | typing.Callable,
    ) -> DocumentEntry: ...
    @typing.overload
    def createDocument(
        self,
        string: java.lang.String | str,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
    ) -> DocumentEntry: ...
    def getEntries(self) -> java.util.Iterator: ...
    def getEntry(self, string: java.lang.String | str) -> Entry: ...
    def getEntryCount(self) -> int: ...
    def getStorageClsid(self) -> loci.poi.hpsf.ClassID: ...
    def isEmpty(self) -> bool: ...
    def setStorageClsid(self, classID: loci.poi.hpsf.ClassID) -> None: ...

class DocumentEntry(Entry):
    def getSize(self) -> int: ...

class EntryNode(Entry):
    def delete(self) -> bool: ...
    def getName(self) -> java.lang.String: ...
    def getParent(self) -> DirectoryEntry: ...
    def isDirectoryEntry(self) -> bool: ...
    def isDocumentEntry(self) -> bool: ...
    def renameTo(self, string: java.lang.String | str) -> bool: ...

class POIFSDocument(
    BATManaged, loci.poi.poifs.storage.BlockWritable, loci.poi.poifs.dev.POIFSViewable
):
    @typing.overload
    def __init__(
        self,
        string: java.lang.String | str,
        int: int,
        pOIFSDocumentPath: POIFSDocumentPath,
        pOIFSWriterListener: POIFSWriterListener | typing.Callable,
        int2: int,
    ): ...
    @typing.overload
    def __init__(
        self,
        string: java.lang.String | str,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
        int: int,
    ): ...
    @typing.overload
    def __init__(
        self,
        string: java.lang.String | str,
        listManagedBlockArray: list[loci.poi.poifs.storage.ListManagedBlock]
        | jpype.JArray,
        int: int,
        int2: int,
    ): ...
    @typing.overload
    def __init__(
        self,
        string: java.lang.String | str,
        rawDataBlockArray: list[loci.poi.poifs.storage.RawDataBlock] | jpype.JArray,
        int: int,
    ): ...
    @typing.overload
    def __init__(
        self,
        string: java.lang.String | str,
        smallDocumentBlockArray: list[loci.poi.poifs.storage.SmallDocumentBlock]
        | jpype.JArray,
        int: int,
    ): ...
    def countBlocks(self) -> int: ...
    def getBigBlockSize(self) -> int: ...
    def getBigBlocks(
        self,
    ) -> typing.MutableSequence[loci.poi.poifs.storage.DocumentBlock]: ...
    def getShortDescription(self) -> java.lang.String: ...
    def getSize(self) -> int: ...
    def getSmallBlocks(
        self,
    ) -> typing.MutableSequence[loci.poi.poifs.storage.BlockWritable]: ...
    def getViewableArray(self) -> typing.MutableSequence[typing.Any]: ...
    def getViewableIterator(self) -> java.util.Iterator: ...
    def preferArray(self) -> bool: ...
    def setStartBlock(self, int: int) -> None: ...
    def writeBlocks(self, outputStream: java.io.OutputStream) -> None: ...

class DirectoryNode(EntryNode, DirectoryEntry, loci.poi.poifs.dev.POIFSViewable):
    def createDirectory(self, string: java.lang.String | str) -> DirectoryEntry: ...
    @typing.overload
    def createDocument(
        self,
        string: java.lang.String | str,
        int: int,
        pOIFSWriterListener: POIFSWriterListener | typing.Callable,
    ) -> DocumentEntry: ...
    @typing.overload
    def createDocument(
        self,
        string: java.lang.String | str,
        randomAccessInputStream: loci.common.RandomAccessInputStream,
    ) -> DocumentEntry: ...
    def getEntries(self) -> java.util.Iterator: ...
    def getEntry(self, string: java.lang.String | str) -> Entry: ...
    def getEntryCount(self) -> int: ...
    def getPath(self) -> POIFSDocumentPath: ...
    def getShortDescription(self) -> java.lang.String: ...
    def getStorageClsid(self) -> loci.poi.hpsf.ClassID: ...
    def getViewableArray(self) -> typing.MutableSequence[typing.Any]: ...
    def getViewableIterator(self) -> java.util.Iterator: ...
    def isDirectoryEntry(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def preferArray(self) -> bool: ...
    def setStorageClsid(self, classID: loci.poi.hpsf.ClassID) -> None: ...

class DocumentNode(EntryNode, DocumentEntry, loci.poi.poifs.dev.POIFSViewable):
    def getDocument(self) -> POIFSDocument: ...
    def getShortDescription(self) -> java.lang.String: ...
    def getSize(self) -> int: ...
    def getViewableArray(self) -> typing.MutableSequence[typing.Any]: ...
    def getViewableIterator(self) -> java.util.Iterator: ...
    def isDocumentEntry(self) -> bool: ...
    def preferArray(self) -> bool: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("loci.poi.poifs.filesystem")``.

    BATManaged: type[BATManaged]
    DirectoryEntry: type[DirectoryEntry]
    DirectoryNode: type[DirectoryNode]
    DocumentDescriptor: type[DocumentDescriptor]
    DocumentEntry: type[DocumentEntry]
    DocumentInputStream: type[DocumentInputStream]
    DocumentNode: type[DocumentNode]
    DocumentOutputStream: type[DocumentOutputStream]
    Entry: type[Entry]
    EntryNode: type[EntryNode]
    OfficeXmlFileException: type[OfficeXmlFileException]
    POIFSDocument: type[POIFSDocument]
    POIFSDocumentPath: type[POIFSDocumentPath]
    POIFSFileSystem: type[POIFSFileSystem]
    POIFSWriterEvent: type[POIFSWriterEvent]
    POIFSWriterListener: type[POIFSWriterListener]
